const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{
for(const width of [1440,1024]){
 const p=await browser.newPage({viewport:{width,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('https://**/*',r=>r.abort());await p.route('http://localhost:43123/**',r=>{const name=new URL(r.request().url()).pathname;if(name.endsWith('buyer-feed.json'))return r.fulfill({json:{schema:1,sources:[],listings:[]}});const f=path.resolve('01-crm','.'+name);return r.fulfill({contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css',body:fs.readFileSync(f)});});
 await p.goto('http://localhost:43123/index.html');await p.evaluate(()=>{DB=[{id:'confirmation',name:'買方長姓名測試',types:['經營買方'],bDemands:[{areaCities:['新北市'],matchCriteria:{searchPurpose:'住宅'}}],buyerMatching:{auto:true}}];persist();BuyerMatching.open('confirmation');});
 await p.waitForFunction(()=>document.querySelector('#bmStatus').textContent.includes('最後取得'));
 await p.evaluate(()=>{const base={source:'591',city:'新北市',district:'板橋區',price:99999999,area:9999,age:20,floor:10,rooms:4,type:'電梯大樓',address:'新北市板橋區文化路一段很長的社區門牌地址'.repeat(5),title:'具有很長名稱的物件與車位說明'.repeat(6)};BuyerResults.ingest(DB[0],{schema:1,includeExcluded:true,generatedAt:new Date().toISOString(),sources:[{id:'591',status:'ok'}],listings:[{...base,id:'591:1',usage:'住家用'},{...base,id:'591:2',price:3000},{...base,id:'591:3',usage:'工業用'}]});document.querySelector('#bmSource').dispatchEvent(new Event('change'));});

 await p.evaluate(async()=>{await BuyerResults.applyChecks(DB[0],[{id:'591:2',usage:'住家用',usageEvidence:'測試明確欄位',elevator:true,rooms:2,detailCheckedAt:'2030-01-01T10:00:00Z'}]);BuyerResults.ingest(DB[0],{schema:1,includeExcluded:true,generatedAt:'2030-01-02T10:00:00Z',sources:[{id:'591',status:'ok'}],listings:[{id:'591:2',source:'591',city:'新北市',price:2800,usage:'',rooms:null,elevator:null}]});await BuyerResults.flush();await BuyerResults.ready([DB[0].id]);});
 let row=await p.evaluate(()=>BuyerResults.rows(DB[0]).find(p=>p.id==='591:2'));assert.equal(row.usage,'住家用');assert.equal(row.rooms,2);assert.equal(row.elevator,true);assert.equal(row.price,2800);assert.equal(row.fieldCheckedAt.usage,'2030-01-01T10:00:00Z');
 await p.evaluate(async()=>{await BuyerResults.applyChecks(DB[0],[{id:'591:2',usage:'一般事務所',detailCheckedAt:'2030-01-03T10:00:00Z'}]);await BuyerResults.flush();await BuyerResults.ready([DB[0].id]);});row=await p.evaluate(()=>BuyerResults.rows(DB[0]).find(p=>p.id==='591:2'));assert.equal(row.usage,'一般事務所');await p.locator('#bmView').selectOption('excluded');assert(await p.locator('.bm-card[data-id="591:2"]').count());assert.deepEqual(errors,[]);await p.close();console.log('PASS '+width+' actual IndexedDB sparse feed retention, field timestamps, newer contradiction and reclassification');
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
