const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{
const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
const image=JSON.parse(fs.readFileSync('01-crm/data/buyer-feed.json','utf8')).listings.find(x=>x.image).image;
await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.request().url().startsWith('https://yccdn.yungching.com.tw/')?r.fulfill({contentType:'image/jpeg',body:fs.readFileSync(process.argv[2]+'/sample-photo.jpg')}):r.abort());
await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);return r.fulfill({contentType:f.endsWith('.html')?'text/html; charset=utf-8':f.endsWith('.js')?'text/javascript; charset=utf-8':'text/css',body:fs.readFileSync(f)});});
await p.addInitScript(()=>window.addEventListener('message',e=>{if(e.data?.channel==='CRM_BUYER_REQUEST')window.postMessage({channel:'CRM_BUYER_RESPONSE',id:e.data.id,result:e.data.type==='hello'?{version:3,extensionVersion:'1.2.2'}:e.data.type==='sync'?{saved:e.data.payload.length}:{}},'*');}));await p.goto('http://localhost:43123/index.html');await p.evaluate(async image=>{DB=[{id:'group-test',name:'範例買方',type:'經營買方',types:['經營買方'],buyerMatching:{auto:true},bDemands:[{areaDisplay:'新北市板橋區',areaCities:['新北市'],areaDists:['板橋區']}]}];persist();await BuyerResults.ready(['group-test']);const base={city:'新北市',district:'板橋區',address:'新北市板橋區民權路202巷',area:23.23,floor:1,age:52,price:1988,rooms:3,image};BuyerResults.ingest(DB[0],{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:['民權路方正可停車一樓','板橋車站 前後增建一樓','近板橋車站 民權方正一樓','板橋車站 前有小庭院','稀有雙面臨路一樓・大降價','近板橋車站公寓一樓門口可停車'].map((title,i)=>({...base,id:'sample:'+i,source:['yungching','sinyi','591','591','591','sinyi'][i],title,floor:i===3?null:1,rooms:i===3?5:3,address:i===3?'新北市板橋區民權路':base.address,area:i===3?23.02:i<4?23.23:22.61,price:i<4?1988:i===4?1880:2099,image:i===4?'https://invalid.example/missing.jpg':i===5?'':image,url:'https://sale.591.com.tw/home/house/detail/2/'+i+'.html'}))});await BuyerResults.flush();BuyerMatching.open('group-test');},image);
await p.waitForSelector('.bm-property-group');await p.waitForTimeout(1800);assert(await p.locator('img.bm-thumb').first().evaluate(e=>e.complete&&e.naturalWidth>0));
const alignment=await p.locator('.bm-card').first().evaluate(e=>{const a=e.querySelector('.bm-row-main>[data-action=save]').getBoundingClientRect(),b=e.querySelector('.bm-detail-button').getBoundingClientRect();return Math.abs(a.top-b.top)<1&&Math.abs(a.height-b.height)<1;});assert(alignment);assert.equal(await p.locator('#bmSort').inputValue(),'price:asc');assert.equal(await p.locator('.bm-property-group').count(),1);assert.equal(await p.locator('.bm-property-group>.bm-card>.bm-change-marker').innerText(),'New');assert((await p.locator('#bmCount').innerText()).includes('3 組候選／6 筆刊登'));assert.equal(await p.locator('.bm-card:visible').count(),3);
assert(await p.locator('#bmAcknowledge').isVisible());assert.equal(await p.locator('.bm-result-filters').innerText().then(x=>x.includes('null')),false);assert(!(await p.locator('#bmExport').isVisible()));await p.locator('.bm-info-tools>summary').click();assert(await p.locator('#bmExport').isVisible());assert(await p.locator('#bmRefresh').isVisible());await p.locator('.bm-info-tools>summary').click();
assert((await p.locator('.bm-property-group>.bm-card>.bm-row-sub>.bm-row-sources').innerText()).includes('永慶（1）'));assert((await p.locator('.bm-property-group>.bm-card>.bm-row-sub>.bm-row-sources').innerText()).includes('信義（1）'));assert((await p.locator('.bm-property-group>.bm-card>.bm-row-sub>.bm-row-sources').innerText()).includes('591（2）'));
assert((await p.locator('.bm-property-group>.bm-card>.bm-row-sub').innerText()).includes('樓層待確認／房數不一致／地址待確認'));const titleLink=p.locator('.bm-title-link:visible').first();assert.equal(await titleLink.getAttribute('target'),'_blank');const expectedURL=await titleLink.getAttribute('href');await p.context().route('https://sale.591.com.tw/home/house/detail/2/**',r=>r.fulfill({contentType:'text/html',body:'<title>Listing link test</title>'}));const popupPromise=p.waitForEvent('popup');await titleLink.click();const popup=await popupPromise;assert.equal(popup.url(),expectedURL);await popup.close();assert.equal(await p.locator('#bmView').inputValue(),'all');assert.equal(await p.locator('#bmView option').count(),5);const prices=()=>p.locator('#bmResults>.bm-card>.bm-row-main>.bm-price,#bmResults>.bm-property-group>.bm-card>.bm-row-main>.bm-price').allTextContents();await p.locator('#bmSort').selectOption('price:asc');assert.deepEqual(await prices(),['1,880 萬','1,988 萬','2,099 萬']);await p.locator('#bmSort').selectOption('price:desc');assert.deepEqual(await prices(),['2,099 萬','1,988 萬','1,880 萬']);await p.locator('#bmSort').selectOption('unit:asc');assert.deepEqual(await prices(),['1,880 萬','1,988 萬','2,099 萬']);assert.equal(await p.locator('.bm-property-group').count(),1);
for(const width of [1440,1024]){await p.setViewportSize({width,height:1000});await p.locator('#buyerMatchDialog').evaluate(e=>e.scrollTop=0);assert(await p.locator('#buyerMatchDialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1));if(process.argv[2])await p.screenshot({path:process.argv[2]+'/merge-expanded-'+width+'.png'});}
const toolbarTop=await p.locator('.bm-toolbar').evaluate(e=>e.getBoundingClientRect().top);await p.locator('#bmResults').evaluate(e=>{e.style.maxHeight='170px';e.scrollTop=150;});assert.equal(await p.locator('.bm-toolbar').evaluate(e=>e.getBoundingClientRect().top),toolbarTop);assert(await p.locator('#bmResults').evaluate(e=>e.scrollTop>0));await p.locator('#bmResults').evaluate(e=>{e.style.maxHeight='';e.scrollTop=0;});const expand=async()=>{if(await p.locator('.bm-group-badge').getAttribute('aria-expanded')==='false')await p.locator('.bm-group-badge').click();};await expand();assert.equal(await p.locator('.bm-card:visible').count(),6);assert(await p.locator('.bm-variants').isVisible());assert(await p.locator('.bm-variants').evaluate(e=>e.getBoundingClientRect().left-e.parentElement.getBoundingClientRect().left>=35));assert.equal(await p.locator('.bm-detail-button').first().innerText(),'追蹤');if(process.argv[2])await p.screenshot({path:process.argv[2]+'/merge-list-expanded.png'});
const target=p.locator('[data-id="sample:3"]');await target.locator('[data-action=save]').click();assert.equal(await p.locator('#bmFavorites').innerText(),'收藏清單（1）');await expand();await target.locator(':scope > .bm-row-main > [data-track=status]').selectOption('recommended');await expand();await target.locator(':scope > .bm-row-main > .bm-detail-button').click();assert(await target.locator('.bm-row-panel').evaluate(e=>e.clientWidth>e.closest('.bm-card').clientWidth*.9));if(process.argv[2])await p.screenshot({path:process.argv[2]+'/merge-detail-wide.png'});await target.locator(':scope > .bm-row-details > .bm-row-panel > .bm-track [data-track=reason]').fill('只推薦這筆，確認屋主及約看時間。'.repeat(30));await target.locator(':scope > .bm-row-details > .bm-row-panel > .bm-track [data-track=reason]').blur();assert.equal(await p.evaluate(()=>DB[0].buyerMatching.tracking['sample:3'].status),'recommended');assert.equal(await p.evaluate(()=>DB[0].buyerMatching.tracking['sample:0']),undefined);assert(await target.locator(':scope > .bm-row-details > .bm-row-panel > .bm-track textarea').evaluate(e=>e.scrollHeight<=e.clientHeight+3));
await p.reload();await p.evaluate(()=>BuyerMatching.open('group-test'));await p.waitForSelector('.bm-property-group');assert.equal(await p.locator('#bmSort').inputValue(),'price:asc');await p.locator('#bmSource').selectOption('yungching');await p.locator('#bmFavorites').click();assert.equal(await p.locator('#bmSource').inputValue(),'');assert.equal(await p.locator('#bmView').inputValue(),'saved');assert.equal(await p.locator('#bmFavorites').innerText(),'收藏清單（1）');assert.equal(await p.locator('.bm-card').count(),1);assert.equal(await p.locator('[data-track=status]').inputValue(),'recommended');assert((await p.locator('textarea[data-track=reason]').inputValue()).length>100);assert.equal(await p.evaluate(()=>BuyerResults.rows(DB[0]).length),6);
await p.locator('#bmView').selectOption('all');await p.locator('.bm-card').first().evaluate(e=>{e.querySelector('h3').textContent='長社區名稱與物件說明'.repeat(25);e.querySelector('.bm-address').textContent='新北市板橋區文化路一段長地址'.repeat(20);e.querySelector('.bm-price').textContent='99,999,999 萬';});for(const width of [1440,1024]){await p.setViewportSize({width,height:1000});assert(await p.locator('.bm-card').first().evaluate(e=>e.scrollWidth<=e.clientWidth+1));assert(await p.locator('h3').first().evaluate(e=>e.scrollHeight<=e.clientHeight+1));}
await p.locator('#bmClose').click();await p.evaluate(()=>{setFilter('經營買方',document.querySelector('.filter-btn'));});await p.setViewportSize({width:390,height:844});assert(!(await p.locator('#buyerMatchEntry').isVisible()));assert.equal(await p.locator('.card-auto-match:visible').count(),0);await p.setViewportSize({width:1440,height:1000});assert(await p.locator('#buyerMatchEntry').isVisible());assert.deepEqual(errors,[]);console.log('PASS compact desktop rows, source names, grouping, per-listing save/tracking/reload, long content, visible controls, hidden mobile entries');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
