{
const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
(async()=>{const c=vm.createContext({AbortSignal,Date,fetch:async()=>{throw Error('offline')}});vm.runInContext(fs.readFileSync('01-crm/tools/buyer-browser/read.js','utf8'),c);const row={id:'yungching:1',source:'yungching',url:'https://example.com/1'};let [r]=await c.crmVerifyListings([row]);assert.equal(r.detailStatus,'failed');assert(r.detailAttemptedAt);assert.equal(r.detailCheckedAt,undefined);c.fetch=async()=>({status:404,ok:false});[r]=await c.crmVerifyListings([row]);assert.equal(r.availability,'unavailable');assert.equal(r.detailStatus,'ok');assert(r.detailCheckedAt);console.log('PASS failed fetch has no success timestamp; definitive 404 is unavailable');})().catch(e=>{console.error(e);process.exitCode=1});
}
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),E=require('../buyer-match-engine.js');const source=fs.readFileSync('01-crm/tools/buyer-browser/background.js','utf8'),fn=source.slice(source.indexOf('async function enrichSinyi('),source.indexOf('async function enrich591('));
const d={areaCities:['新北市'],areaDists:['板橋區'],matchCriteria:{areaMin:20,areaBasis:'main',searchPurpose:'住宅'}},row={id:'yungching:7438929',source:'yungching',url:'https://buy.yungching.com.tw/house/7438929',city:'新北市',district:'板橋區',mainArea:null};
let calls=0,failures=1;const store={};function worker(){const context=vm.createContext({BuyerMatchEngine:E,BuyerStorage:{get:async()=>structuredClone(store)},saveSearch:async x=>Object.assign(store,structuredClone(x)),filterTaskRows:x=>x,Date,Map,Promise,AbortSignal,DOMParser:class{parseFromString(){return {}}},setTimeout:f=>f(),fetch:async()=>{calls++;if(failures-->0)throw Object.assign(Error('timeout'),{name:'TimeoutError'});return {ok:true,status:200,text:async()=>''}},crmReadYCDetail:()=>({mainArea:18.35,mainAreaEvidence:'永慶主建物',usage:'集合住宅'}),chrome:{scripting:{executeScript:async o=>{context.rows=o.args[0];return [{result:await vm.runInContext('('+o.func.toString()+')(rows)',context)}]}}}});vm.runInContext(fn,context);return context;}
async function run(c,round='one'){c.task={source:'yungching',roundId:round,demands:[d]};c.data={rows:[row]};return vm.runInContext('enrichSinyi(1,data,task)',c)}
(async()=>{let c=worker(),r=await run(c);assert.equal(calls,2);assert.equal(r.rows[0].detailStatus,'ok');assert.equal(E.evaluate(d,r.rows[0]).status,'excluded');await run(worker());assert.equal(calls,2,'worker restart must not refetch');failures=99;r=await run(worker(),'two');assert.equal(calls,4);assert.equal(r.rows[0].detailStatus,'failed');assert.match(r.rows[0].detailError,/逾時/);await run(worker(),'two');assert.equal(calls,4);failures=0;r=await run(worker(),'three');assert.equal(calls,5);assert.equal(r.rows[0].detailError,'');
const start=source.indexOf('function buildDailyReport('),end=source.indexOf('\nasync function startBatch',start);const ctx=vm.createContext({BuyerMatchEngine:E,tasksFor:()=>[{key:'task',source:'yungching'}]});vm.runInContext(source.slice(start,end),ctx);ctx.job={demands:[d],selection:[{id:'buyer',demands:[d]}],status:'partial',scopeStates:{task:'completed'},sources:{yungching:{status:'partial',completedScopes:1}},feed:{listings:[{...row,detailStatus:'failed',detailError:'詳細頁讀取逾時'}]}};const report=vm.runInContext("buildDailyReport(job,'buyer')",ctx);assert.equal(report.status,'partial');assert.equal(report.members[0].completed,false);assert.match(report.error,/補讀失敗 1 筆/);assert.equal(report.canRetry,false);console.log('PASS transient retry, two-attempt limit, restart persistence, manual new round, verified exclusion and truthful member report');})().catch(e=>{console.error(e);process.exitCode=1});
