const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{
for(const width of [1440,1024]){
 const p=await browser.newPage({viewport:{width,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('https://**/*',r=>r.abort());await p.route('http://localhost:43123/**',r=>{const name=new URL(r.request().url()).pathname;if(name.endsWith('buyer-feed.json'))return r.fulfill({json:{schema:1,sources:[],listings:[]}});const f=path.resolve('01-crm','.'+name);return r.fulfill({contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css',body:fs.readFileSync(f)});});
 await p.goto('http://localhost:43123/index.html');await p.evaluate(()=>{DB=[{id:'confirmation',name:'買方長姓名測試',types:['經營買方'],bDemands:[{areaCities:['新北市'],matchCriteria:{searchPurpose:'住宅'}}],buyerMatching:{auto:true}}];persist();BuyerMatching.open('confirmation');});
 await p.waitForFunction(()=>document.querySelector('#bmStatus').textContent.includes('最後取得'));
 await p.evaluate(()=>{const base={source:'591',city:'新北市',district:'板橋區',price:99999999,area:9999,age:20,floor:10,rooms:4,type:'電梯大樓',address:'新北市板橋區文化路一段很長的社區門牌地址'.repeat(5),title:'具有很長名稱的物件與車位說明'.repeat(6)};BuyerResults.ingest(DB[0],{schema:1,includeExcluded:true,generatedAt:new Date().toISOString(),sources:[{id:'591',status:'ok'}],listings:[{...base,id:'591:1',usage:'住家用'},{...base,id:'591:2',price:3000},{...base,id:'591:3',usage:'工業用'}]});document.querySelector('#bmSource').dispatchEvent(new Event('change'));});
 assert.equal(await p.locator('#bmView').inputValue(),'matched');assert.equal(await p.locator('.bm-card').count(),1);assert.equal(await p.locator('.bm-card').getAttribute('data-id'),'591:1');assert((await p.locator('#bmTabs [data-view=pending]').innerText()).includes('1 筆'));
 await p.locator('#bmTabs [data-view=pending]').click();assert.equal(await p.locator('.bm-card').count(),1);assert.equal(await p.locator('.bm-card').getAttribute('data-id'),'591:2');assert((await p.locator('.bm-row-sub').innerText()).includes('待確認：用途'));

 await p.screenshot({path:require('os').tmpdir()+'/buyer-manual-'+width+'.png'});await p.locator('[data-action="confirm"]').click();assert(await p.locator('#bmConfirmDialog').evaluate(el=>{const r=el.getBoundingClientRect();return Math.abs(r.x+r.width/2-innerWidth/2)<2&&Math.abs(r.y+r.height/2-innerHeight/2)<2;}));await p.screenshot({path:require('os').tmpdir()+'/buyer-confirm-center-'+width+'.png'});await p.locator('#bmConfirmDialog .bm-confirm-accept').click();await p.waitForFunction(()=>!document.querySelector('#bmConfirmDialog')&&!document.querySelector('[data-action="confirm"]')); assert.equal(await p.locator('.bm-card').count(),0);await p.locator('#bmTabs [data-view=matched]').click();assert.equal(await p.locator('.bm-card').count(),2);assert.equal(await p.locator('[data-action="unconfirm"]').count(),1);
 await p.locator('#bmClose').click();await p.evaluate(()=>BuyerMatching.open('confirmation'));await p.waitForSelector('[data-action="unconfirm"]');assert.equal(await p.locator('.bm-card').count(),2);
 await p.locator('[data-action="unconfirm"]').click();await p.locator('#bmTabs [data-view=pending]').click();assert.equal(await p.locator('.bm-card').count(),1);await p.locator('[data-action="confirm"]').click();assert(await p.locator('#bmConfirmDialog').evaluate(el=>{const r=el.getBoundingClientRect();return Math.abs(r.x+r.width/2-innerWidth/2)<2&&Math.abs(r.y+r.height/2-innerHeight/2)<2;}));await p.screenshot({path:require('os').tmpdir()+'/buyer-confirm-center-'+width+'.png'});await p.locator('#bmConfirmDialog .bm-confirm-accept').click();await p.waitForFunction(()=>!document.querySelector('#bmConfirmDialog')&&!document.querySelector('[data-action="confirm"]')); await p.locator('#bmTabs [data-view=matched]').click();
 await p.evaluate(()=>{DB[0].bDemands[0].budgetMax='5000';document.querySelector('#bmSource').dispatchEvent(new Event('change'));});await p.locator('#bmTabs [data-view=pending]').click();assert.equal(await p.locator('[data-action="confirm"]').count(),1);
 await p.locator('[data-action="confirm"]').click();assert(await p.locator('#bmConfirmDialog').evaluate(el=>{const r=el.getBoundingClientRect();return Math.abs(r.x+r.width/2-innerWidth/2)<2&&Math.abs(r.y+r.height/2-innerHeight/2)<2;}));await p.screenshot({path:require('os').tmpdir()+'/buyer-confirm-center-'+width+'.png'});await p.locator('#bmConfirmDialog .bm-confirm-accept').click();await p.waitForFunction(()=>!document.querySelector('#bmConfirmDialog')&&!document.querySelector('[data-action="confirm"]')); await p.evaluate(async()=>{await BuyerResults.applyChecks(DB[0],[{id:'591:2',availability:'unavailable',detailCheckedAt:new Date(Date.now()+2000).toISOString()}]);});await p.locator('#bmView').selectOption('excluded');assert(await p.locator('.bm-card[data-id="591:2"]').count());assert.equal(await p.locator('[data-action="unconfirm"]').count(),0);assert.equal(await p.locator('[data-action="confirm"]').count(),0);assert.deepEqual(errors,[]);await p.close();console.log('PASS '+width+' manual confirmation, reopen persistence, revoke, changed demand invalidation and unavailable exclusion');
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
