const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{
const context=await browser.newContext();await context.route('http://audit.local/**',r=>r.fulfill({body:'<html></html>',contentType:'text/html'}));
async function page(){const p=await context.newPage();await p.goto('http://audit.local/');await p.evaluate(()=>{globalThis.BuyerMatchEngine={evaluate:()=>({status:'matched'})};globalThis.c={id:'audit-buyer',bDemands:[{}]};});await p.addScriptTag({path:path.resolve('01-crm/buyer-results.js')});await p.evaluate(()=>BuyerResults.ready(['audit-buyer']));return p;}
async function ingest(p,id,at){await p.evaluate(async({id,at})=>{BuyerResults.ingest(c,{generatedAt:at,sources:[],listings:[{id:'591:'+id,source:'591',price:1000}]});await BuyerResults.flush();},{id,at});}
const a=await page();await ingest(a,'A','2026-10-05T01:00:00Z');const b=await page();await ingest(b,'B','2026-10-05T02:00:00Z');await ingest(a,'C','2026-10-05T03:00:00Z');const check=await page();const ids=await check.evaluate(()=>BuyerResults.rows(c).map(p=>p.id));assert.deepEqual(ids.sort(),['591:A','591:B','591:C']);console.log('PASS: both tabs retain A/B/C:',ids);
// Ignore broadcasts to force stale caches: transactions must be safe on their own.
await a.evaluate(()=>BroadcastChannel.prototype.postMessage=()=>{});await b.evaluate(()=>BroadcastChannel.prototype.postMessage=()=>{});
await Promise.all([ingest(a,'D','2026-10-05T04:00:00Z'),ingest(b,'E','2026-10-05T04:00:00Z')]);
async function priced(page,price,at){await page.evaluate(async({price,at})=>{BuyerResults.ingest(c,{generatedAt:at,sources:[],listings:[{id:'591:price',source:'591',price}]});await BuyerResults.flush();},{price,at});}
await priced(a,2000,'2026-10-05T05:00:00Z');await priced(b,1800,'2026-10-05T06:00:00Z');await priced(a,1900,'2026-10-05T05:30:00Z');
const latest=await page();const retained=await latest.evaluate(()=>BuyerResults.rows(c));assert.equal(retained.length,6);const drop=retained.find(p=>p.id==='591:price');assert.equal(drop.price,1800);assert.equal(drop.priceBeforeDrop,2000);assert.equal(drop.priceEvents.length,1);assert(drop.priceDroppedAt);console.log('PASS concurrent additions, stale price rejection and cross-tab price drop history');
await context.close();
const ctx=await browser.newContext();await ctx.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:'2026-10-05T00:00:00Z',sources:[],listings:[]}}):r.abort());await ctx.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css',body:fs.readFileSync(f)});});
const p=await ctx.newPage({viewport:{width:1440,height:1000}});await p.goto('http://localhost:43123/index.html');
await p.evaluate(async()=>{DB=[{id:'audit-restore',name:'測試買方',type:'經營買方',types:['經營買方'],buyerMatching:{auto:true},bDemands:[{areaCities:['新北市'],areaDists:['板橋區']}]}];persist();await BuyerResults.ready(['audit-restore']);BuyerMatching.open('audit-restore');});
await p.waitForSelector('#bmImportFile',{state:'attached'});
const eventAt=new Date(Date.now()-30000).toISOString(),readAt=new Date(Date.now()-10000).toISOString(),newerReadAt=new Date().toISOString();
const backup={schema:1,buyerId:'audit-restore',results:{items:{'591:test':{id:'591:test',source:'591',title:'已讀備份物件',city:'新北市',district:'板橋區',price:1000,firstMatchedAt:eventAt,seenAt:eventAt}},runs:[]},tracking:{acknowledgedAt:readAt,saved:['591:test']}};
await p.locator('#bmImportFile').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await p.waitForFunction(()=>document.querySelector('#bmStatus').textContent.includes('已匯入'));
assert.equal(await p.locator('.bm-change-new').count(),0);assert.equal(await p.evaluate(()=>DB[0].buyerMatching.acknowledgedAt),readAt);assert.equal(await p.evaluate(()=>DB[0].schedules?.length||0),0);await p.evaluate(at=>{DB[0].buyerMatching.acknowledgedAt=at;persist();},newerReadAt);await p.locator('#bmImportFile').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await p.waitForFunction(()=>document.querySelector('#bmImportFile').value==='');assert.equal(await p.evaluate(()=>DB[0].buyerMatching.acknowledgedAt),newerReadAt);console.log('PASS: imported read state has no New/reminder replay and never rolls back newer read state');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
