const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{
for(const width of [1440,1024]){
 const p=await browser.newPage({viewport:{width,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('https://**/*',r=>r.abort());await p.route('http://localhost:43123/**',r=>{const name=new URL(r.request().url()).pathname;if(name.endsWith('buyer-feed.json'))return r.fulfill({json:{schema:1,sources:[],listings:[]}});const f=path.resolve('01-crm','.'+name);return r.fulfill({contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css',body:fs.readFileSync(f)});});
 await p.addInitScript(()=>window.addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST')return;const {id,type,payload}=e.data;(window.helperCalls||=[]).push(type);let result={};if(type==='hello')result={version:3,extensionVersion:'1.2.19'};if(type==='sync')result={saved:payload.length};if(type==='progress')result={job:null};if(type==='buyerVerify'){window.verifyCalls=(window.verifyCalls||0)+1;result={checks:payload.rows.map(p=>({id:p.id,detailCheckedAt:new Date(Date.now()+1000).toISOString(),...(p.id==='591:2'?{availability:'unavailable',availabilityReason:'HTTP 404'}:{})}))};}window.postMessage({channel:'CRM_BUYER_RESPONSE',id,result},'*');}));await p.goto('http://localhost:43123/index.html');await p.evaluate(()=>{DB=[{id:'confirmation',name:'買方長姓名測試',types:['經營買方'],bDemands:[{areaCities:['新北市'],matchCriteria:{searchPurpose:'住宅',ageMax:10}}],buyerMatching:{auto:true}}];persist();BuyerMatching.open('confirmation');});
 await p.waitForFunction(()=>document.querySelector('#bmStatus').textContent.includes('最後取得'));
 await p.evaluate(()=>{const base={source:'591',city:'新北市',district:'板橋區',area:40,age:2,floor:10,rooms:3,type:'電梯大樓',usage:'住家用',address:'新北市板橋區文化路一段長地址'.repeat(4),title:'長名稱景觀三房平面車位'.repeat(5)};const today=new Date().toISOString().slice(0,10);BuyerResults.ingest(DB[0],{schema:1,includeExcluded:true,generatedAt:today+'T12:00:00+08:00',sources:[{id:'591',status:'ok'}],listings:[{...base,id:'591:1',price:3450},{...base,id:'591:2',price:2698},{...base,id:'591:3',price:3368}]});document.querySelector('#bmSource').dispatchEvent(new Event('change'));});
 await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>window.verifyCalls||0),0);
 const prices=()=>p.locator('.bm-card').evaluateAll(cards=>cards.map(c=>Number(c.querySelector('.bm-price').textContent.replace(/[^0-9.]/g,''))));assert.deepEqual(await prices(),[2698,3368,3450]);await p.screenshot({path:require('os').tmpdir()+'/buyer-price-sort-'+width+'.png'});await p.locator('#bmSort').selectOption('price:desc');assert.deepEqual(await prices(),[3450,3368,2698]);await p.locator('#bmSort').selectOption('date:desc');assert.deepEqual(await prices(),[2698,3368,3450]);
 assert.deepEqual(errors,[]);await p.close();console.log('PASS same-day price ascending, explicit price descending and date reset',width);
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});