const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{for(const width of [1440,1024,390]){
 const p=await b.newPage({viewport:{width,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.abort());await p.route('http://localhost:43123/**',r=>{const name=decodeURIComponent(new URL(r.request().url()).pathname);if(name.endsWith('buyer-feed.json'))return r.fulfill({json:{schema:1,sources:[],listings:[]}});const f=path.resolve('01-crm','.'+name);return fs.existsSync(f)&&fs.statSync(f).isFile()?r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'}):r.fulfill({status:404,body:''});});
 await p.addInitScript(()=>{window.launchRequests=[];document.addEventListener('click',e=>{const a=e.target.closest('a');if(a?.protocol==='crm-buyer-helper:'){window.launchRequests.push(a.href);e.preventDefault();}},true);});
 await p.goto('http://localhost:43123/index.html');const desktop=await p.locator('#headerMoreBtn').isVisible();const trigger=p.locator(desktop?'#headerMoreBtn':'#mobileSettingBtn'),entry=p.locator((desktop?'#headerMoreMenu':'#mobileSettingMenu')+' button').filter({hasText:'更新小助手'});
 await trigger.click();await entry.click();assert.deepEqual(await p.evaluate(()=>launchRequests),['crm-buyer-helper://update']);assert.equal(await p.locator('.helper-update-dialog').count(),0);assert.equal(await p.locator('dialog[open]').count(),0);assert.equal(await p.locator('.helper-launch-notice').count(),1);
 assert(await p.locator('.helper-launch-notice').evaluate(e=>e.scrollWidth<=e.clientWidth+1));assert.match(await p.locator('.helper-launch-notice a').getAttribute('href'),/\.exe\?v=1\.0\.4$/);await p.screenshot({path:path.join(process.env.TEMP,'helper-launch-'+width+'.png'),fullPage:true});
 await trigger.click();await entry.click();assert.equal(await p.locator('.helper-launch-notice').count(),1);assert.equal(await p.evaluate(()=>launchRequests.length),2);await p.locator('.helper-launch-notice button').click();assert.equal(await p.locator('.helper-launch-notice').count(),0);assert.deepEqual(errors,[]);await p.close();console.log('PASS direct EXE protocol request, no dialog, first-use fallback, repeat click and close',width);
 }}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
