const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST'||['dailyStatus','dailyRetry'].includes(e.data.type))return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='buyerVerify'?{checks:payload.rows.map(p=>({id:p.id,...(['yungching:7417941','591:20734577'].includes(p.id)?{usage:'住家用',usageEvidence:'法定用途',availability:'available'}:{})}))}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');






await p.evaluate(()=>{DB=[{id:'c1',name:'吳尚彥',type:'庫存屋主',types:['庫存屋主'],sProperties:[{inventoryKey:'p1',addr:'台北市中正區重慶南路三段4巷9號3樓'}],inventoryWatch:{p1:{id:'watch1',enabled:true,mode:'road',address:'台北市中正區重慶南路三段4巷9號3樓'}},searchReportEvents:[{id:'inventory-watch:watch1:2026-10-07',date:'2026-10-07',propertyRef:{label:'中正區重慶南路三段3樓'},marketEvents:Object.fromEntries(Array.from({length:5},(_,i)=>[i,'其中一筆已下架']))}]},...['張高銘','鄭勝元','劉傳懷','黃政傑'].map((name,i)=>({id:'more'+i,name,searchReportEvents:[{id:'inventory-watch:w'+i+':2026-10-07',date:'2026-10-07',propertyRef:{label:['帝王別墅','富裔山','大華縱橫','紅布朗花園'][i]},marketEvents:{a:'New',b:'Down',c:'其中一筆已下架'}}]}))];BuyerMatching.refreshBulkResults=async()=>{};InventoryMarket.tick=async()=>{};addEventListener('message',e=>{if(e.data?.channel==='CRM_BUYER_REQUEST'&&e.data.type==='dailyStatus')postMessage({channel:'CRM_BUYER_RESPONSE',id:e.data.id,result:{current:true,day:'2026-10-07',report:{status:'completed',startedAt:'2026-10-07T00:25:00Z',finishedAt:'2026-10-07T00:39:57Z',buyers:{total:4,completed:4},inventory:{total:17,completed:17},members:[]}}},location.origin);});});

await p.evaluate(async()=>{BuyerMatching.refreshBulkResults=()=>new Promise(()=>{});InventoryMarket.tick=()=>new Promise(()=>{});await InventoryMarket.updateState('watch1',()=>({records:{x:{id:'x',availability:'off'}},events:[{id:'old',listingId:'x',kind:'已下架',at:'2026-10-06T00:00:00Z'},{id:'rel',listingId:'x',kind:'重新上架',at:'2026-10-07T00:00:00Z',price:1,before:1},{id:'0',listingId:'x',kind:'已下架',at:'2026-10-07T01:00:00Z'}]}));});
await p.evaluate(()=>DailySearchNotice.open());await p.waitForFunction(()=>document.querySelector('[data-message]')?.textContent==='本機紀錄比對完成');
assert((await p.locator('[data-change-client="c1"]').innerText()).includes('部分新下架 4 筆'));assert.equal(await p.evaluate(()=>DB[0].searchReportSuppressions['0']),'legacy-unverified-relisting-cycle');
await p.locator('.daily-notice [data-close]').last().click();await p.evaluate(()=>{InventoryMarket.cleanLegacyReports=async()=>{throw Error('blocked storage')};});await p.evaluate(()=>DailySearchNotice.open());await p.waitForFunction(()=>document.querySelector('[data-message]')?.textContent.includes('比對未完成'));assert.deepEqual(errors,[]);console.log('PASS actual local cleanup updates report while both network jobs never resolve; explicit failure state');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});