const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST'||['dailyStatus','dailyRetry'].includes(e.data.type))return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='buyerVerify'?{checks:payload.rows.map(p=>({id:p.id,...(['yungching:7417941','591:20734577'].includes(p.id)?{usage:'住家用',usageEvidence:'法定用途',availability:'available'}:{})}))}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');





await p.evaluate(()=>{DB=[{id:'report-test',name:'長姓名測試'.repeat(8),schedules:[{id:'manual',memo:'修圖，回報',date:'2026-10-07'},{id:'inventory-watch:test:2026-10-07',date:'2026-10-07',memo:'新確認下架2筆',marketEvents:{a:'已下架',b:'已下架'},propertyRef:{label:'長社區地址'.repeat(25)}}],searchReportEvents:[{id:'inventory-watch:test:2026-10-07',date:'2026-10-07',marketEvents:{a:'已下架',b:'已下架',c:'New'}}]}];persist();if(_liveItems(DB[0].schedules).length!==1)throw Error('automatic reminder still visible');BuyerMatching.refreshBulkResults=async()=>{};InventoryMarket.tick=async()=>{};window.noticeData={current:true,day:'2026-10-07',report:{status:'running',startedAt:'2026-10-07T00:25:00Z',buyers:{total:4,completed:4},inventory:{total:17,completed:16},members:[{id:'missing',completed:false}],scopes:[{source:'591',district:'新北市',keyword:'很長的社區名稱'.repeat(20),reason:'原站尚未完成'.repeat(20)}],canRetry:true}};window.noticeCalls=[];addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST'||!['dailyStatus','dailyRetry'].includes(e.data.type))return;noticeCalls.push(e.data.type);postMessage({channel:'CRM_BUYER_RESPONSE',id:e.data.id,result:e.data.type==='dailyStatus'?noticeData:{}},location.origin);},true);});
await p.evaluate(()=>DailySearchNotice.check());assert.equal(await p.locator('.daily-notice').count(),0);await p.evaluate(()=>{noticeData.report.status='partial';noticeData.report.finishedAt='2026-10-07T00:39:57Z';});await p.evaluate(()=>DailySearchNotice.check());assert(await p.locator('.daily-notice').isVisible());assert((await p.locator('.daily-notice').innerText()).includes('14 分 57 秒'));assert((await p.locator('.daily-notice-changes').innerText()).includes('已下架 2 筆'));assert.equal(await p.locator('.daily-notice-changes li').count(),1);
await p.locator('[data-change-tab="0"]').click();assert(await p.locator('#dailyChangePanel0').isVisible());assert(await p.locator('#dailyChangePanel1').isHidden());await p.keyboard.press('ArrowRight');assert(await p.locator('#dailyChangePanel1').isVisible());
await p.evaluate(()=>{window.openedCase=null;InventoryMarket.entries=()=>[{c:DB[0],config:{id:'test'},key:'exact-property'}];InventoryMarket.open=key=>window.openedCase=key;});await p.locator('[data-change-client]').click();assert.equal(await p.evaluate(()=>openedCase),'exact-property');for(const width of [1440,1024,780]){await p.setViewportSize({width,height:1000});assert(await p.locator('.daily-notice').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await p.screenshot({path:path.join(process.env.TEMP,'daily-notice-'+width+'.png'),fullPage:true});}await p.locator('.daily-notice [data-close]').last().click();await p.locator('.daily-notice').waitFor({state:'detached'});await p.evaluate(()=>DailySearchNotice.check());assert.equal(await p.locator('.daily-notice').count(),0);await p.evaluate(()=>DailySearchNotice.open());assert(await p.locator('.daily-notice').isVisible());await p.locator('.daily-notice [data-retry]').click();await p.waitForFunction(()=>document.querySelector('[data-message]')?.textContent.includes('已開始重試'));await p.locator('.daily-notice [data-close]').last().click();await p.locator('.daily-notice').waitFor({state:'detached'});assert(await p.evaluate(()=>JSON.parse(localStorage.getItem('crmDailySearchNotices')).length===1));await p.evaluate(()=>{BuyerMatching.refreshBulkResults=()=>new Promise(()=>{});InventoryMarket.tick=()=>new Promise(()=>{});window.openPromise=DailySearchNotice.open();if(!document.querySelector('.daily-notice[open]'))throw Error('report did not open synchronously');});
await p.waitForFunction(()=>document.querySelector('.daily-notice-status')?.textContent==='部分未完成');
await p.locator('.daily-notice [data-close]').last().click();await p.locator('.daily-notice').waitFor({state:'detached'});
assert.deepEqual(errors,[]);console.log('PASS completed-only notice, combined duration, once per batch, manual reopen, retry, 3 widths');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});