const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST'||['dailyStatus','dailyRetry'].includes(e.data.type))return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='buyerVerify'?{checks:payload.rows.map(p=>({id:p.id,...(['yungching:7417941','591:20734577'].includes(p.id)?{usage:'住家用',usageEvidence:'法定用途',availability:'available'}:{})}))}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');






await p.evaluate(async()=>{
 DB=Array.from({length:4},(_,i)=>({id:'owner'+i,name:'屋主'+i,type:'庫存屋主',types:['庫存屋主'],sProperties:[{community:'測試社區'+i,addr:'新北市土城區青和街'}]}));
 for(const [i,c] of DB.entries()){const e=InventoryMarket.entries([c])[0];c.inventoryWatch={[e.slot]:{...e.config,id:'watch'+i,enabled:true}};c.searchReportEvents=[{id:'inventory-watch:watch'+i+':2026-10-09',date:'2026-10-09',marketEvents:{['off'+i]:'已下架'}}];await InventoryMarket.updateState('watch'+i,()=>({records:{},events:[],baselines:{}}));}DB[3].searchReportEvents=[];persist();
 BuyerMatching.refreshBulkResults=async()=>{};InventoryMarket.tick=async()=>{};InventoryMarket.cleanLegacyReports=async()=>{};
 addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST'||e.data.type!=='dailyStatus')return;postMessage({channel:'CRM_BUYER_RESPONSE',id:e.data.id,result:{day:'2026-10-09',report:{status:'completed',startedAt:'2026-10-09T00:25:00Z',finishedAt:'2026-10-09T00:37:00Z',buyers:{total:0},inventory:{total:4,completed:4}}}},location.origin);});
});
await p.evaluate(()=>DailySearchNotice.open());await p.locator('[data-change-kind="inventory"]').first().click();assert.equal(await p.locator('#imOwnerPosition').innerText(),'1 / 3');await p.locator('#imRead').click();await p.waitForFunction(()=>document.querySelector('[data-review-key]')?.getAttribute('aria-pressed')==='false'&&document.querySelectorAll('.daily-change-reviewed').length===1);assert.match(await p.locator('[data-change-tab="1"]').innerText(),/2／3/);
assert.equal(await p.locator('.im-dialog[open]').count(),0);await p.locator('[data-change-client="owner1"]').click();assert.equal(await p.locator('#imOwnerPosition').innerText(),'1 / 3');await p.locator('#imOwnerNext').click();assert.equal(await p.locator('#imOwnerPosition').innerText(),'2 / 3');await p.locator('#imOwnerNext').click();assert.equal(await p.locator('#imOwnerPosition').innerText(),'3 / 3');assert(await p.locator('#imOwnerNext').isDisabled());await p.locator('#imOwnerPrev').click();await p.locator('#imRead').click();await p.waitForFunction(()=>document.querySelectorAll('.daily-change-reviewed').length===2);assert.equal(await p.locator('.im-dialog[open]').count(),0);await p.locator('.daily-notice [data-close]').first().click();
await p.evaluate(()=>InventoryMarket.open(InventoryMarket.entries()[0].key));assert.equal(await p.locator('#imOwnerPosition').innerText(),'1 / 4');await p.locator('#imClose').click();
await p.evaluate(()=>{const c=DB[0];const snapshot=DailySearchNotice.captureReviewed(c,'watch0','listings');c.searchReportEvents[0].marketEvents.trade='成交';DailySearchNotice.commitReviewed(snapshot);});await p.evaluate(()=>DailySearchNotice.open());assert.equal(await p.locator('[data-change-client="owner0"]').locator('..').locator('[data-review-key]').getAttribute('aria-pressed'),'false');
await p.evaluate(()=>DailySearchNotice.commitReviewed(DailySearchNotice.captureReviewed(DB[0],'watch0','transactions')));assert.equal(await p.locator('[data-change-client="owner0"]').locator('..').locator('[data-review-key]').getAttribute('aria-pressed'),'true');
await p.locator('[data-change-client="owner0"]').locator('..').locator('[data-review-key]').click();assert.equal(await p.locator('[data-change-client="owner0"]').locator('..').locator('[data-review-key]').getAttribute('aria-pressed'),'false');
await p.evaluate(()=>{DailySearchNotice.commitReviewed(DailySearchNotice.captureReviewed(DB[0],'watch0','listings'));DailySearchNotice.commitReviewed(DailySearchNotice.captureReviewed(DB[0],'watch0','transactions'));persist();});await p.locator('.daily-notice [data-close]').first().click();await p.evaluate(()=>{DB.push({id:'buyer',name:'測試買方',type:'經營買方',types:['經營買方'],buyerMatching:{auto:true},bDemands:[{areaCities:['新北市'],areaDists:['板橋區']}],searchReportEvents:[{id:'buyer-match:buyer:2026-10-09',date:'2026-10-09',matchEvents:{newAd:'New'}}]});persist();});await p.evaluate(()=>DailySearchNotice.open());await p.locator('[data-change-tab="0"]').click();await p.locator('[data-change-client="buyer"]').click();await p.locator('#bmAcknowledge').click();await p.waitForFunction(()=>!document.querySelector('.bm-dialog[open]'));assert.equal(await p.locator('[data-change-client="buyer"]').locator('..').locator('[data-review-key]').getAttribute('aria-pressed'),'true');await p.reload();assert(await p.evaluate(()=>!!JSON.parse(localStorage.getItem('crmDailySearchReviewed'))[JSON.stringify(['owner0','inventory-watch:watch0:2026-10-09'])]));assert.deepEqual(errors,[]);console.log('PASS report read sync, scoped 3-case navigation, normal 4-case navigation, separate transaction read, new changes unread, undo and reload');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
