const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST'||['dailyStatus','dailyRetry'].includes(e.data.type))return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='buyerVerify'?{checks:payload.rows.map(p=>({id:p.id,...(['yungching:7417941','591:20734577'].includes(p.id)?{usage:'住家用',usageEvidence:'法定用途',availability:'available'}:{})}))}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');






await p.evaluate(()=>{DB=[{id:'c1',name:'吳尚彥',type:'庫存屋主',types:['庫存屋主'],sProperties:[{inventoryKey:'p1',addr:'台北市中正區重慶南路三段4巷9號3樓'}],inventoryWatch:{p1:{id:'watch1',enabled:true,mode:'road',address:'台北市中正區重慶南路三段4巷9號3樓'}},searchReportEvents:[{id:'inventory-watch:watch1:2026-10-07',date:'2026-10-07',propertyRef:{label:'中正區重慶南路三段3樓'},marketEvents:Object.fromEntries(Array.from({length:5},(_,i)=>[i,'其中一筆已下架']))}]},...['張高銘','鄭勝元','劉傳懷','黃政傑'].map((name,i)=>({id:'more'+i,name,searchReportEvents:[{id:'inventory-watch:w'+i+':2026-10-07',date:'2026-10-07',propertyRef:{label:['帝王別墅','富裔山','大華縱橫','紅布朗花園'][i]},marketEvents:{a:'New',b:'Down',c:'其中一筆已下架'}}]}))];BuyerMatching.refreshBulkResults=async()=>{};InventoryMarket.tick=async()=>{};addEventListener('message',e=>{if(e.data?.channel==='CRM_BUYER_REQUEST'&&e.data.type==='dailyStatus')postMessage({channel:'CRM_BUYER_RESPONSE',id:e.data.id,result:{current:true,day:'2026-10-07',report:{status:'completed',startedAt:'2026-10-07T00:25:00Z',finishedAt:'2026-10-07T00:39:57Z',buyers:{total:4,completed:4},inventory:{total:17,completed:17},members:[]}}},location.origin);});});
await p.evaluate(()=>DailySearchNotice.open());await p.waitForSelector('.daily-change-row');
for(const width of [1440,1024,780,430]){await p.setViewportSize({width,height:1000});assert(await p.locator('.daily-notice').evaluate(e=>e.scrollWidth<=e.clientWidth));if(width>=1024){const a=await p.locator('.daily-change-name').first().boundingBox(),b=await p.locator('.daily-change-badges').first().boundingBox();assert(Math.abs(a.y-b.y)<8);}await p.screenshot({path:path.join(process.env.TEMP,'daily-tabs-'+width+'.png')});}
await p.setViewportSize({width:1440,height:1000});
assert.equal(await p.locator('.daily-change-name').first().innerText(),'張高銘');assert.deepEqual(await p.locator('.daily-change-row').first().locator('.daily-change-badge').allTextContents(),['新刊登 1 筆','降價 1 筆','部分新下架 1 筆']);
const before=await p.locator('.daily-notice').boundingBox();await p.locator('[data-change-tab="0"]').click();assert.deepEqual(await p.locator('.daily-notice').boundingBox(),before);await p.locator('[data-change-tab="1"]').click();
await p.evaluate(()=>{const list=document.querySelector('#dailyChangePanel1 ul');for(let i=0;i<25;i++){const clone=list.firstElementChild.cloneNode(true);clone.dataset.testClone='true';list.append(clone);}});
const header=await p.locator('.daily-notice>header').boundingBox(),tabs=await p.locator('.daily-change-tabs').boundingBox();await p.locator('#dailyChangePanel1').evaluate(e=>e.scrollTop=500);assert.deepEqual(await p.locator('.daily-notice>header').boundingBox(),header);assert.deepEqual(await p.locator('.daily-change-tabs').boundingBox(),tabs);await p.evaluate(()=>document.querySelectorAll('[data-test-clone]').forEach(e=>e.remove()));
await p.locator('[data-schedule-client="c1"]').click();assert(await p.locator('.daily-schedule-dialog').isVisible());assert.equal(await p.locator('.im-dialog').count(),0);await p.locator('.daily-schedule-dialog textarea').fill('回訪屋主並確認刊登變動');await p.locator('.daily-schedule-dialog [type=submit]').click();assert.equal(await p.evaluate(()=>DB[0].schedules.filter(x=>x.sourceReportKey).length),1);assert.equal(await p.evaluate(()=>_liveItems(DB[0].schedules)[0].memo),'回訪屋主並確認刊登變動');assert(await p.locator('[data-schedule-client="c1"]').isDisabled());assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('reCRM'))[0].schedules[0].memo),'回訪屋主並確認刊登變動');
await p.locator('[data-change-client="c1"]').click();assert(await p.locator('.im-dialog').isVisible());assert((await p.locator('#imProperty').innerText()).includes('重慶南路'));await p.locator('#imClose').click();assert(await p.locator('#dailyChangePanel1').isVisible());await p.locator('[data-change-tab="0"]').click();assert(await p.locator('#dailyChangePanel0').isVisible());await p.locator('[data-change-tab="1"]').click();
assert.equal(await p.locator('.daily-change-off').first().evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 240, 227)');
const review=p.locator('.daily-change-item').filter({has:p.locator('[data-change-client="c1"]')}).locator('[data-review-key]');await review.click();assert.equal(await review.getAttribute('aria-pressed'),'true');assert((await review.locator('..').locator('.daily-change-off').innerText()).includes('部分刊登下架'));assert.equal(await review.locator('..').locator('.daily-change-off').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(240, 242, 244)');assert.equal(await p.locator('.daily-change-item').last().locator('[data-change-client]').getAttribute('data-change-client'),'c1');assert((await p.locator('[data-change-tab="1"]').innerText()).includes('4／5 未看'));assert.equal(await p.locator('[data-results]').count(),0);
await p.locator('.daily-notice [data-close]').last().click();await p.locator('.daily-notice').waitFor({state:'detached'});await p.evaluate(()=>DailySearchNotice.open());await p.waitForSelector('.daily-change-item');assert.equal(await review.getAttribute('aria-pressed'),'true');
await review.click();assert.equal(await review.getAttribute('aria-pressed'),'false');await review.click();
await p.evaluate(()=>{DB[0].searchReportEvents[0].marketEvents.newEvent='New';});await p.locator('.daily-notice [data-close]').last().click();await p.locator('.daily-notice').waitFor({state:'detached'});await p.evaluate(()=>DailySearchNotice.open());await p.waitForSelector('.daily-change-item');assert.equal(await review.getAttribute('aria-pressed'),'false');
await p.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='crmDailySearchReviewed')throw Error('test storage failure');return originalSetItem.call(this,k,v);};});await review.click();assert.equal(await review.getAttribute('aria-pressed'),'false');assert((await p.locator('[data-message]').innerText()).includes('未能保存'));await p.evaluate(()=>Storage.prototype.setItem=originalSetItem);
await review.click();await p.evaluate(()=>persist());
await p.addInitScript(()=>{addEventListener('message',e=>{if(e.data?.channel==='CRM_BUYER_REQUEST'&&e.data.type==='dailyStatus')postMessage({channel:'CRM_BUYER_RESPONSE',id:e.data.id,result:{current:true,day:'2026-10-07',report:{status:'completed',startedAt:'2026-10-07T00:25:00Z',finishedAt:'2026-10-07T00:39:57Z',buyers:{total:4,completed:4},inventory:{total:17,completed:17}}}},location.origin);});});
await p.reload();await p.evaluate(()=>{BuyerMatching.refreshBulkResults=async()=>{};InventoryMarket.tick=async()=>{};return DailySearchNotice.open();});await p.waitForSelector('.daily-change-item');assert.equal(await review.getAttribute('aria-pressed'),'true');
assert.deepEqual(errors,[]);console.log('PASS compact rows, colors, 4 widths, direct property navigation and return tab');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});