const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST'||['dailyStatus','dailyRetry'].includes(e.data.type))return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='buyerVerify'?{checks:payload.rows.map(p=>({id:p.id,...(['yungching:7417941','591:20734577'].includes(p.id)?{usage:'住家用',usageEvidence:'法定用途',availability:'available'}:{})}))}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');







await p.evaluate(()=>{autoSync=async()=>{};const date=localDateISO();DB=Array.from({length:5},(_,i)=>({id:'client'+i,name:i===1?'很長的客戶姓名'.repeat(5):'測試客戶'+i,type:'經營買方',types:['經營買方'],schedules:[{id:'s'+i,date,memo:i===1?'這是長備註，需保留完整內容與自動換行。'.repeat(8):'回訪確認',propertyRef:{label:i===1?'很長的社區地址'.repeat(5):'板橋區國泰街',type:'經營買方',clientId:'client'+i}}],todos:[{id:'t'+i,memo:i===1?'長待辦備註'.repeat(30):'確認進度'}]}));persist();render();});
await p.waitForSelector('#dashSchedule [data-compact-actions]');
for(const width of [1920,1440,1024,430]){await p.setViewportSize({width,height:1000});for(const id of ['dashSchedule','dashTodo']){const row=p.locator('#'+id+' [data-compact-actions]').first();assert.equal(await row.locator('.dash-compact-actions button').count(),2);await row.locator('[title="更多"]').click();assert(await p.locator('.dash-action-menu').isVisible());assert.equal(await p.locator('.dash-menu-action').count(),3);const rect=await p.locator('.dash-action-menu').boundingBox();assert(rect.x>=0&&rect.y>=0&&rect.x+rect.width<=width);await p.keyboard.press('Escape');assert.equal(await p.locator('.dash-action-menu').count(),0);}await p.screenshot({path:path.join(process.env.TEMP,'dashboard-actions-'+width+'.png')});}
await p.setViewportSize({width:1440,height:1000});await p.evaluate(()=>{window.actionCalls=[];editDashSchedule=(...args)=>actionCalls.push(['edit',...args.slice(0,4)]);scheduleToTodo=(...args)=>actionCalls.push(['convert',...args]);deleteSchedule=(...args)=>actionCalls.push(['delete',...args]);});
for(const [label,kind] of [['編輯','edit'],['轉待辦','convert'],['刪除','delete']]){await p.locator('#dashSchedule [data-compact-actions]').first().locator('[title="更多"]').click();await p.locator('.dash-menu-action[title="'+label+'"]').click();assert.equal(await p.evaluate(()=>actionCalls.at(-1)[0]),kind);assert.equal(await p.evaluate(()=>actionCalls.at(-1)[1]),'client0');}
assert.deepEqual(errors,[]);console.log('PASS compact actions, menu bounds, keyboard, correct item actions, long text and four widths');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
