const assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{for(const width of [1440,1100,390]){
const page=await browser.newPage({viewport:{width,height:900}});await page.route('https://**/*',r=>r.abort());await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);await page.evaluate(()=>{DB=[{id:'column-test',type:'房東',types:['房東'],name:'測試客戶',phone:'0900000000',llOccupation:'測試職業',llEmail:'test@example.invalid',llAddr:'測試基本地址',rProperties:[{rCommunity:'測試社區',rAddr:'測試物件地址',rent:'20000'}],schedules:[{date:'2026-10-01',time:'15:00',memo:'行程測試'}],notes:Array(60).fill('唯讀備註').join('\n'),contactLog:Array.from({length:20},(_,i)=>({date:'2026-09-01',memo:'聯繫紀錄 '+i+'\n'+Array(5).fill('長內容').join('\n')}))}];curFilter='房東';showDet('column-test');});
const panes=page.locator('.det-pane'),left=panes.nth(0),middle=panes.nth(1),right=panes.nth(2);assert.match(await left.innerText(),/測試基本地址/);assert.match(await right.innerText(),/聯繫紀錄 0/);assert(!((await middle.innerText()).includes('聯繫紀錄 0')));
if(width>=1050){const box=await left.boundingBox(),m=await middle.boundingBox(),r=await right.boundingBox();assert(Math.abs(box.width/m.width-28/38)<.01&&Math.abs(r.width/m.width-34/38)<.01);assert(m.x>box.x&&r.x>m.x);assert.equal(await right.locator('.det-log-date').count(),0);assert.equal(await right.locator('#detLogList .det-row:visible').count(),10);await right.locator('#detLogToggle').click();assert.equal(await right.locator('#detLogList .det-row:visible').count(),20);await right.locator('#detLogToggle').click();assert.equal(await right.locator('#detLogList .det-row:visible').count(),10);await right.evaluate(e=>e.scrollTop=0);assert.equal(await left.locator('.det-copy-contact').textContent(),'複製');assert.match(await right.locator('.det-schedule-card .det-key').textContent(),/115\/10\/01 15:00/);assert.equal(await middle.locator('.det-schedule-card').count(),0);assert.equal(await right.locator(':scope>:first-child').getAttribute('class'),'det-schedule-card');const pinnedBefore=await middle.locator('.det-property-header').boundingBox();await middle.hover();await page.mouse.wheel(0,500);await page.waitForTimeout(150);assert(await middle.evaluate(e=>e.scrollTop>0));const pinnedAfter=await middle.locator('.det-property-header').boundingBox();assert(Math.abs(pinnedAfter.y-pinnedBefore.y)<1,'property heading and tabs stay fixed');assert.equal(await right.evaluate(e=>e.scrollTop),0);assert.equal(await left.evaluate(e=>e.scrollTop),0);assert.deepEqual(await left.boundingBox(),box);const saved=await middle.evaluate(e=>e.scrollTop);await right.hover();await page.mouse.wheel(0,450);await page.waitForTimeout(150);assert(await right.evaluate(e=>e.scrollTop>0));assert.equal(await middle.evaluate(e=>e.scrollTop),saved);assert.equal(await page.locator('#dModal>.modal').evaluate(e=>e.scrollTop),0);await page.screenshot({path:path.join(os.tmpdir(),'crm-detail-columns-'+width+'.png')});}
else {assert.equal(await page.locator('.det-columns').evaluate(e=>getComputedStyle(e).display),'contents');assert.equal(await left.evaluate(e=>getComputedStyle(e).display),'contents');assert((await page.locator('#dModal>.modal').boundingBox()).width<=width);}
assert.equal(await page.locator('#detContent input,#detContent textarea,#detContent [contenteditable=true]').count(),0);await page.close();console.log('PASS detail columns '+width+': placement, desktop independent scroll, mobile unchanged, read-only');
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
