const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url'),os=require('node:os');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{for(const width of [1440,390]){
const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);
await page.evaluate(()=>{DB=[{id:'landlord-test',type:'房東',types:['房東'],name:'測試房東',rProperties:[{rCommunity:'測試大樓',rAddr:'新北市板橋區民生路二段1號',rent:'20000',rSz:'20',rMeterGas:'瓦斯錶測試',rEquipment:{冷氣:'2台'}},{rAddr:'新北市新莊區民安西路75號',rSz:'21'}]},{id:'tenant-a',type:'租客',name:'第一位租客',linkedLandlordId:'landlord-test',linkedPropertyIdx:0},{id:'tenant-b',type:'租客',name:'第二位租客',linkedLandlordId:'landlord-test',linkedPropertyIdx:1}];window.beforeDetail=JSON.stringify(DB);curFilter='房東';showDet('landlord-test');});
const tabs=page.locator('#detContent .det-property-tabs [role=tab]');assert.deepEqual(await tabs.allTextContents(),['測試大樓','民安西路']);let active=page.locator('#detContent .det-property-page:not([hidden])');assert.match(await active.textContent(),/第一位租客/);assert(!((await active.textContent()).includes('第二位租客')));assert.equal(await active.locator('details').first().getAttribute('open'),null);await active.locator('summary').filter({hasText:'其他資料'}).click();assert.match(await active.innerText(),/瓦斯錶測試/);await tabs.nth(1).click();assert.match(await active.innerText(),/第二位租客/);assert(!((await active.innerText()).includes('第一位租客')));await page.keyboard.press('ArrowLeft');assert.equal(await tabs.first().getAttribute('aria-selected'),'true');assert.equal(await page.evaluate(()=>JSON.stringify(DB)===beforeDetail),true);assert.equal(await page.locator('#detContent input,#detContent textarea,#detContent select,#detContent [contenteditable=true]').count(),0);
await page.screenshot({path:path.join(os.tmpdir(),'crm-property-detail-'+width+'.png')});
for(const [type,key] of [['庫存屋主','sProperties'],['租案管理','rProperties'],['成交客戶','deals'],['商機募集','dAddrs']]){await page.evaluate(({type,key})=>{const a={community:'同名大樓',rCommunity:'同名大樓',addr:'第一地址',rAddr:'第一地址',price:'1000',rent:'20000',spPriceHistory:[{value:'1200',time:'2026-01-01T00:00:00Z'}]},b={...a,addr:'第二地址',rAddr:'第二地址'};DB=[{id:'multi',type,types:[type],name:'測試客戶',[key]:[a,b]}];curFilter=type;window.beforeDetail=JSON.stringify(DB);showDet('multi');},{type,key});assert.deepEqual(await tabs.allTextContents(),['同名大樓（1）','同名大樓（2）']);await tabs.nth(1).click();assert.match(await active.innerText(),/第二地址/);assert.equal(await page.evaluate(()=>JSON.stringify(DB)===beforeDetail),true);}
await page.evaluate(()=>{DB=[{id:'compact',type:'庫存屋主',types:['庫存屋主'],name:'測試',sProperties:[{community:'精簡測試',addr:'測試路',price:'1000',grade:'B',contractType:'一般約',parking:'坡道機械',parkingPrice:'200',parkingSz:'6.23',mainBldg:'20',common:'5',contractStart:'2026-01-01',contractEnd:'2026-12-31',mgmtBuilding:'1000',spRenewals:[{oldEnd:'2025-12-31',newEnd:'2026-12-31'}],spPriceHistory:[{value:'1200',time:'2026-01-01T00:00:00Z'}],areaInput:{main:{area:'66.12',unit:'sqm'}}}]}];curFilter='庫存屋主';showDet('compact');});assert.deepEqual(await active.locator('summary').allTextContents(),['面積與持分明細','合約與價格歷程','其他資料']);assert.equal(await active.locator('details[open]').count(),0);assert.match(await active.innerText(),/建物 25.00 坪/);assert.match(await active.innerText(),/車位 6.23 坪/);assert.match(await active.innerText(),/總計 31.23 坪/);assert.equal(await active.locator(':scope>div.det-field-pair').count(),3);const pair=active.locator('.det-field-pair').first(),cells=pair.locator('.det-row');const ab=await cells.nth(0).boundingBox(),bb=await cells.nth(1).boundingBox();if(width>=1050){assert(Math.abs(ab.y-bb.y)<1,'short fields share a row');}else{assert(bb.y>=ab.y+ab.height-1,'narrow screen wraps without shrinking');}assert.equal(await cells.first().locator('.det-val').evaluate(e=>getComputedStyle(e).fontSize),await active.locator(':scope>.det-row .det-val').first().evaluate(e=>getComputedStyle(e).fontSize));assert.match(await active.innerText(),/115\/12\/31/);assert(!((await active.innerText()).includes('66.12')));await active.locator('summary').filter({hasText:'面積與持分明細'}).click();assert.match(await active.innerText(),/66.12/);assert.equal(await active.locator('details[open]').count(),1);assert(!((await active.innerText()).includes('1200')));
await page.evaluate(()=>{const x={id:'x',type:'房東',name:'測試',rProperties:[{rCommunity:'<img src=x onerror=alert(1)>',rAddr:'a'},{rAddr:''}]};DB=[x];curFilter='房東';showDet('x');});assert.equal(await tabs.first().textContent(),'<img src=x onerror=alert(1)>');assert.equal(await tabs.nth(1).textContent(),'物件 2');assert.equal(await page.locator('.det-property-tabs img').count(),0);assert.deepEqual(errors,[]);await page.close();console.log('PASS property details '+width+': labels, tabs, tenant associations, read-only, compact details, all property types, escaping');
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
