const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');const{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{for(const width of [1440,390]){const p=await b.newPage({viewport:{width,height:960}});await p.route('https://**/*',r=>r.abort());await p.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);await p.evaluate(()=>{DB=[{id:'tabs-test',name:'測試客戶',phone:'0900000000',type:'庫存屋主',types:['庫存屋主','房東','成交客戶','商機募集'],sName:'測試客戶',sPhone:'0900000000',sProperties:[{community:'庫存一',price:'1200'},{community:'庫存二',price:'1300'}],rProperties:[{rCommunity:'租案一',rent:'20000'},{rCommunity:'租案二',rent:'25000'}],deals:[{community:'成交一',price:'900'},{community:'成交二',price:'1000'}],dAddrs:[{community:'商機一'},{community:'商機二'}]}];curFilter='庫存屋主';openEdit('tabs-test');});
for(const [type,id,adder] of [['庫存屋主','sPropertyList','addSellerProperty'],['房東','rPropertyList','addRentalProperty'],['成交客戶','dealList','addDealRow'],['商機募集','dAddrList','addDAddrRow']]){
 await p.evaluate(t=>pickType(t),type);const nav=p.locator('#'+id).locator('xpath=preceding-sibling::*[1]');assert.equal(await nav.getAttribute('role'),'tablist');assert.equal(await p.locator('#'+id+'>.edit-object-page:visible').count(),1);await nav.getByRole('tab').nth(1).click();assert.equal(await p.locator('#'+id+'>.edit-object-page').nth(1).evaluate(e=>e.hidden),false);
 const field=p.locator('#'+id+'>.edit-object-page').nth(1).locator('[data-f="community"],.deal-community');await field.fill(type+'修改');assert.match(await nav.getByRole('tab').nth(1).innerText(),/修改/);await nav.getByRole('tab').nth(0).click();await nav.getByRole('tab').nth(1).click();assert.equal(await field.inputValue(),type+'修改');
 await p.evaluate(name=>window[name](),adder);await p.waitForFunction(id=>document.getElementById(id).previousElementSibling.children.length===3,id);assert.equal(await p.locator('#'+id+'>.edit-object-page').last().evaluate(e=>e.hidden),false);await p.locator('#'+id+'>.edit-object-page').last().locator('.c-del').click();await p.waitForFunction(id=>document.getElementById(id).previousElementSibling.children.length===2,id);assert.equal(await p.locator('#'+id+'>.edit-object-page:visible').count(),1);
 if(type==='房東'){const alignment=await p.locator('#rPropertyList>.edit-object-page:not([hidden]) .rp-mgmt-row').evaluate(row=>{const a=row.querySelector('[data-f="mgmtType"]').getBoundingClientRect(),b=row.querySelector('[data-f="mgmtBuilding"]').getBoundingClientRect();return {top:Math.abs(a.top-b.top),height:Math.abs(a.height-b.height)};});assert(alignment.top<1&&alignment.height<1,'management selector and amount align');}
 const addButton=p.locator('#s-'+type+' .sec-title>.add-row-btn');assert(await addButton.count()>0);
}
if(width>=1200){assert.equal(await p.locator('.edit-basic>.edit-pane-heading .add-row-btn').count(),1);await p.locator('.edit-basic>.edit-pane-heading .add-row-btn').click();assert.equal(await p.locator('#sharedContactsList').locator(':scope>*').count(),1);await p.setViewportSize({width:1100,height:960});await p.waitForFunction(()=>!document.querySelector('.edit-pane'));assert.equal(await p.locator('#sharedContactsWrap .add-row-btn').count(),1);}
await p.evaluate(()=>{window.persist=()=>true;window.render=()=>{};saveClient();});assert.deepEqual(await p.evaluate(()=>[DB[0].sProperties[1].community,DB[0].rProperties[1].rCommunity,DB[0].deals[1].community,DB[0].dAddrs[1].community]),['庫存屋主修改','房東修改','成交客戶修改','商機募集修改']);console.log('PASS property edit tabs '+width+': switch, drafts, titles, add/delete, header actions, save');await p.close();}}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});