const assert=require('assert/strict'),fs=require('fs'),vm=require('vm');
const E=require('../buyer-match-engine.js'),I=require('../inventory-market-engine.js'),G=require('../buyer-grouping.js');
for(const [text,min,max] of [['B1-1F',-1,1],['22-23樓/23樓',22,23],['B2-B1',-2,-1],['3F/10F',3,3],['-1',-1,-1],['２２～２３樓',22,23]])assert.deepEqual(E.floorRange({floorText:text}),{min,max});
for(const text of ['全棟','頂加','高樓層','0','1,3',''])assert.equal(E.floorRange({floorText:text}),null);
const range={floorText:'B1-1F',floor:null};assert(E.evaluate({matchCriteria:{floorMin:1,floorMax:1}},range).no.includes('樓層'));assert(E.evaluate({matchCriteria:{floorMin:-1,floorMax:1}},range).yes.includes('樓層'));assert(E.evaluate({matchCriteria:{exclude:['basement','first']}},range).no.includes('非地下室'));assert(!I.assess({criteria:{floorMin:1,floorMax:1}},range).match);assert.deepEqual(I.assess({criteria:{floorMin:-1,floorMax:1}},range),{match:true,missing:[]});
assert(E.evaluate({matchCriteria:{exclude:['top']}},{floorText:'22-23',totalFloors:23}).no.includes('非頂樓'));
const base={address:'新北市新店區復興路',city:'新北市',district:'新店區',price:11500,area:215.87,age:10,floorText:'22-23'};assert(!G.same(base,{...base,floorText:'22'}));assert(G.same(base,{...base,floorText:'22–23樓'}));assert(!G.warnings([{p:base}]).includes('樓層待確認'));
const document={querySelector:s=>s==='#__NEXT_DATA__'?{textContent:JSON.stringify({props:{initialReduxState:{buyReducer:{list:[{houseNo:'70114P',name:'富裔河‧樓中樓',floor:'22-23',totalfloor:'23',address:'新北市新店區復興路',areaBuilding:215.87,totalPrice:11500,age:'10.1年'},{houseNo:'test',name:'店面',totalPrice:1680,areaBuilding:25.86,floor:'B1-1',address:'台北市中正區重慶南路三段'}]}}}})}:null};const context=vm.createContext({document});vm.runInContext(fs.readFileSync('01-crm/tools/buyer-browser/read.js','utf8'),context);const rows=context.crmReadListings('sinyi','新北市');assert.equal(rows[0].floorText,'22-23');assert.equal(E.floorLabel(rows[0]),'22–23樓');assert.equal(E.floorLabel(rows[1]),'B1–1樓');console.log('PASS basement/multi-floor parsing, reader retention, full-range criteria, exclusions, grouping and display');

