const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{for(const width of [1440,390]){
 const context=await browser.newContext({viewport:{width,height:1000}});await context.route('https://**/*',r=>r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);await page.evaluate(()=>openImgTool());
 await page.locator('#icBackground').setInputFiles({name:'sample.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><rect width="800" height="600" fill="#173756"/></svg>')});await page.waitForFunction(()=>!document.getElementById('icCanvas').hidden);await page.locator('#icTab_caption').click();
 await page.locator('#itCapText').fill('歡迎預約賞屋\n電話 0912-345-678');await page.locator('#icSaveMainText').click();assert.equal(await page.locator('#icSavedText option').count(),2);await page.locator('#icSaveMainText').click();assert.equal(await page.locator('#icSavedText option').count(),2,'deduplicates saved phrases');
 await page.locator('#itCapText').fill('物件特色');await page.locator('#icSavedTextAdd').click();const extra=page.locator('#icTextList textarea');assert.equal(await extra.inputValue(),'歡迎預約賞屋\n電話 0912-345-678');assert.equal(await page.locator('#itCapText').inputValue(),'物件特色');assert(await page.locator('#itUseCap').isChecked());
 await page.locator('#icTextList select[aria-label="快速定位"]').selectOption('.8,.85');const before=await page.locator('#icCanvas').evaluate(c=>c.toDataURL());await page.locator('#icTextList select[aria-label="快速定位"]').selectOption('.2,.15');assert.notEqual(await page.locator('#icCanvas').evaluate(c=>c.toDataURL()),before,'second paragraph moves independently');assert.equal(await page.locator('#itCapText').inputValue(),'物件特色');await page.locator('#icUndo').click();assert.equal(await page.locator('#icCanvas').evaluate(c=>c.toDataURL()),before,'position change is undoable');
 await page.locator('#icSavedTextApply').click();assert.equal(await page.locator('#itCapText').inputValue(),'歡迎預約賞屋\n電話 0912-345-678');assert.equal(await extra.count(),1);
 await extra.fill('<img src=x onerror=alert(1)>');await page.locator('#icTextList').getByRole('button',{name:'存為常用',exact:true}).click();assert.equal(await page.locator('#icSavedText option').count(),3);assert.equal(await page.locator('.ic-text-tools img').count(),0);
 page.once('dialog',d=>d.dismiss());await page.locator('#icSavedTextDelete').click();assert.equal(await page.locator('#icSavedText option').count(),3);page.once('dialog',d=>d.accept());await page.locator('#icSavedTextDelete').click();assert.equal(await page.locator('#icSavedText option').count(),2);assert.equal(await extra.inputValue(),'<img src=x onerror=alert(1)>','deleting a saved phrase does not delete artwork');
 const stored=await page.evaluate(()=>localStorage.getItem('_crmImageTexts_v1'));await page.evaluate(()=>{window.oldSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='_crmImageTexts_v1')throw Error('QuotaExceeded');return oldSet.call(this,k,v);};});await page.locator('#itCapText').fill('測試失敗');await page.locator('#icSaveMainText').click();assert.match(await page.locator('#icSavedTextStatus').textContent(),/無法儲存/);assert.equal(await page.evaluate(()=>localStorage.getItem('_crmImageTexts_v1')),stored);await page.evaluate(()=>Storage.prototype.setItem=window.oldSet);
 await page.reload();await page.evaluate(()=>openImgTool());await page.locator('#icTab_caption').click();assert.equal(await page.locator('#icSavedText option').count(),2,'saved phrases persist after reload');await page.locator('#icSavedText').selectOption({index:1});await page.locator('#icSavedTextApply').click();assert.equal(await page.locator('#itCapText').inputValue(),'歡迎預約賞屋\n電話 0912-345-678');assert.deepEqual(errors,[]);await context.close();console.log('PASS common text '+width+'px: save, duplicate, apply, independent position, undo, delete confirmation, storage failure, reload');
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
