const assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{for(const width of [1440,1024,768,390]){
 const context=await browser.newContext({viewport:{width,height:900}});await context.route('https://**/*',r=>r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);await page.evaluate(()=>openImgTool());
 await page.locator('#icBackground').setInputFiles(Array.from({length:20},(_,i)=>({name:`照片-${i+1}.svg`,mimeType:'image/svg+xml',buffer:Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${i%2?600:1200}" height="${i%2?1200:800}"><rect width="100%" height="100%" fill="${i%2?'#d4af62':'#173756'}"/><text x="100" y="200" fill="white" font-size="80">${i+1}</text></svg>`)})));await page.waitForFunction(()=>document.querySelectorAll('#icPhotos button[data-id]').length===20);
 const stage=page.locator('#icStage'),canvas=page.locator('#icCanvas'),rail=page.locator('#icPhotos');const before=await stage.boundingBox();
 if(width>650){const box=await rail.boundingBox();assert(box.x>=before.x+before.width-1,'rail is to right of large image');assert.equal(Math.round(box.y),Math.round(before.y));assert(await rail.evaluate(e=>e.scrollHeight>e.clientHeight));await rail.hover();await page.mouse.wheel(0,700);await page.waitForTimeout(150);assert(await rail.evaluate(e=>e.scrollTop>0),'wheel scrolls rail');assert.deepEqual(await stage.boundingBox(),before,'scrolling thumbnails leaves large image stationary');await rail.evaluate(e=>e.scrollTop=e.scrollHeight);await page.mouse.wheel(0,700);await page.waitForTimeout(150);assert.deepEqual(await stage.boundingBox(),before,'wheel at rail boundary does not scroll preview');assert.equal(await page.locator('.ic-preview').evaluate(e=>e.scrollTop),0);
 await rail.locator('button[data-id]').last().click();assert.match(await page.locator('#icPhotoName').textContent(),/20 \/ 20/);let image=await canvas.boundingBox();assert(image.height<=before.height+1&&image.width<=before.width+1,'portrait photo fits viewport');await page.locator('#icZoom').selectOption('2');assert(await stage.evaluate(e=>e.scrollHeight>e.clientHeight||e.scrollWidth>e.clientWidth),'zoom can scroll inside main image');await page.locator('#icZoom').selectOption('fit');assert.deepEqual(await stage.boundingBox(),before);await page.screenshot({path:path.join(os.tmpdir(),'crm-photo-rail-'+width+'.png')});
 }else{assert.equal(await rail.evaluate(e=>getComputedStyle(e).flexDirection),'row');assert((await rail.boundingBox()).y>=before.y+before.height-1);}
 assert.deepEqual(errors,[]);await context.close();console.log('PASS photo rail '+width+'px: layout, independent wheel scrolling, photo selection, portrait fit, zoom');
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
