const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 try{for(const width of [1440,390]){
  const context=await browser.newContext({viewport:{width,height:1000},acceptDownloads:true});await context.route('https://**/*',r=>r.abort());
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);await page.evaluate(()=>openImgTool());assert.equal(await page.locator('#icTab_crop').getAttribute('aria-selected'),'true');assert.deepEqual(await page.locator('.ic-tabs [role=tab]').allTextContents(),['裁切拼版','人物合成','品牌底條','文字','浮水印','局部遮蔽','輸出設定']);assert.equal(await page.locator('.ic-head #icTab_layouts').count(),1);await page.locator('#icTab_person').click();
  const fixture=(name,color,w=800,h=600)=>({name,mimeType:'image/svg+xml',buffer:Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><rect width="${w}" height="${h}" fill="${color}"/></svg>`)});
  const pixel=(id,x,y)=>page.locator('#'+id).evaluate((c,p)=>Array.from(c.getContext('2d').getImageData(Math.floor(c.width*p.x),Math.floor(c.height*p.y),1,1).data),{x,y});
  const signature=async()=>crypto.createHash('sha256').update(await page.locator('#icCanvas').evaluate(c=>c.toDataURL())).digest('hex');

  await page.locator('#icBackground').setInputFiles(fixture('room.svg','blue'));await page.waitForFunction(()=>!document.getElementById('icCanvas').hidden);await page.locator('#icTab_layouts').click();await page.locator('#icLayoutName').fill('有效版面');await page.locator('#icLayoutSave').click();
  const stored=await page.evaluate(()=>localStorage.getItem('_crmImageLayouts_v1'));const bad={type:'crm-image-layouts',version:1,layouts:[{name:'損壞版面',settings:{version:1,values:{itUseCap:true,itCapText:'不應被套用'},studio:{texts:[null]}}}]};await page.locator('#icLayoutImport').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await page.waitForFunction(()=>/匯入/.test(document.getElementById('icLayoutStatus').textContent));assert.match(await page.locator('#icLayoutStatus').textContent(),/匯入失敗/,'malformed nested settings must be rejected before storing');assert.equal(await page.evaluate(()=>localStorage.getItem('_crmImageLayouts_v1')),stored,'invalid import is atomic');
  await page.locator('#icTab_person').click();await page.locator('#icUsePerson').check();await page.locator('#icAuto').uncheck();await page.locator('#icPerson').setInputFiles(fixture('person.svg','red',200,300));await page.waitForFunction(()=>!document.getElementById('icRepair').disabled);await page.locator('#icRepair').click();await page.locator('#icBrushSize').fill('120');await page.locator('#icBrushSoft').fill('0');const repair=page.locator('#icRepairCanvas');await repair.scrollIntoViewIfNeeded();
  // Use real coordinates and capture for an interrupted mouse stroke.
  await page.keyboard.press('Escape');assert(await page.locator('#imageComposer').evaluate(e=>e.open),'Escape only closes repair');await page.locator('#icRepair').click();await page.locator('#icBrushSize').fill('120');await page.locator('#icBrushSoft').fill('0');await repair.scrollIntoViewIfNeeded();const box=await repair.boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();assert.equal((await pixel('icRepairCanvas',.5,.5))[3],0);await repair.dispatchEvent('pointercancel',{pointerId:1});await page.mouse.up();assert.equal((await pixel('icRepairCanvas',.5,.5))[3],255,'cancelled repair stroke restores pixels');// A second pointer cannot draw into the active stroke.
  await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await repair.dispatchEvent('pointerdown',{button:0,pointerId:7,clientX:box.x+box.width*.2,clientY:box.y+box.height*.2});await repair.dispatchEvent('pointermove',{pointerId:7,clientX:box.x+box.width*.2,clientY:box.y+box.height*.2});assert.equal((await pixel('icRepairCanvas',.2,.2))[3],255);await page.mouse.up();await page.locator('#icRepairUndo').click();assert(await page.locator('#icRepairRedo').isEnabled());await page.mouse.down();await repair.dispatchEvent('pointercancel',{pointerId:1});await page.mouse.up();assert(await page.locator('#icRepairRedo').isEnabled(),'cancel preserves prior redo');await page.locator('#icRepairRedo').click();assert.equal((await pixel('icRepairCanvas',.5,.5))[3],0);await page.locator('#icRepairCancel').click();
  await page.locator('.ic-asset-library summary').click();await page.locator('#icAssetName').fill('<img src=x onerror=alert(1)>');await page.evaluate(()=>{window._savedPut=ImageStorage.put;ImageStorage.put=async()=>{throw Error('測試儲存失敗');};});await page.locator('#icAssetSave').click();await page.waitForFunction(()=>document.getElementById('icAssetStatus').textContent.includes('測試儲存失敗'));assert(await page.locator('#icAssetSave').isEnabled());await page.evaluate(()=>ImageStorage.put=window._savedPut);await page.locator('#icAssetSave').click();await page.waitForFunction(()=>document.getElementById('icAssetStatus').textContent.startsWith('已保存'));assert.equal(await page.locator('#icAssets img[src="x"]').count(),0,'asset name rendered as text');assert((await page.locator('#icAssets').textContent()).includes('<img src=x onerror=alert(1)>'));
  await page.evaluate(()=>{window._savedBlob=ImageStorage.blob;ImageStorage.blob=async()=>{throw Error('測試下載失敗');};});await page.locator('#icDownload').click();assert.match(await page.locator('#icStatus').textContent(),/測試下載失敗/);assert(await page.locator('#icDownload').isEnabled(),'export failure releases controls');await page.evaluate(()=>ImageStorage.blob=window._savedBlob);const event=page.waitForEvent('download');await page.locator('#icDownload').click();assert((await fs.promises.stat(await(await event).path())).size>0,'export can be retried');
  await page.locator('#icUsePerson').uncheck();await page.locator('#icClear').click();await page.locator('#icBackground').setInputFiles(fixture('large.svg','blue',4000,3000));await page.waitForFunction(()=>document.querySelectorAll('#icPhotos button[data-id]').length===1&&!document.getElementById('icDownload').disabled);await page.locator('#icTab_output').click();await page.locator('#icFormat').selectOption('png');await page.locator('#itMax').fill('0');await page.locator('#itMax').dispatchEvent('input');const largeEvent=page.waitForEvent('download');await page.locator('#icDownload').click();const largeBytes=fs.readFileSync(await(await largeEvent).path());assert.equal(largeBytes.readUInt32BE(16),4000);assert.equal(largeBytes.readUInt32BE(20),3000);assert((await page.locator('#icCanvas').evaluate(c=>c.width))<4000,'preview scales down but export keeps full dimensions');
  await page.locator('#icFormat').selectOption('jpeg');await page.locator('#itMax').fill('1600');await page.locator('#itQ').fill('60');await page.evaluate(()=>{window._quality=null;const blob=ImageStorage.blob;ImageStorage.blob=(c,t,q)=>{window._quality=q;return blob(c,t,q);};});const qualityEvent=page.waitForEvent('download');await page.locator('#icDownload').click();const jpg=fs.readFileSync(await(await qualityEvent).path()).toString('base64');assert.equal(await page.evaluate(()=>window._quality),.6,'immediate download uses latest JPEG quality');const dimensions=await page.evaluate(async data=>{const img=new Image();img.src='data:image/jpeg;base64,'+data;await img.decode();return [img.width,img.height];},jpg);assert.deepEqual(dimensions,[1600,1200],'immediate download uses latest size');
  assert.deepEqual(errors,[]);await context.close();console.log('PASS resilience '+width+'px: malformed backup rejection, nested Escape, cancelled repair, export/storage failure and retry, safe names, 12MP export');
 }}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
