const assert=require('node:assert/strict'),path=require('node:path'),crypto=require('node:crypto'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 try{for(const width of [1440,390]){
  const context=await browser.newContext({viewport:{width,height:1000},hasTouch:width===390});await context.route('https://**/*',r=>r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);await page.evaluate(()=>openImgTool());
  const fixture=(name,color,w,h)=>({name,mimeType:'image/svg+xml',buffer:Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><rect width="${w}" height="${h}" fill="${color}"/></svg>`)});
  await page.locator('#icBackground').setInputFiles(fixture('room.svg','blue',800,600));await page.locator('#icUsePerson').check();await page.locator('#icAuto').uncheck();await page.locator('#icPerson').setInputFiles(fixture('person.svg','red',100,200));await page.waitForFunction(()=>!document.getElementById('icDownload').disabled);
  const signature=async()=>crypto.createHash('sha256').update(await page.locator('#icCanvas').evaluate(c=>c.toDataURL())).digest('hex');
  async function drag(x1,y1,x2,y2,during){await page.locator('#icCanvas').scrollIntoViewIfNeeded();const b=await page.locator('#icCanvas').boundingBox();if(width===390){const session=await context.newCDPSession(page),send=(type,x,y)=>session.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x:b.x+b.width*x,y:b.y+b.height*y}]});await send('touchStart',x1,y1);await send('touchMove',x2,y2);if(during)await during();await send('touchEnd');await session.detach();}else{await page.mouse.move(b.x+b.width*x1,b.y+b.height*y1);await page.mouse.down();await page.mouse.move(b.x+b.width*x2,b.y+b.height*y2);if(during)await during();await page.mouse.up();}}
  let withGuide;await drag(.22,.72,.495,.505,async()=>{withGuide=await signature();});assert.notEqual(await signature(),withGuide,'alignment guides disappear after release');
  await page.locator('#icTab_layouts').click();await page.locator('#icLayoutName').fill('對齊測試');await page.locator('#icLayoutSave').click();let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('_crmImageLayouts_v1'))[0].settings);assert.equal(saved.person.x,.5);assert.equal(saved.person.y,.5,'person snaps to image center');
  await page.locator('#icTab_person').click();await page.locator('#icLockPerson').check();assert(await page.locator('#icSize').isDisabled());const locked=await signature();await drag(.5,.5,.7,.7);assert.equal(await signature(),locked,'locked person cannot be dragged');await page.locator('#icCanvas').focus();await page.keyboard.press('ArrowRight');assert.equal(await signature(),locked,'locked person cannot be moved by keyboard');
  await page.locator('#icLockPerson').uncheck();await page.locator('#icGuides').uncheck();await drag(.5,.5,.495,.505);await page.locator('#icTab_layouts').click();await page.locator('#icLayoutUpdate').click();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('_crmImageLayouts_v1'))[0].settings);assert(Math.abs(saved.person.x-.495)<.003&&saved.person.x!==.5,'snapping can be turned off');
  await page.locator('#icTab_caption').click();await page.locator('#itUseCap').check();await page.locator('#itCapText').fill('鎖定文字');await page.locator('#itCapPos').selectOption('free');await page.locator('#icLockMain').check();assert(await page.locator('#itCapSz').isDisabled());const text=await signature();await drag(.5,.2,.7,.2);assert.equal(await signature(),text);
  await page.locator('#icTextAdd').click();await page.locator('#icTextList input[type=checkbox]').check();const extra=await signature();await drag(.5,.25,.7,.3);assert.equal(await signature(),extra,'additional text lock prevents dragging');
  await page.locator('#icTab_layouts').click();await page.locator('#icLayoutUpdate').click();await page.reload();await page.evaluate(()=>openImgTool());await page.locator('#icTab_layouts').click();await page.locator('#icLayoutSelect').selectOption({index:1});await page.locator('#icLayoutApply').click();await page.locator('#icTab_caption').click();assert(await page.locator('#icLockMain').isChecked());assert(await page.locator('#icTextList input[type=checkbox]').isChecked(),'locks survive saved layout reload');assert.deepEqual(errors,[]);await context.close();console.log('PASS alignment '+width+'px: snapping, guide removal, disabled snapping, position locks, persistence');
 }}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
