const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 try{for(const width of [1440,768,390,320]){
  const context=await browser.newContext({viewport:{width,height:width<=390?740:1000},hasTouch:width<=390,acceptDownloads:true});await context.route('https://**/*',r=>r.abort());
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);await page.evaluate(()=>openImgTool());await page.locator('#icTab_person').click();
  const svg='<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><defs><pattern id="p" width="20" height="20" patternUnits="userSpaceOnUse"><rect width="20" height="20" fill="white"/><rect width="10" height="20" fill="red"/></pattern></defs><rect width="800" height="600" fill="url(#p)"/></svg>';
  await page.locator('#icBackground').setInputFiles(['first.svg','second.svg'].map(name=>({name,mimeType:'image/svg+xml',buffer:Buffer.from(svg)})));await page.waitForFunction(()=>document.querySelectorAll('#icPhotos button[data-id]').length===2);
  const signature=async()=>{await page.locator('#icRedactRegions').evaluate(el=>{el.value='';el.dispatchEvent(new Event('change'));});return crypto.createHash('sha256').update(await page.locator('#icCanvas').evaluate(c=>c.toDataURL())).digest('hex');};
  const pixel=(x,y)=>page.locator('#icCanvas').evaluate((c,p)=>Array.from(c.getContext('2d').getImageData(Math.floor(c.width*p.x),Math.floor(c.height*p.y),1,1).data),{x,y});
  async function drag(x1,y1,x2,y2,cancel=false,during){await page.locator('#icCanvas').scrollIntoViewIfNeeded();const b=await page.locator('#icCanvas').boundingBox();if(width<=390){const session=await context.newCDPSession(page);const touch=(type,x,y)=>session.send('Input.dispatchTouchEvent',{type,touchPoints:['touchEnd','touchCancel'].includes(type)?[]:[{x:b.x+b.width*x,y:b.y+b.height*y}]});await touch('touchStart',x1,y1);await touch('touchMove',x2,y2);if(during)await during();await touch(cancel?'touchCancel':'touchEnd');await session.detach();}else{await page.mouse.move(b.x+b.width*x1,b.y+b.height*y1);await page.mouse.down();await page.mouse.move(b.x+b.width*x2,b.y+b.height*y2);if(during)await during();if(cancel)await page.locator('#icCanvas').dispatchEvent('pointercancel',{pointerId:1});await page.mouse.up();}}


  await page.locator('#icTab_redact').click();assert.equal(await page.locator('#icUseRedact').isChecked(),false);assert(await page.locator('#icRedactMode').isVisible(),'settings visible without enabling');const original=await pixel(.25,.25);
  await page.locator('#icRedactMode').selectOption('solid');await page.locator('#icRedactColor').fill('#123456');await drag(.1,.1,.5,.5);assert(await page.locator('#icUseRedact').isChecked(),'first region auto enables');assert.deepEqual(await pixel(.25,.25),[18,52,86,255]);const ids=await page.locator('#icRedactRegions option').evaluateAll(a=>a.map(x=>x.value));
  await page.locator('#icUseRedact').uncheck();assert.deepEqual(await pixel(.25,.25),original,'disabling restores original pixels');assert.deepEqual(await page.locator('#icRedactRegions option').evaluateAll(a=>a.map(x=>x.value)),ids,'disabling retains regions');await page.locator('#icUndo').click();assert(await page.locator('#icUseRedact').isChecked());await page.locator('#icRedo').click();assert.equal(await page.locator('#icUseRedact').isChecked(),false);
  await page.locator('#icTab_crop').click();await page.locator('#icRatio').selectOption('1');await page.locator('#icTab_redact').click();assert(await page.locator('#icRedactWarning').isHidden(),'disabled masks do not block export');await page.locator('#icUseRedact').check();assert(await page.locator('#icRedactWarning').isVisible(),'reenabling keeps crop review requirement');await page.locator('#icUseRedact').uncheck();
  await page.locator('#icTab_crop').click();await page.locator('#icCropReset').click();assert.equal(await page.locator('#icRatio').inputValue(),'original');assert.equal(await page.locator('#icFrameMode').inputValue(),'single');await page.locator('#icUndo').click();assert.equal(await page.locator('#icRatio').inputValue(),'1');await page.locator('#icRedo').click();assert.equal(await page.locator('#icRatio').inputValue(),'original');
  await page.locator('#icTab_output').click();await page.locator('#icFormat').selectOption('png');const event=page.waitForEvent('download');await page.locator('#icDownload').click();const data=fs.readFileSync(await(await event).path()).toString('base64');assert.deepEqual(await page.evaluate(async data=>{const i=new Image();i.src='data:image/png;base64,'+data;await i.decode();const c=document.createElement('canvas');c.width=i.width;c.height=i.height;const x=c.getContext('2d');x.drawImage(i,0,0);return [...x.getImageData(c.width*.25,c.height*.25,1,1).data];},data),original,'disabled redaction absent from exported PNG');
  await page.locator('#icPhotos button[data-id]').nth(1).click();await page.locator('#icTab_redact').click();assert.equal(await page.locator('#icUseRedact').isChecked(),false);await page.locator('#icUseRedact').check();await page.locator('#icPhotos button[data-id]').first().click();assert.equal(await page.locator('#icUseRedact').isChecked(),false,'enabled state belongs to each photo');await page.locator('#icUseRedact').check();assert.deepEqual(await pixel(.25,.25),[18,52,86,255],'reenabling restores saved region');
  await page.locator('#icUseRedact').uncheck();await page.locator('#icRedactNew').click();await drag(.6,.6,.8,.8,true);assert.equal(await page.locator('#icUseRedact').isChecked(),false,'cancelled new region does not enable masks');assert.deepEqual(await page.locator('#icRedactRegions option').evaluateAll(a=>a.map(x=>x.value)),ids,'cancelled new region preserves saved regions');
  await page.locator('#icApplyAll').click();await page.locator('#icPhotos button[data-id]').nth(1).click();assert(await page.locator('#icUseRedact').isChecked(),'apply all does not copy first photo disabled state');await page.locator('#icPhotos button[data-id]').first().click();assert.equal(await page.locator('#icUseRedact').isChecked(),false);
  page.once('dialog',d=>d.dismiss());await page.locator('#icRedactClear').click();assert.equal(await page.locator('#icRedactRegions option').count(),2,'cancel clear preserves region');page.once('dialog',d=>d.accept());await page.locator('#icRedactClear').click();assert.equal(await page.locator('#icRedactRegions option').count(),1);await page.locator('#icUndo').click();assert.equal(await page.locator('#icRedactRegions option').count(),2);assert.equal(await page.locator('#icUseRedact').isChecked(),false,'undo clear preserves disabled state');await page.locator('#icRedo').click();assert.equal(await page.locator('#icRedactRegions option').count(),1);
  assert.deepEqual(errors,[]);await context.close();console.log('PASS toggles '+width+'px: defaults, auto enable, retained regions, per-photo switches, undo/redo, crop review, crop reset, PNG export');
 }}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
