const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const file=(name,color)=>({name:name+'.svg',mimeType:'image/svg+xml',buffer:Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><rect width="800" height="600" fill="${color}"/></svg>`)});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{for(const width of [1440,390]){
const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);await page.evaluate(()=>openImgTool());
await page.locator('#icBackground').setInputFiles([file('red','#ff0000'),file('green','#00ff00')]);await page.waitForFunction(()=>document.querySelectorAll('#icPhotos img').length===2);await page.locator('#icTab_crop').click();await page.locator('#icFrameMode').selectOption('lr');await page.locator('#icSecondFile').setInputFiles(file('blue','#0000ff'));
const pixels=()=>page.locator('#icPhotos img').evaluateAll(async imgs=>Promise.all(imgs.map(async img=>{await img.decode();const c=document.createElement('canvas');c.width=100;c.height=100;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,100,100);return [[25,25],[75,75]].map(([x,y])=>Array.from(ctx.getImageData(x,y,1,1).data).slice(0,3));})));
await page.waitForTimeout(400);assert.deepEqual(await pixels(),[[[255,0,0],[0,0,255]],[[0,255,0],[0,255,0]]],'only edited thumbnail displays both photos');
await page.locator('#icPhotos button').nth(1).click();await page.waitForTimeout(250);assert.deepEqual((await pixels())[0],[[255,0,0],[0,0,255]],'composition persists when switching photos');await page.locator('#icPhotos button').first().click();await page.locator('#icCropReset').click();await page.waitForTimeout(250);assert.deepEqual((await pixels())[0],[[255,0,0],[255,0,0]],'reset updates thumbnail');await page.locator('#icUndo').click();await page.waitForTimeout(250);assert.deepEqual((await pixels())[0],[[255,0,0],[0,0,255]],'undo restores thumbnail');
await page.locator('#icApplyAll').click();await page.waitForTimeout(250);assert.deepEqual((await pixels())[1],[[0,255,0],[0,0,255]],'apply all uses each photo with shared second image');assert.deepEqual(errors,[]);await page.close();console.log('PASS composed thumbnails '+width);
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
