const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 try{for(const width of [1440,390]){
  const context=await browser.newContext({viewport:{width,height:1000},acceptDownloads:true});await context.route('https://**/*',r=>r.abort());
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);await page.evaluate(()=>openImgTool());
  const fixture=(name,color,w=800,h=600)=>({name,mimeType:'image/svg+xml',buffer:Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><rect width="${w}" height="${h}" fill="${color}"/></svg>`)});
  const pixel=(id,x,y)=>page.locator('#'+id).evaluate((c,p)=>Array.from(c.getContext('2d').getImageData(Math.floor(c.width*p.x),Math.floor(c.height*p.y),1,1).data),{x,y});
  const signature=async()=>crypto.createHash('sha256').update(await page.locator('#icCanvas').evaluate(c=>c.toDataURL())).digest('hex');
  await page.locator('#icBackground').setInputFiles([fixture('first.svg','blue'),fixture('second.svg','yellow')]);await page.waitForFunction(()=>document.querySelectorAll('#icPhotos button').length===2);
  await page.locator('#icEditScope').selectOption('current');await page.locator('#icTab_brand').click();await page.locator('#icUseBrand').check();await page.locator('#icBrand_name').fill('第一張');await page.waitForTimeout(300);
  await page.locator('#icBrand_name').fill('修改姓名');await page.waitForTimeout(300);await page.locator('#icUndo').click();assert.equal(await page.locator('#icBrand_name').inputValue(),'第一張','undo restores text');await page.locator('#icRedo').click();assert.equal(await page.locator('#icBrand_name').inputValue(),'修改姓名');
  await page.locator('#icPhotos button').nth(1).click();assert(!await page.locator('#icUseBrand').isChecked(),'editing only this photo preserves other photo');await page.locator('#icPhotos button').first().click();assert.equal(await page.locator('#icBrand_name').inputValue(),'修改姓名');
  await page.locator('#icTab_layouts').click();await page.locator('#icLayoutName').fill('只套用測試');await page.locator('#icLayoutSave').click();assert(await page.locator('#icLayoutPreview').isVisible());
  const backupEvent=page.waitForEvent('download');await page.locator('#icLayoutExport').click();const backup=fs.readFileSync(await (await backupEvent).path());assert.equal(JSON.parse(backup).layouts.length,1);
  await page.locator('#icLayoutImport').setInputFiles({name:'layouts.json',mimeType:'application/json',buffer:backup});await page.waitForFunction(()=>document.getElementById('icLayoutStatus').textContent.includes('已匯入 1'));assert.equal(await page.locator('#icLayoutSelect option').count(),3,'import merges without overwrite');
  await page.locator('#icPhotos button').nth(1).click();await page.locator('#icLayoutScope').selectOption('current');await page.locator('#icLayoutApply').click();await page.locator('#icTab_brand').click();assert(await page.locator('#icUseBrand').isChecked());
  await page.locator('#icBrand_name').fill('第二張');await page.waitForTimeout(300);await page.locator('#icUndo').click();assert.equal(await page.locator('#icBrand_name').inputValue(),'修改姓名','undo stays consistent on second photo');await page.locator('#icRedo').click();assert.equal(await page.locator('#icBrand_name').inputValue(),'第二張');await page.locator('#icPhotos button').first().click();assert.equal(await page.locator('#icBrand_name').inputValue(),'修改姓名','apply current does not replace first');
  await page.locator('#icUseBrand').uncheck();await page.locator('#icTab_caption').click();await page.locator('#itUseCap').check();await page.locator('#itCapText').fill('可移動標題');await page.locator('#itCapPos').selectOption('free');await page.locator('#icTextAdd').click();await page.locator('#icTextList textarea').fill('第二組文字');
  const textBefore=await signature();await page.locator('#icCanvas').scrollIntoViewIfNeeded();let box=await page.locator('#icCanvas').boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.25);await page.mouse.down();await page.mouse.move(box.x+box.width*.65,box.y+box.height*.4);await page.mouse.up();assert.notEqual(await signature(),textBefore,'additional text can be dragged');
  await page.locator('#itUseCap').uncheck();await page.locator('#icTab_crop').click();await page.locator('#icRatio').selectOption('1');await page.locator('#icFrameMode').selectOption('lr');await page.locator('#icSecondFile').setInputFiles(fixture('green.svg','lime'));await page.waitForFunction(()=>document.getElementById('icSecondName').textContent==='green.svg');
  assert.deepEqual(await pixel('icCanvas',.25,.5),[0,0,255,255]);assert.deepEqual(await pixel('icCanvas',.75,.5),[0,255,0,255]);assert.equal(await page.locator('#icCanvas').evaluate(c=>c.width/c.height),1);
  await page.locator('#icTab_output').click();await page.locator('#icFormat').selectOption('png');const pngEvent=page.waitForEvent('download');await page.locator('#icDownload').click();const png=await pngEvent;assert.match(png.suggestedFilename(),/\.png$/);assert.equal(fs.readFileSync(await png.path()).subarray(1,4).toString(),'PNG');
  const zipEvent=page.waitForEvent('download');await page.locator('#icZip').click();const zip=await zipEvent;const zipPath=path.join(os.tmpdir(),'crm-studio-'+width+'.zip');await zip.saveAs(zipPath);const bytes=fs.readFileSync(zipPath);assert.equal(bytes.readUInt32LE(0),0x04034b50);assert.equal(bytes.readUInt32LE(bytes.length-22),0x06054b50);assert.equal(bytes.readUInt16LE(bytes.length-12),2,'ZIP contains both photos');let offset=0;for(let i=0;i<2;i++){const len=bytes.readUInt32LE(offset+18),start=offset+30+bytes.readUInt16LE(offset+26)+bytes.readUInt16LE(offset+28);assert.equal(require('node:zlib').crc32(bytes.subarray(start,start+len)),bytes.readUInt32LE(offset+14),'ZIP CRC matches native implementation');offset=start+len;}
  await page.locator('#icTab_crop').click();await page.locator('#icFrameMode').selectOption('single');await page.locator('#icRatio').selectOption('original');
  await page.locator('#icTab_person').click();await page.locator('#icUsePerson').check();await page.locator('#icAuto').uncheck();await page.locator('#icPerson').setInputFiles(fixture('portrait.svg','red',200,300));await page.waitForFunction(()=>!document.getElementById('icDownload').disabled);
  await page.locator('#icSize').fill('90');await page.locator('#icTab_brand').click();await page.locator('#icUseBrand').check();await page.locator('#icTab_person').click();const behind=await signature();await page.locator('#icPersonFront').check();assert.notEqual(await signature(),behind,'person can be placed in front of banner');
  await page.locator('.ic-asset-library summary').click();await page.locator('#icAssetName').fill('常用人物');await page.locator('#icAssetSave').click();await page.waitForFunction(()=>document.querySelectorAll('#icAssets .ic-asset').length===1);assert.match(await page.locator('#icAssetStatus').innerText(),/已保存/);
  const beforeRepair=await signature();await page.locator('#icRepair').click();await page.locator('#icBrushSoft').fill('0');await page.locator('#icBrushSize').fill('120');await page.locator('#icRepairCanvas').scrollIntoViewIfNeeded();box=await page.locator('#icRepairCanvas').boundingBox();await page.mouse.click(box.x+box.width*.5,box.y+box.height*.5);assert.equal((await pixel('icRepairCanvas',.5,.5))[3],0,'erase removes alpha');
  await page.locator('#icRepairUndo').click();assert.equal((await pixel('icRepairCanvas',.5,.5))[3],255);await page.locator('#icRepairRedo').click();assert.equal((await pixel('icRepairCanvas',.5,.5))[3],0);
  await page.locator('#icBrushMode').selectOption('restore');await page.mouse.click(box.x+box.width*.5,box.y+box.height*.5);assert.equal((await pixel('icRepairCanvas',.5,.5))[3],255,'restore recovers original');await page.locator('#icBrushMode').selectOption('erase');await page.mouse.click(box.x+box.width*.5,box.y+box.height*.5);await page.locator('#icRepairApply').click();assert.notEqual(await signature(),beforeRepair);await page.waitForTimeout(300);await page.locator('#icUndo').click();assert.equal(await signature(),beforeRepair,'main undo restores cutout');
  await page.locator('#icAssets button').filter({hasText:'加為標誌'}).click();await page.waitForFunction(()=>!document.getElementById('icLogoControls').hidden);
  await page.locator('#icZoom').selectOption('1');assert(await page.locator('#icStage').evaluate(e=>e.scrollWidth>e.clientWidth));await page.locator('#icZoom').selectOption('fit');
  await page.screenshot({path:path.join(os.tmpdir(),'crm-studio-'+width+'.png')});assert(await page.locator('#imageComposer').evaluate(e=>e.scrollWidth<=e.clientWidth+1));
  if(width===390){assert(await page.locator('#icMiniToggle').isVisible());await page.locator('#icMiniToggle').click();assert(!await page.locator('#icMiniCanvas').isVisible());}
  await page.reload();await page.evaluate(()=>openImgTool());await page.locator('.ic-asset-library summary').click();await page.waitForFunction(()=>document.querySelectorAll('#icAssets .ic-asset').length===1);await page.locator('#icAssets button').filter({hasText:'用作人物'}).click();await page.waitForFunction(()=>!document.getElementById('icThumb').hidden);assert(await page.locator('#icUsePerson').isChecked(),'reusable cutout loads after refresh');
  assert.deepEqual(errors,[]);await context.close();console.log('PASS studio '+width+'px: history, photo scope, backups, text drag, collage, PNG/ZIP, asset persistence, repair and layer order');
 }}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
