// Interaction contract uses deterministic results; real-model acceptance is run separately.
const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{for(const width of [1440,390,320]){
 const p=await b.newPage({viewport:{width,height:950},acceptDownloads:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.abort());await p.goto(pathToFileURL(path.resolve('01-crm/index.html')).href);await p.evaluate(()=>openImgTool());await p.locator('#icTab_enhance').click();assert(await p.locator('#icAIRestore').isDisabled());
 await p.locator('#icBackground').setInputFiles({name:'很長的房屋照片名稱'.repeat(12)+'.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><rect width="800" height="600" fill="#456789"/></svg>')});await p.waitForFunction(()=>!document.getElementById('icAIRestore').disabled);
 await p.evaluate(()=>{window.aiTestMode='normal';window.aiCalls=[];ImageAI.run=(source,mode,rect,progress,size,variant)=>{aiCalls.push({mode,rect,size,variant});if(aiTestMode==='error')return Promise.reject(Error('模型測試失敗'));if(aiTestMode==='pending')return new Promise((resolve,reject)=>{ImageAI.cancel=()=>reject(Error('已取消 AI 處理'));});const c=document.createElement('canvas');c.width=source.naturalWidth||source.width;c.height=source.naturalHeight||source.height;c.getContext('2d').drawImage(source,0,0);c.getContext('2d').fillStyle='red';c.getContext('2d').fillRect(20,20,40,40);return Promise.resolve(c);};});
 await p.locator('#icAIRemove').click();assert(await p.locator('#icAIRun').isDisabled());const c=p.locator('#icAIBefore'),box=await c.boundingBox();assert(Math.abs(box.width/box.height-800/600)<.02,'selection canvas retains exact ratio');await p.mouse.move(box.x+box.width*.2,box.y+box.height*.2);await p.mouse.down();await p.mouse.move(box.x+box.width*.4,box.y+box.height*.4);await p.mouse.up();await p.locator('#icAIRun').click();assert(await p.locator('#icAIResult').isVisible());let call=await p.evaluate(()=>aiCalls.at(-1));assert.equal(call.variant,'fine');assert(Math.abs(call.rect.x-.2)<.01);assert.equal(call.mode,'remove');
 assert(await p.locator('#icAIDialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1));const download=p.waitForEvent('download');await p.locator('#icAIDownload').click();assert((await download).suggestedFilename().endsWith('_AI去雜物.png'));assert.equal(await p.evaluate(()=>_itFiles.length),1,'download does not adopt');
 await p.locator('#icAIAdopt').click();await p.waitForSelector('#icAIDialog',{state:'detached'});assert.equal(await p.evaluate(()=>_itFiles.length),2);assert((await p.locator('#icPhotoName').innerText()).includes('AI去雜物'));assert.equal(await p.locator('#itMax').inputValue(),'0');
 await p.locator('#icPhotos button[data-id]').first().click();await p.locator('#icAIRestore').click();await p.evaluate(()=>aiTestMode='error');await p.locator('#icAIRun').click();assert((await p.locator('#icAIStatus').innerText()).includes('處理未完成'));assert(await p.locator('#icAIAdopt').isDisabled());
 await p.evaluate(()=>aiTestMode='pending');await p.locator('#icAIRun').click();await p.locator('#icAICancel').click();await p.waitForFunction(()=>document.getElementById('icAIStatus').textContent.includes('已取消'));assert.equal(await p.evaluate(()=>_itFiles.length),2);assert(!await p.locator('#icAIRun').isDisabled());
 await p.locator('#icAIRun').click();await p.keyboard.press('Escape');await p.waitForSelector('#icAIDialog',{state:'detached'});assert(await p.locator('#imageComposer').evaluate(el=>el.open));assert(!await p.locator('#icAIRestore').isDisabled());assert.deepEqual(errors,[]);await p.close();console.log('PASS '+width+' AI dialog, coordinates, responsive layout, download/adopt separation, originals, failure, cancel and Escape');
}}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
