const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{for(const width of [1440,390]){
const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);await page.evaluate(()=>openImgTool());await page.locator('#icBackground').setInputFiles(['red','blue','green'].map(color=>({name:color+'.svg',mimeType:'image/svg+xml',buffer:Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><rect width="800" height="600" fill="${color}"/></svg>`)})));await page.waitForFunction(()=>document.querySelectorAll('#icPhotos button[data-id]').length===3);
const photos=page.locator('#icPhotos button[data-id]'),remove=page.locator('.ic-photo-remove');await page.locator('#icTab_crop').click();await page.locator('#icRatio').selectOption('1');const before=await page.locator('#icCanvas').evaluate(c=>c.toDataURL());
page.once('dialog',d=>d.dismiss());await remove.nth(1).click();assert.equal(await photos.count(),3);assert.equal(await page.locator('#icCanvas').evaluate(c=>c.toDataURL()),before);
page.once('dialog',d=>{assert.match(d.message(),/blue.svg/);d.accept();});await remove.nth(1).click();assert.equal(await photos.count(),2);assert.equal(await page.locator('#icCanvas').evaluate(c=>c.toDataURL()),before,'removing unselected photo preserves active edits');assert.match(await page.locator('#icPhotoName').textContent(),/red.svg · 1 \/ 2/);
page.once('dialog',d=>d.accept());await remove.first().click();assert.equal(await photos.count(),1);assert(await page.locator('#icPhotos').isVisible(),'last photo still has remove control');assert.match(await page.locator('#icPhotoName').textContent(),/green.svg/);assert.equal(await page.locator('#icRatio').inputValue(),'original','next photo keeps its settings');
page.once('dialog',d=>d.accept());await remove.first().focus();await page.keyboard.press('Enter');assert.equal(await photos.count(),0);assert(await page.locator('#icEmpty').isVisible());assert(await page.locator('#icDownload').isDisabled());assert.deepEqual(errors,[]);await page.close();console.log('PASS thumbnail removal '+width+': cancel, unselected, selected, final photo, keyboard');
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
