const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 try{for(const width of [1440,390]){
  const context=await browser.newContext({viewport:{width,height:1000},acceptDownloads:true});await context.route('https://**/*',r=>r.abort());
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);await page.evaluate(()=>openImgTool());assert.equal(await page.locator('#icTab_crop').getAttribute('aria-selected'),'true');assert.deepEqual(await page.locator('.ic-tabs [role=tab]').allTextContents(),['裁切拼版','人物合成','品牌底條','文字','浮水印','局部遮蔽','輸出設定']);assert.equal(await page.locator('.ic-head #icTab_layouts').count(),1);await page.locator('#icTab_person').click();
  const fixture=(name,color,w=800,h=600)=>({name,mimeType:'image/svg+xml',buffer:Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><rect width="${w}" height="${h}" fill="${color}"/></svg>`)});
  const pixel=(id,x,y)=>page.locator('#'+id).evaluate((c,p)=>Array.from(c.getContext('2d').getImageData(Math.floor(c.width*p.x),Math.floor(c.height*p.y),1,1).data),{x,y});
  const signature=async()=>crypto.createHash('sha256').update(await page.locator('#icCanvas').evaluate(c=>c.toDataURL())).digest('hex');

  await page.locator('#icBackground').setInputFiles([fixture('first.svg','blue'),fixture('unvisited.svg','yellow'),fixture('third.svg','lime'),...Array.from({length:17},(_,i)=>fixture('extra-'+i+'.svg','yellow'))]);await page.waitForFunction(()=>document.querySelectorAll('#icPhotos button[data-id]').length===20);
  await page.locator('#icTab_crop').click();await page.locator('#icRatio').selectOption('1');await page.locator('#icFrameMode').selectOption('lr');await page.locator('#icSecondFile').setInputFiles(fixture('insert.svg','red'));await page.waitForFunction(()=>document.getElementById('icSecondName').textContent==='insert.svg');await page.locator('#icTab_output').click();await page.locator('#icFormat').selectOption('png');
  await page.locator('#icClose').click();await page.evaluate(()=>openImgTool());const singleEvent=page.waitForEvent('download');await page.locator('#icDownload').click();const single=fs.readFileSync(await(await singleEvent).path()).toString('base64');
  const event=page.waitForEvent('download');await page.locator('#icZip').click();const bytes=fs.readFileSync(await(await event).path());const files=[];let offset=0;while(bytes.readUInt32LE(offset)===0x04034b50){const size=bytes.readUInt32LE(offset+18),nameLength=bytes.readUInt16LE(offset+26),start=offset+30+nameLength+bytes.readUInt16LE(offset+28);files.push({name:bytes.subarray(offset+30,offset+30+nameLength).toString(),data:bytes.subarray(start,start+size).toString('base64')});offset=start+size;}assert.equal(files.length,20);assert.equal(files[0].data,single,'single and ZIP output for edited photo agree');
  const info=await page.evaluate(async files=>Promise.all(files.map(async file=>{const i=new Image();i.src='data:image/'+(file.name.endsWith('.png')?'png':'jpeg')+';base64,'+file.data;await i.decode();const c=document.createElement('canvas');c.width=i.width;c.height=i.height;const x=c.getContext('2d');x.drawImage(i,0,0);return {name:file.name,w:i.width,h:i.height,pixel:[...x.getImageData(10,10,1,1).data]};})),files);
  assert.deepEqual(info.map(x=>[x.w,x.h]),[[800,800],...Array.from({length:19},()=>[800,600])],'unvisited photos must keep original crop');assert(info[0].name.endsWith('.png'));assert(info[1].name.endsWith('.jpg'),'unvisited photo keeps default output format');assert(info[1].pixel[0]>250&&info[1].pixel[1]>250&&info[1].pixel[2]<5);for(const entry of info.slice(1)){assert(entry.name.endsWith('.jpg'));assert(entry.pixel[1]>250&&entry.pixel[2]<5,'untouched photo retains original color, without collage artwork');}
  assert.deepEqual(errors,[]);await context.close();console.log('PASS batch content '+width+'px: decoded ZIP pixels, per-photo dimensions and formats including unvisited photos');
 }}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
