const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 try{for(const width of [1440,768,390,320]){
  const context=await browser.newContext({viewport:{width,height:width<=390?740:1000},hasTouch:width<=390,acceptDownloads:true});await context.route('https://**/*',r=>r.abort());
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);await page.evaluate(()=>openImgTool());
  const svg='<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><defs><pattern id="p" width="20" height="20" patternUnits="userSpaceOnUse"><rect width="20" height="20" fill="white"/><rect width="10" height="20" fill="red"/></pattern></defs><rect width="800" height="600" fill="url(#p)"/></svg>';
  await page.locator('#icBackground').setInputFiles(['first.svg','second.svg'].map(name=>({name,mimeType:'image/svg+xml',buffer:Buffer.from(svg)})));await page.waitForFunction(()=>document.querySelectorAll('#icPhotos button').length===2);
  const signature=async()=>{await page.locator('#icRedactRegions').evaluate(el=>{el.value='';el.dispatchEvent(new Event('change'));});return crypto.createHash('sha256').update(await page.locator('#icCanvas').evaluate(c=>c.toDataURL())).digest('hex');};
  const pixel=(x,y)=>page.locator('#icCanvas').evaluate((c,p)=>Array.from(c.getContext('2d').getImageData(Math.floor(c.width*p.x),Math.floor(c.height*p.y),1,1).data),{x,y});
  async function drag(x1,y1,x2,y2,cancel=false,during){await page.locator('#icCanvas').scrollIntoViewIfNeeded();const b=await page.locator('#icCanvas').boundingBox();if(width<=390){const session=await context.newCDPSession(page);const touch=(type,x,y)=>session.send('Input.dispatchTouchEvent',{type,touchPoints:['touchEnd','touchCancel'].includes(type)?[]:[{x:b.x+b.width*x,y:b.y+b.height*y}]});await touch('touchStart',x1,y1);await touch('touchMove',x2,y2);if(during)await during();await touch(cancel?'touchCancel':'touchEnd');await session.detach();}else{await page.mouse.move(b.x+b.width*x1,b.y+b.height*y1);await page.mouse.down();await page.mouse.move(b.x+b.width*x2,b.y+b.height*y2);if(during)await during();if(cancel)await page.locator('#icCanvas').dispatchEvent('pointercancel',{pointerId:1});await page.mouse.up();}}

  assert.equal(await page.locator('#icEditScope').inputValue(),'current');
  await page.locator('#icTab_redact').click();await page.locator('#icRedactMode').selectOption('solid');await drag(.2,.2,.5,.5);
  const selected=await page.locator('#icCanvas').evaluate(c=>c.toDataURL());
  await drag(.5,.5,.7,.65);assert(Number(await page.locator('#icRedact_w').inputValue())>45,'corner handle resizes horizontally');assert(Number(await page.locator('#icRedact_h').inputValue())>40,'corner handle resizes vertically');
  await page.locator('#icUndo').click();assert(Math.abs(Number(await page.locator('#icRedact_w').inputValue())-30)<1,'resize undo');await page.locator('#icRedo').click();
  await page.locator('#icTab_output').click();const clean=await page.locator('#icCanvas').evaluate(c=>c.toDataURL());await page.locator('#icTab_redact').click();assert.notEqual(await page.locator('#icCanvas').evaluate(c=>c.toDataURL()),clean,'selected outline reappears on tab activation');
  await page.locator('#icTab_crop').click();await page.locator('#icRatio').selectOption('1');await page.locator('#icDownload').click();assert(await page.locator('#icRedactWarning').isVisible(),'crop change blocks export and requests review');assert((await page.locator('#icStatus').textContent()).includes('核對'));
  await page.locator('#icRedactReviewed').click();assert(await page.locator('#icRedactWarning').isHidden());await page.locator('#icUndo').click();assert(await page.locator('#icRedactWarning').isVisible(),'undo review restores protection');await page.locator('#icRedo').click();assert(await page.locator('#icRedactWarning').isHidden());
  await page.locator('#icTab_caption').click();await page.locator('#itUseCap').check();await page.locator('#itCapText').fill('單張測試');await page.locator('#icPhotos button').nth(1).click();assert.equal(await page.locator('#itUseCap').isChecked(),false,'single-photo edit does not change second photo');
  await page.locator('#icPhotos button').first().click();await page.locator('#icApplyAll').click();assert.equal(await page.locator('#icEditScope').inputValue(),'current','one-shot all application stays in single-photo mode');await page.locator('#icPhotos button').nth(1).click();assert.equal(await page.locator('#itCapText').inputValue(),'單張測試');await page.locator('#icTab_redact').click();assert.equal(await page.locator('#icRedactRegions option').count(),1,'apply-all excludes redactions');
  await page.locator('#icRedactMode').selectOption('solid');await page.locator('#icRedactColor').fill('#000000');await page.locator('#icRedactNew').click();await drag(.1,.1,.3,.3,false,async()=>{assert.deepEqual(await pixel(.2,.2),[0,0,0,255],'mask effect is visible while drawing');});
  await page.locator('#icRedactNew').click();await drag(.6,.6,.8,.8);const ids=await page.locator('#icRedactRegions option').evaluateAll(nodes=>nodes.map(n=>n.value));await page.locator('#icRedactRegions').selectOption(ids[1]);await drag(.2,.2,.4,.3);assert.deepEqual(await page.locator('#icRedactRegions option').evaluateAll(nodes=>nodes.map(n=>n.value)),ids,'moving a region preserves numbering and layer order');
  if(width<=390){const layout=await page.evaluate(()=>{const a=document.querySelector('.ic-mini').getBoundingClientRect(),b=document.querySelector('.ic-controls').getBoundingClientRect();return a.bottom<=b.top+1;});assert(layout,'mobile preview reserves space above settings');}
  assert(await page.locator('#imageComposer').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'no horizontal dialog overflow');
  await page.screenshot({path:path.join(require('node:os').tmpdir(),'crm-polish-'+width+'.png')});assert.deepEqual(errors,[]);await context.close();console.log('PASS polish '+width+'px: handles, selected overlay, crop review/export protection, undo, per-photo default, apply-all, mobile non-overlap');
 }}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
