const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST')return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='retry'&&window.retryError?{error:window.retryError}:type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');




await p.route('https://sale.591.com.tw/candidate-photo.jpg',r=>r.fulfill({body:fs.readFileSync(path.join(process.argv[2],'sample-photo.jpg')),contentType:'image/jpeg'}));await p.evaluate(()=>{DB=[{id:'candidate-owner',name:'同棟辨識測試屋主長名稱',types:['庫存屋主'],sProperties:[{addr:'桃園市蘆竹區濱海路一段10號',community:'鴻輝AI首席'}]}];persist();InventoryMarket.open(InventoryMarket.entries()[0].key);});
await p.locator('.im-config>summary').click();await p.locator('[name=enabled]').check();await p.locator('#imSave').click();await p.waitForFunction(()=>document.querySelector('#imSaveNotice').dataset.state==='success');
await p.evaluate(async()=>{window.candidateBase={source:'591',image:'https://sale.591.com.tw/candidate-photo.jpg',title:'待核對廠辦完整長標題'.repeat(8),address:'桃園市蘆竹區濱海路一段',price:99999999,area:146.33,floor:8,age:1.7,url:'https://business.591.com.tw/sale/123'};await InventoryMarket.ingest(InventoryMarket.entries()[0],{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'591',status:'ok'}],listings:[{...candidateBase,id:'591:yes'},{...candidateBase,id:'591:no',address:'桃園市蘆竹區濱海路一段（工業區廠辦大樓入口、臨路側附屬空間與後方卸貨區，實際門牌請核對原刊登）'},{...candidateBase,id:'591:learn',address:'桃園市蘆竹區濱海路一段12號'}]});});await p.locator('#imTab-listings').click();assert((await p.locator('#imCount').innerText()).includes('0 組'));assert.equal(await p.locator('[data-building=yes]').count(),3);assert((await p.locator('.im-empty').innerText()).includes('3 筆候選'));assert.equal(await p.evaluate(()=>DB[0].schedules?.length||0),0);
await p.locator('.im-candidates img').first().evaluate(img=>img.decode());for(const width of [1440,1024,700]){await p.setViewportSize({width,height:1000});assert(await p.locator('.im-dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+2));assert(await p.locator('.im-candidates').evaluate(e=>e.scrollWidth<=e.clientWidth+2));if(process.argv[2])await p.screenshot({path:process.argv[2]+'/building-candidates-'+width+'.png'});}
await p.locator('[data-building=yes][data-id="591:yes"]').click();await p.locator('.im-confirm [data-confirm]').click();await p.waitForFunction(()=>document.querySelector('#imCount').textContent.includes('1 組'));assert.equal(await p.locator('[data-building=yes]').count(),2);
await p.locator('[data-building=no][data-id="591:no"]').click();await p.waitForFunction(()=>!document.querySelector('[data-building=no][data-id="591:no"]'));await p.reload();await p.evaluate(()=>InventoryMarket.open(InventoryMarket.entries()[0].key));await p.waitForFunction(()=>document.querySelector('#imCount').textContent.includes('1 組'));assert.equal(await p.locator('[data-building=yes]').count(),1);
await p.locator('.im-decisions>summary').click();await p.locator('[data-building=undo][data-id="591:no"]').click();await p.waitForFunction(()=>!!document.querySelector('[data-building=no][data-id="591:no"]'));
await p.locator('[data-building=yes][data-id="591:learn"]').click();await p.locator('.im-confirm [data-learn]').check();await p.locator('.im-confirm [data-confirm]').click();await p.waitForFunction(()=>InventoryMarket.entries()[0].config.addresses?.includes('12號'));
await p.evaluate(async()=>{const candidateBase=InventoryMarket.entries()[0].config.buildingDecisions['591:yes'].listing;await InventoryMarket.ingest(InventoryMarket.entries()[0],{schema:1,incremental:true,generatedAt:new Date().toISOString(),sources:[{id:'591',status:'partial'}],listings:[{...candidateBase,id:'591:learned-next',address:'桃園市蘆竹區濱海路一段12號'},{...candidateBase,id:'591:other-house',address:'桃園市蘆竹區濱海路一段999號'}]});});await p.locator('#imTab-listings').click();assert.equal(await p.locator('[data-building=yes][data-id="591:learned-next"]').count(),0);assert.equal(await p.locator('[data-building=yes][data-id="591:other-house"]').count(),1);
await p.evaluate(()=>{invJob={buyerId:'inventory:'+InventoryMarket.entries()[0].config.id,status:'partial',sources:[],failures:[]};window.retryError='買方或需求已變更，請重新搜尋';});await p.locator('#imRefresh').click();await p.waitForFunction(()=>document.querySelector('#imRetry').hidden===false);await p.locator('#imSearch').click();await p.waitForFunction(()=>invCalls.some(x=>x.type==='inventorySearch'));assert(await p.evaluate(()=>invCalls.some(x=>x.type==='retry')));
assert.deepEqual(errors,[]);console.log('PASS candidate isolation, confirm/reject/undo/reload, explicit learned door, no whole-road acceptance, changed-demand retry fallback, long content at three widths');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
