const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST')return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');
await p.evaluate(async()=>{DB=[{id:'audit-owner',name:'測試屋主',types:['庫存屋主'],sProperties:[{addr:'台北市內湖區民權東路六段136巷26號',listingPurpose:'店面'}]}];const e=InventoryMarket.entries()[0];e.c.inventoryWatch={[e.slot]:{...e.config,id:'revision-old',enabled:true,transactionsEnabled:true,criteria:{priceMax:4000},buildingDecisions:{'591:yes':{same:true}},ownIds:['591:excluded']}};persist();const p={id:'591:eligible',source:'591',address:e.config.address,title:'一樓店面',price:3000,floor:1};await InventoryMarket.updateState('revision-old',()=>({records:{[p.id]:p,'moi:old':{...p,id:'moi:old',kind:'transaction'}},events:[{id:'old-event',listingId:'moi:old',kind:'成交',at:new Date().toISOString()}],baselines:{591:'2026-10-04'},scans:{591:{id:'previous',at:'2026-10-04'}},candidates:{}}));window.oldEntry=InventoryMarket.entries()[0];InventoryMarket.open(oldEntry.key);});
await p.locator('.im-config>summary').click();await p.locator('[name=priceMax]').fill('3500');await p.locator('#imSave').click();await p.waitForFunction(()=>document.querySelector('#imSaveNotice').dataset.state==='success');
const revised=await p.evaluate(async()=>{const e=InventoryMarket.entries()[0],s=await InventoryMarket.loadState(e.config.id);return {id:e.config.id,records:Object.keys(s.records),baselines:s.baselines,scans:s.scans,events:s.events};});assert.notEqual(revised.id,'revision-old');assert.deepEqual(revised.records,['591:eligible','moi:old']);assert.deepEqual(revised.events,[]);assert.deepEqual(revised.scans,{});assert.equal(revised.baselines['591'],undefined);
await p.evaluate(async()=>{await InventoryMarket.ingest(oldEntry,{generatedAt:new Date().toISOString(),scanId:'late',sources:[{id:'591',status:'ok'}],listings:[{id:'591:late',source:'591',address:oldEntry.config.address,title:'店面',price:1000}]});});assert.equal(await p.evaluate(async()=>(await InventoryMarket.loadState(InventoryMarket.entries()[0].config.id)).records['591:late']),undefined);
await p.locator('.im-config>summary').click();await p.locator('[name=searchPurpose]').selectOption('住宅');await p.locator('#imSave').click();await p.waitForFunction(()=>document.querySelector('#imSaveNotice').dataset.state==='success');const purposeId=await p.evaluate(()=>InventoryMarket.entries()[0].config.id);assert.notEqual(purposeId,revised.id);
await p.locator('.im-config>summary').click();await p.locator('[name=address]').fill('台北市內湖區成功路一段1號');await p.locator('#imSave').click();await p.waitForFunction(()=>document.querySelector('#imSaveNotice').dataset.state==='success');assert.deepEqual(await p.evaluate(()=>InventoryMarket.entries()[0].config.buildingDecisions),{});assert.deepEqual(await p.evaluate(()=>InventoryMarket.entries()[0].config.ownIds),[]);await p.reload();assert.notEqual(await p.evaluate(()=>InventoryMarket.entries()[0].config.id),purposeId);assert.deepEqual(errors,[]);console.log('PASS criteria/purpose revisions retain results without old scan baselines; late old feed ignored; changed scope clears manual decisions; reload persists');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
