const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path'),{randomUUID}=require('crypto');
const root=path.resolve('01-crm/tools/buyer-browser'),store={},listeners={},closed=[],tabMap=new Map();let clock=Date.now(),tabId=0,blocked=false;
class TestDate extends Date{static now(){return clock;}}
const chrome={storage:{local:{get:async()=>structuredClone(store),set:async o=>Object.assign(store,structuredClone(o)),remove:async k=>delete store[k]}},tabs:{create:async o=>{const id=++tabId;tabMap.set(id,o.url);return {id};},get:async id=>({status:'complete',url:tabMap.get(id).replace('shType=list&regionid=3','shType=list&regionid=3&section=26')}),update:async(id,o)=>{tabMap.set(id,o.url);return {id};},remove:async id=>closed.push(id)},scripting:{executeScript:async o=>{if(o.files)return [];if(o.args.length===1)return [{result:true}];const url=new URL(tabMap.get(o.target.tabId)),page=Number(url.searchParams.get('page')||1);url.searchParams.set('page','2');return [{result:{rows:[{id:o.args[0]+':'+page,source:o.args[0],price:1000,title:'測試物件',city:'新北市',district:'板橋區'}],page,total:2,next:page===1?url.href:null,complete:page===2,blocked}}];}},alarms:{get:async()=>null,create:async(n,o)=>{store[n]=o;},clear:async n=>{delete store[n];},onAlarm:{addListener:f=>listeners.alarm=f}},runtime:{onInstalled:{addListener:f=>listeners.install=f},onStartup:{addListener:f=>listeners.start=f},onMessage:{addListener:f=>listeners.message=f}}};
function worker(){const c=vm.createContext({chrome,BuyerStorage:chrome.storage.local,console,URL,structuredClone,Date:TestDate,crypto:{randomUUID},setTimeout:(f,ms)=>{if(ms===120000)return setTimeout(f,ms);clock+=30000;f();},clearTimeout});c.importScripts=(...files)=>files.filter(f=>f!=='storage.js').forEach(f=>vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),c));vm.runInContext(fs.readFileSync(path.join(root,'background.js'),'utf8'),c);return c;}

(async()=>{const c=worker(),ds=[{areaCities:['新北市'],areaDists:['板橋區'],matchCriteria:{keywords:'文化路一段'}}],send=(type,payload)=>new Promise(r=>listeners.message({type,payload},{url:'https://dsiqke8d1w5q2zz5.github.io/jijdspwl3115djsjlp/01-crm/'},r));
const allAreas=vm.runInContext('CRM_AREAS',c);assert.equal(new Set(allAreas.map(a=>a.city)).size,22);assert.equal(allAreas.length,368);for(const a of allAreas){const tasks=vm.runInContext('tasksFor('+JSON.stringify([{areaCities:[a.city],areaDists:[a.district],matchCriteria:{keywords:'中正路'}}])+')',c);assert.equal(tasks.length,3);assert(tasks.find(t=>t.source==='sinyi').url.includes('/'+a.sinyi+'/'+a.zip+'-zip/'));assert.equal(new URL(tasks.find(t=>t.source==='591').url).searchParams.get('regionid'),a.region);assert(tasks.every(t=>t.city===a.city&&t.district===a.district));}assert.equal((await send('inventorySync',[{id:'inventory:one',demands:ds}])).saved,1);assert.equal(store.inventorySelection.length,1);store.selection=[{id:'buyer-one',demands:ds}];await listeners.alarm({name:'buyer-daily'});assert.equal(store.job.status,'completed');assert.deepEqual(store.last.inventoryIds,['inventory:one']);assert.equal(store.job.totalScopes,3);assert.equal(store.selection[0].id,'buyer-one');
await send('inventorySearch',{id:'inventory:one',demands:ds});for(let i=0;i<100&&store.job.status==='running';i++)await new Promise(r=>setImmediate(r));assert(store.inventoryFeeds['inventory:one']);assert(!store.manualFeeds?.['inventory:one']);assert.equal(store.selection.length,1);
const bridge=fs.readFileSync(path.join(root,'bridge.js'),'utf8'),posted=[],calls=[];let handler;const w={addEventListener:(type,f)=>{if(type==='message')handler=f;},postMessage:x=>posted.push(x)};const ctx=vm.createContext({window:w,location:{origin:'https://test.local',href:'https://test.local/'},URL,sessionStorage:{getItem:()=>null},chrome:{runtime:{sendMessage:async x=>{calls.push(x);return {ok:true};}}}});vm.runInContext(bridge,ctx);for(const type of ['retry','inventorySync','inventorySearch'])await handler({source:w,origin:'https://test.local',data:{channel:'CRM_BUYER_REQUEST',id:type,type,payload:{}}});assert.equal(calls.length,3);await handler({source:w,origin:'https://wrong.local',data:{channel:'CRM_BUYER_REQUEST',id:'bad',type:'inventorySearch'}});assert.equal(calls.length,3);console.log('PASS real bridge commands/origin, combined buyer+inventory daily search dedup, isolated inventory feeds and buyer settings preserved');})().catch(e=>{console.error(e);process.exitCode=1});
