const assert=require('assert/strict');global.BuyerGrouping=require('../buyer-grouping.js');const E=require('../inventory-market-engine.js'),{parse,csv}=require('../tools/market-feed/collect.cjs');
const config={mode:'building',address:'新北市板橋區文化路一段100號',community:'巨蛋',aliases:'巨蛋東京花園廣場',addresses:'新北市板橋區新站路200號'};
const base={id:'591:1',source:'591',address:'新北市板橋區文化路一段',community:'巨蛋東京花園廣場',price:2000,area:30,age:20,floor:5,city:'新北市',district:'板橋區'};
assert(E.matches(config,base));assert(!E.matches(config,{...base,community:'新巨蛋'}));assert(!E.matches(config,{...base,address:'新北市新莊區文化路一段'}));assert(!E.matches(config,{...base,address:'新北市板橋區民權路'}));assert(E.matches(config,{...base,address:'新北市板橋區新站路200號五樓',community:'',kind:'transaction'}));assert(!E.matches(config,{...base,address:'新北市板橋區新站路201號',community:'',kind:'transaction'}));assert(E.matches({...config,community:'金城舞5世界花園',aliases:''},{...base,community:'金城舞5-世界花園'}));assert(!E.matches({...config,community:'金城舞5世界花園',aliases:''},{...base,community:'金城舞6世界花園'}));
assert(E.matches({...config,mode:'road',address:'新北市板橋區民權路202巷1號'},{...base,address:'新北市板橋區民權路202巷8號'}));assert(E.matches({...config,mode:'road',address:'新北市板橋區民權路202巷1號'},{...base,address:'新北市板橋區民權路260巷8號'}));assert.equal(E.location('新北市板橋區文化路一段２３之１號五樓').building,E.location('新北市板橋區文化路1段23-1號').building);
const at='2026-10-05T02:00:00Z',feed=(rows,status='ok',generatedAt=at,source='591')=>({generatedAt,sources:[{id:source,status}],listings:rows});let s=E.apply(null,config,feed([base]),at);assert.equal(s.events.length,0);s=E.apply(s,config,feed([{...base,price:1800}],'ok','2026-10-05T03:00:00Z'),'2026-10-05T03:00:00Z');assert.equal(s.events[0].kind,'Down');s=E.apply(s,config,feed([base]),at);assert.equal(s.records[base.id].price,1800);assert.equal(s.events.length,1);s=E.apply(s,config,feed([{...base,id:'591:2',price:2200}],'partial','2026-10-05T04:00:00Z'),'2026-10-05T04:00:00Z');assert.equal(s.events.at(-1).kind,'New');const n=s.events.length;s=E.apply(s,config,feed([],'error'));assert.equal(s.events.length,n);assert.equal(Object.keys(s.records).length,2);
let partial=E.apply(null,config,feed([base],'partial'));assert(!partial.baselines['591']);partial=E.apply(partial,config,feed([base,{...base,id:'591:3'}]));assert.equal(partial.events.length,0);assert(partial.baselines['591']);
let cross=E.apply(null,config,{generatedAt:at,sources:[{id:'591',status:'ok'},{id:'sinyi',status:'ok'}],listings:[base]});cross=E.apply(cross,config,feed([{...base,id:'sinyi:1',source:'sinyi'}],'ok',at,'sinyi'));assert.equal(cross.events.length,0);
let own=E.apply(null,{...config,ownIds:[base.id]},feed([base]));own=E.apply(own,{...config,ownIds:[base.id]},feed([{...base,price:1000}],'ok','2026-10-05T05:00:00Z'));assert.equal(own.events.length,0);
const tx={...base,id:'moi:1',source:'moi',kind:'transaction',address:'新北市板橋區文化路一段100號五樓',tradeDate:'2026-08-01'};let t=E.apply(null,config,feed([tx],'ok',at,'moi'));t=E.apply(t,config,feed([{...tx,id:'moi:2'}],'ok','2026-10-05T05:00:00Z','moi'),'2026-10-05T05:00:00Z');assert.equal(t.events[0].kind,'成交');t=E.apply(t,config,feed([{...tx,id:'moi:2',price:1800}],'ok','2026-10-05T06:00:00Z','moi'),'2026-10-05T06:00:00Z');assert.equal(t.events[1].kind,'成交更正');
const c={id:'test'},now=new Date('2026-10-05T06:00:00Z');assert(E.reminder(c,'id','測試社區',t,()=>true,now));assert.equal(c.schedules.length,1);c.schedules[0]._deleted=true;assert(!E.reminder(c,'id','測試社區',t,()=>true,now));assert(c.schedules[0]._deleted);const failed={id:'fail'};assert(!E.reminder(failed,'id','社區',t,()=>false,now));assert.equal(failed.schedules,undefined);assert(!E.reminder(c,'id','社區',t,()=>true,new Date('2026-10-06T06:00:00Z')));
assert.deepEqual(csv('a,b\n"x,y","z""w"\n'),[['a','b'],['x,y','z"w']]);const raw='鄉鎮市區,交易標的,土地位置建物門牌,交易年月日,總價元,建物移轉總面積平方公尺,編號\n板橋區,房地(土地+建物),新北市板橋區文化路100號,1150801,20000000,99.17355,TEST';const row=parse(raw,'新北市')[0];assert.equal(row.price,2000);assert.equal(row.area,30);assert.equal(row.tradeDate,'2026-08-01');assert.throws(()=>parse('bad','新北市'));
console.log('PASS aliases exclude 新巨蛋; punctuation, exact building, multiple addresses, district/road conflicts, baseline/partial/zero/error/stale feeds, dedup, own listings, price drop, official transaction corrections, daily reminders and rollback, CSV units/dates');

for(const separator of ['/', '／', '\n']){const cfg={...config,aliases:'巨蛋'+separator+'巨蛋東京花園廣場'};assert.deepEqual(E.aliases(cfg),['巨蛋','巨蛋東京花園廣場']);assert(E.matches(cfg,base));assert(!E.matches(cfg,{...base,community:'新巨蛋'}));}
const slash={...config,community:'巨蛋/巨蛋東京花園廣場',aliases:''};
assert(E.matches(slash,base));assert(E.matches(slash,{...base,community:'巨蛋'}));assert(!E.matches(slash,{...base,community:'新巨蛋'}));
assert(E.matches(slash,{...base,community:'',title:'巨蛋景觀套房'}));
assert(!E.matches(slash,{...base,community:'',title:'新巨蛋景觀套房'}));
assert(!E.matches(slash,{...base,address:'新北市板橋區文化路二段',community:'巨蛋'}));

{const c={mode:'road',address:'新北市土城區延和路41巷2弄11號5樓',criteria:{floorMin:4,floorMax:5}};
assert.equal(E.location(c.address).searchStreet,'延和路');
for(const address of ['新北市土城區延和路','新北市土城區延和路41巷','新北市土城區延和路41巷6弄8號','新北市土城區延和路99巷3號']){assert(E.matches(c,{address}));for(const floor of [4,5])assert(E.assess(c,{address,floor}).match);assert(!E.assess(c,{address,floor:3}).match);}
for(const address of ['新北市土城區延吉路','新北市板橋區延和路'])assert(!E.matches(c,{address}));
assert(!E.matches({...c,address:'新北市板橋區文化路一段3巷1號'},{address:'新北市板橋區文化路二段'}));
assert(E.matches({...c,address:'新北市板橋區文化路一段3巷1號'},{address:'新北市板橋區文化路1段99巷'}));
assert(!E.matches({...c,mode:'building'},{address:'新北市土城區延和路41巷6弄11號'}));
console.log('PASS whole street ignores lanes/alleys, retains district/section/floor limits and exact building matching');}

{const c={criteria:E.criteria({buildingType:'公寓',floorMin:4,floorMax:5})};
assert(E.assess(c,{buildingType:'公寓',floor:4}).match);
for(const p of [{buildingType:'住宅大樓',floor:4},{buildingType:'華廈',floor:5},{buildingType:'店面',totalFloors:20,floor:4},{buildingType:'公寓',elevator:true,floor:4},{buildingType:'公寓',floor:3}])assert(!E.assess(c,p).match);
assert.deepEqual(E.assess(c,{floor:4}),{match:true,missing:['房型']});assert.deepEqual(E.assess(c,{kind:'transaction',buildingType:'住宅大樓',floor:20}),{match:true,missing:[]});assert.throws(()=>E.criteria({buildingType:'invalid'}));console.log('PASS apartment criteria, elevator/high-rise evidence, missing type, floors and transaction isolation');}

{const groups=[[{p:{id:'old',price:100}}],[{p:{id:'first',price:200}},{p:{id:'new',price:200}}],[{p:{id:'down',price:300}}]],events=[{listingId:'new',kind:'New',at:'2026-10-05'},{listingId:'down',kind:'Down',at:'2026-10-05'}];assert.deepEqual(E.prioritizeGroups(groups,events).map(g=>g[0].p.id),['first','down','old']);assert.deepEqual(E.prioritizeGroups(groups,events,Date.parse('2026-10-06')),groups);assert.deepEqual(E.prioritizeGroups(groups,[{listingId:'down',kind:'疑似下架',at:'2026-10-05'}]),groups);assert.deepEqual(groups.map(g=>g[0].p.id),['old','first','down']);console.log('PASS unread New/Down group priority, member events, stable price order and acknowledge reset');}

{const c={mode:'building',address:'新北市土城區中央路四段52巷8號',community:'皇翔泱美'};for(const source of ['yungching','sinyi','591']){const p={id:source+':test',source,community:'皇翔泱美',address:'新北市土城區中央路四段',price:2188};assert(E.matches(c,p));assert(E.matches({...c,mode:'project'},p));for(const address of ['新北市土城區中央路三段','新北市土城區中央路四段53巷','新北市板橋區中央路四段'])assert(!E.matches(c,{...p,address}));assert(!E.matches(c,{...p,community:'另一社區'}));assert(!E.matches(c,{...p,kind:'transaction'}));assert(E.apply(null,c,feed([p],'ok',at,source)).records[p.id]);}console.log('PASS 皇翔泱美 all three sources with omitted lane; explicit lane/section/district/community conflicts and transactions stay excluded');}

{let state=E.apply(null,config,feed([tx],'ok',at,'moi'));state=E.apply(state,config,feed([{...tx,area:31,notes:'官方更正坪數'}],'ok','2026-10-05T08:00:00Z','moi'));assert.equal(state.events.at(-1).kind,'成交更正');const count=state.events.length;state=E.apply(state,config,feed([{...tx,area:31,notes:'官方更正坪數'}],'ok','2026-10-05T08:00:00Z','moi'));assert.equal(state.events.length,count);console.log('PASS transaction same-price area/notes correction and repeated-feed dedup');}
