const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST')return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.11'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');


await p.evaluate(()=>{DB=[{id:'road-test',name:'測試屋主',types:['庫存屋主'],type:'庫存屋主',sProperties:[{addr:'新北市土城區延和路41巷2弄11號5樓'}]}];persist();InventoryMarket.open();});
await p.locator('.im-config').evaluate(e=>e.open=true);await p.locator('[name=mode]').selectOption('road');await p.locator('[name=floorMin]').fill('4');await p.locator('[name=floorMax]').fill('5');await p.locator('[name=buildingType]').selectOption('公寓');await p.locator('[name=enabled]').check();await p.locator('#imSave').click();await p.waitForFunction(()=>document.querySelector('#imSaveNotice').dataset.state==='success');
const check=async()=>assert.deepEqual(await p.evaluate(()=>{const e=InventoryMarket.entries()[0];return {keywords:InventoryMarket.demands(e.config)[0].matchCriteria.keywords,criteria:e.config.criteria,address:e.config.address};}),{keywords:'延和路',criteria:{buildingType:'公寓',floorMin:4,floorMax:5},address:'新北市土城區延和路41巷2弄11號5樓'});await check();await p.locator('#imSearch').click();await p.waitForFunction(()=>invCalls.some(x=>x.type==='inventorySearch'));assert.equal(await p.evaluate(()=>invCalls.filter(x=>x.type==='inventorySync').at(-1).payload[0].demands[0].matchCriteria.keywords),'延和路');await p.reload();await p.evaluate(()=>InventoryMarket.open());await check();assert.equal(await p.evaluate(()=>InventoryMarket.demands(InventoryMarket.entries()[0].config)[0].matchCriteria.types[0]),'公寓');
await p.waitForTimeout(300);await p.evaluate(async()=>{const e=InventoryMarket.entries()[0];await InventoryMarket.ingest(e,{generatedAt:new Date().toISOString(),sources:[{id:'591',status:'ok'}],listings:[{id:'apt',source:'591',address:e.config.address,title:'公寓四樓',buildingType:'公寓',floor:4,price:1000},{id:'tower',source:'591',address:e.config.address,title:'大樓四樓',buildingType:'住宅大樓',floor:4,price:2580}]});});await p.locator('[data-view=listings]').click();assert.equal(await p.locator('.im-row').count(),1);assert((await p.locator('.im-row').innerText()).includes('公寓四樓'));
await p.locator('.im-config').evaluate(e=>e.open=true);for(const width of [1440,1024,700]){await p.setViewportSize({width,height:1000});assert(await p.locator('[name=buildingType]').evaluate(e=>e.getBoundingClientRect().right<=e.closest('fieldset').getBoundingClientRect().right));}
if(process.argv[2])await p.screenshot({path:process.argv[2]});assert.deepEqual(errors,[]);console.log('PASS saved/reloaded full address and floors preserved; manual/automatic helper search keyword is 延和路');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
