const assert=require('node:assert/strict');global.BuyerGrouping=require('../buyer-grouping.js');const E=require('../inventory-market-engine.js');
const cfg={enabled:true,transactionsEnabled:true,mode:'road',address:'新北市板橋區民生路三段',criteria:{priceMax:1500}};
const p={id:'591:1',source:'591',address:cfg.address,price:1000,area:20,floor:5,age:10};
const at=n=>new Date(Date.UTC(2026,9,5,n)).toISOString();const feed=(n,rows=[],status='ok',extra={})=>({scanId:'scan'+n,generatedAt:at(n),sources:[{id:'591',status}],listings:rows,...extra});
let s=E.apply(null,cfg,feed(0,[p]),at(0));assert.equal(s.events.length,0);
s=E.apply(s,cfg,feed(1),at(1));assert.equal(s.records[p.id].missingScans,1);
s=E.apply(s,cfg,feed(1),at(1));assert.equal(s.records[p.id].missingScans,1);
s=E.apply(s,cfg,feed(2,[],'partial'),at(2));assert.equal(s.records[p.id].missingScans,1);
s=E.apply(s,cfg,feed(3,[],'ok',{incremental:true}),at(3));assert.equal(s.records[p.id].missingScans,1);
s=E.apply(s,cfg,feed(4),at(4));s=E.apply(s,cfg,feed(5),at(5));assert.equal(s.events.at(-1).kind,'疑似下架');assert.equal(s.events.length,1);
s=E.apply(s,cfg,feed(0,[p]),at(6));assert.equal(s.records[p.id].availability,'suspected');
s=E.apply(s,cfg,feed(6),at(6));assert.equal(s.events.length,1);
s=E.apply(s,cfg,feed(7,[p]),at(7));assert.equal(s.events.at(-1).kind,'重新上架');assert.equal(s.records[p.id].missingScans,0);
s=E.apply(s,cfg,feed(8),at(8));s=E.verify(s,cfg,[{id:p.id,status:'unknown'}],'scan8',at(8));assert.equal(s.records[p.id].availability,'active');
s=E.verify(s,cfg,[{id:p.id,status:'off'}],'scan8',at(8));assert.equal(s.events.at(-1).kind,'已下架');const n=s.events.length;s=E.verify(s,cfg,[{id:p.id,status:'off'}],'scan8',at(8));assert.equal(s.events.length,n);
s=E.apply(s,cfg,feed(9,[{...p,price:2000}]),at(9));assert.equal(s.records[p.id].availability,'active');assert.equal(s.events.length,n);assert(!E.assess(cfg,s.records[p.id]).match);
assert(E.assess(cfg,{...p,kind:'transaction',price:9999}).match);assert.deepEqual(E.assess({criteria:{roomsMin:2}},p).missing,['房數']);assert.throws(()=>E.criteria({areaMin:20,areaMax:10}));assert.throws(()=>E.criteria({roomsMin:1.5}));assert.equal(E.criteria({floorMin:-1}).floorMin,-1);
let disabled=E.apply(null,{...cfg,enabled:false},feed(0,[p]));assert.equal(Object.keys(disabled.records).length,0);
let own=E.apply(null,{...cfg,ownIds:[p.id]},feed(0,[p]));assert.equal(Object.keys(own.records).length,0);
let dup=E.apply(null,cfg,feed(0,[p,{...p,id:'591:2'}]),at(0));for(let i=1;i<4;i++)dup=E.apply(dup,cfg,feed(i,[{...p,id:'591:2'}]),at(i));assert.equal(dup.events.at(-1).kind,'其中一筆疑似下架');
let retry=E.apply(null,cfg,feed(0,[p]),at(0));retry=E.apply(retry,cfg,feed(1),at(1));retry=E.apply(retry,cfg,feed(2,[],'ok',{scanId:'scan1'}),at(2));assert.equal(retry.records[p.id].missingScans,1);
let old=E.apply(null,cfg,feed(0,[p]),at(0));for(let i=1;i<5;i++)old=E.apply(old,cfg,feed(i,[],'ok',{scanId:undefined}),at(i));assert.equal(old.events.length,0);
console.log('PASS lifecycle: 3 complete unique scans, partial/incremental/legacy exclusion, cached/stale/retry feeds, off confirmation, reappearance, conditions, duplicate ads, own exclusion and disabled source');
