const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST')return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='buyerVerify'?{checks:payload.rows.map(p=>({id:p.id,...(['yungching:7417941','591:20734577'].includes(p.id)?{usage:'住家用',usageEvidence:'法定用途',availability:'available'}:{})}))}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');





await p.evaluate(async()=>{DB=[{id:'purpose',name:'測試',types:['庫存屋主'],sProperties:[{addr:'台北市中正區重慶南路三段4巷9號',listingPurpose:'住宅'}]}];const e=InventoryMarket.entries()[0];e.c.inventoryWatch={[e.slot]:{...e.config,id:'pw',enabled:true}};persist();InventoryMarket.open();const x=InventoryMarket.entries()[0];await InventoryMarket.ingest(x,{generatedAt:new Date().toISOString(),sources:[{id:'yungching',status:'ok'}],listings:[{id:'yungching:7417941',source:'yungching',url:'https://buy.yungching.com.tw/house/7417941',title:'用途自動補查',address:x.config.address,price:2288,area:28.51,floor:3,age:43},{id:'yungching:999',source:'yungching',url:'https://buy.yungching.com.tw/house/999',title:'待人工確認長名稱'.repeat(15),address:x.config.address,price:99999999,area:99999.99,floor:3,age:43}]});});
await p.waitForFunction(async()=>{const s=await InventoryMarket.loadState('pw');return s.records['yungching:7417941'].usage==='住家用';});
await p.evaluate(async()=>{await InventoryMarket.updateState('pw',s=>{s.records['591:20687135']={...s.records['yungching:999'],id:'591:20687135',source:'591',title:'失效刊登',availability:'off'};return s;});});await p.locator('#imRefresh').click();await p.waitForTimeout(300);
assert.equal(await p.locator('details.im-candidates').filter({hasText:'已下架／連結失效'}).count(),1);

await p.evaluate(async()=>{await InventoryMarket.updateState('pw',s=>{const a=s.records['591:20687135'];a.title='同一戶完整長名稱'.repeat(10);a.offConfirmedAt='2026-10-06T01:00:00Z';a.image='https://img.591.com.tw/test.jpg';const b={...a,id:'591:copy',offConfirmedAt:'2026-10-07T01:00:00Z',url:'https://sale.591.com.tw/home/house/detail/2/12345.html'};s.records[b.id]=b;s.events.push({id:'copy-off',listingId:b.id,kind:'已下架',at:b.offConfirmedAt});return s;});});await p.locator('#imTab-listings').click();await p.locator('[data-inventory-view=expired]').click();assert.equal(await p.locator('.im-expired-group').count(),0);assert.equal(await p.locator('.im-expired-panel [data-delete-expired]:visible').count(),2);assert.deepEqual(await p.locator('.im-expired-panel [data-delete-expired]').evaluateAll(es=>es.map(e=>e.dataset.deleteExpired)),['591:copy','591:20687135']);
await p.evaluate(async()=>InventoryMarket.updateState('pw',s=>{const a=s.records['591:20687135'];s.records.unknown={...a,id:'unknown',title:'時間未記錄的廣告',offConfirmedAt:null};s.records.fallback={...a,id:'fallback',title:'事件有時間的廣告',offConfirmedAt:'invalid'};s.events.push({id:'fallback-off',listingId:'fallback',kind:'已下架',at:'2026-10-08T02:00:00Z'});return s;}));await p.locator('#imTab-listings').click();assert.deepEqual(await p.locator('.im-expired-panel [data-delete-expired]').evaluateAll(es=>es.map(e=>e.dataset.deleteExpired)),['fallback','591:copy','591:20687135','unknown']);assert((await p.locator('.im-expired-panel .im-listing-row').last().innerText()).includes('時間未記錄'));for(const width of [1440,1024,780]){await p.setViewportSize({width,height:1000});assert(await p.locator('#imResults').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await p.screenshot({path:path.join(process.env.TEMP,'off-flat-'+width+'.png')});}
await p.locator('#imRead').click();await p.waitForTimeout(100);assert.equal(await p.locator('.im-expired-panel [data-delete-expired]').first().getAttribute('data-delete-expired'),'fallback');await p.reload();await p.evaluate(()=>InventoryMarket.open());await p.waitForSelector('.im-expired-panel',{state:'attached'});await p.locator('button[data-inventory-view=expired]').click();assert.deepEqual(await p.locator('.im-expired-panel [data-delete-expired]').evaluateAll(es=>es.map(e=>e.dataset.deleteExpired)),['fallback','591:copy','591:20687135','unknown']);assert.equal(await p.locator('.im-expired-group').count(),0);assert.deepEqual(errors,[]);console.log('PASS flat off list newest first, unknown last, event fallback, read/reload stability and long layout');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
