const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST')return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='buyerVerify'?{checks:payload.rows.map(p=>({id:p.id,...(['yungching:7417941','591:20734577'].includes(p.id)?{usage:'住家用',usageEvidence:'法定用途',availability:'available'}:{})}))}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');





await p.evaluate(async()=>{DB=[{id:'purpose',name:'測試',types:['庫存屋主'],sProperties:[{addr:'台北市中正區重慶南路三段4巷9號',listingPurpose:'住宅'}]}];const e=InventoryMarket.entries()[0];e.c.inventoryWatch={[e.slot]:{...e.config,id:'pw',enabled:true}};persist();InventoryMarket.open();const x=InventoryMarket.entries()[0];await InventoryMarket.ingest(x,{generatedAt:new Date().toISOString(),sources:[{id:'yungching',status:'ok'}],listings:[{id:'yungching:7417941',source:'yungching',url:'https://buy.yungching.com.tw/house/7417941',title:'用途自動補查',address:x.config.address,price:2288,area:28.51,floor:3,age:43},{id:'yungching:999',source:'yungching',url:'https://buy.yungching.com.tw/house/999',title:'待人工確認長名稱'.repeat(15),address:x.config.address,price:99999999,area:99999.99,floor:3,age:43}]});});
await p.waitForFunction(async()=>{const s=await InventoryMarket.loadState('pw');return s.records['yungching:7417941'].usage==='住家用';});
await p.evaluate(async()=>{await InventoryMarket.updateState('pw',s=>{s.records['591:20687135']={...s.records['yungching:999'],id:'591:20687135',source:'591',title:'失效刊登',availability:'off'};return s;});});await p.locator('#imTab-listings').click();await p.waitForTimeout(300);
assert.equal(await p.locator('details.im-candidates').filter({hasText:'已下架／連結失效'}).count(),1);
const pending=p.locator('details.im-candidates').filter({hasText:'待確認用途'});await p.locator('[data-inventory-view=purpose]').click();
await p.locator('[data-purpose="yungching:999"]').click();await p.locator('.im-confirm [data-cancel]').click();assert(await p.locator('[data-purpose="yungching:999"]').isVisible());
await p.locator('[data-purpose="yungching:999"]').click();await p.locator('.im-confirm [data-confirm]').click();await p.waitForFunction(()=>document.querySelector('[data-purpose="yungching:999"]')?.textContent.includes('用途已確認'));
assert.equal(await p.locator('details.im-candidates').filter({hasText:'待確認用途'}).count(),0);
for(const width of [1440,1024,780]){await p.setViewportSize({width,height:1000});await p.screenshot({path:require('path').join(process.env.TEMP,'inventory-purpose-'+width+'.png'),fullPage:true});assert(await p.locator('#imResults').evaluate(e=>e.scrollWidth<=e.clientWidth+2));}
await p.reload();await p.evaluate(()=>InventoryMarket.open());await p.waitForFunction(()=>document.querySelector('[data-purpose="yungching:999"]')?.textContent.includes('用途已確認'));await p.locator('[data-purpose="yungching:999"]').click();await p.locator('.im-confirm [data-cancel]').click();assert(await p.locator('.im-meta [data-purpose="yungching:999"]').isVisible());await p.locator('[data-purpose="yungching:999"]').click();await p.locator('.im-confirm [data-confirm]').click();await p.waitForFunction(()=>document.querySelector('#imResults').textContent.includes('待確認用途'));

await p.evaluate(async()=>{await InventoryMarket.updateState('pw',s=>{s.events.push({id:'confirmed-off',kind:'已下架',listingId:'591:20687135',at:new Date().toISOString()});return s;});});await p.locator('#imTab-listings').click();const sections=await p.locator('#imResults>details.im-candidates>summary').allTextContents();assert(sections.findIndex(x=>x.includes('待確認用途'))<sections.findIndex(x=>x.includes('已下架')));
await p.locator('[data-inventory-view=expired]').click();assert.equal(await p.locator('.im-expired-panel .im-leading-badges').innerText(),'新下架');for(const width of [1440,1024,780]){await p.setViewportSize({width,height:1000});assert(await p.locator('.im-expired-panel').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await p.screenshot({path:path.join(process.env.TEMP,'inventory-off-'+width+'.png'),fullPage:true});}
await p.evaluate(async()=>{await InventoryMarket.updateState('pw',s=>{const old={...s.records['591:20687135'],id:'591:old',title:'歷史下架'};s.records={'591:old':old,...s.records};s.events.push({id:'old-off',kind:'已下架',listingId:old.id,at:'2020-01-01T00:00:00Z'});s.ackListings=Date.parse('2021-01-01');return s;});});
await p.locator('#imTab-listings').click();
assert.deepEqual(await p.locator('.im-expired-panel .im-off-badge').allTextContents(),['新下架','01/01']);
assert.equal(await p.locator('.im-new-off-badge').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 240, 227)');
await p.reload();await p.evaluate(()=>InventoryMarket.open());await p.waitForSelector('.im-expired-panel',{state:'attached'});await p.locator('[data-inventory-view=expired]').click();assert.equal(await p.locator('.im-new-off-badge').count(),1);
await p.locator('#imRead').click();await p.waitForTimeout(150);assert.deepEqual(await p.locator('.im-expired-panel .im-off-badge').allTextContents(),['新下架','01/01']);
await p.reload();await p.evaluate(()=>InventoryMarket.open());await p.waitForSelector('.im-expired-panel',{state:'attached'});await p.locator('[data-inventory-view=expired]').click();assert.equal(await p.locator('.im-new-off-badge').count(),1);
await p.evaluate(async()=>{await InventoryMarket.updateState('pw',s=>{delete s.records['591:old'];return s;});});await p.locator('#imTab-listings').click();
await p.locator('[data-delete-expired]').click();await p.locator('.im-confirm [data-cancel]').click();assert.equal(await p.locator('[data-delete-expired]').count(),1);
await p.locator('[data-delete-expired]').click();await p.locator('.im-confirm [data-confirm]').click();await p.waitForFunction(()=>!document.querySelector('[data-delete-expired]'));
assert(await p.evaluate(async()=>!(await InventoryMarket.loadState('pw')).records['591:20687135']));
await p.reload();await p.evaluate(()=>InventoryMarket.open());await p.waitForTimeout(150);assert.equal(await p.locator('[data-delete-expired]').count(),0);
assert(await p.evaluate(()=>InventoryMarket.entries()[0].config.deletedListings['591:20687135']));
await p.evaluate(async()=>{const e=InventoryMarket.entries()[0];e.c.inventoryWatch[e.slot].enabled=false;persist();await InventoryMarket.updateState('pw',s=>{s.records['591:20734577']={id:'591:20734577',source:'591',url:'https://sale.591.com.tw/home/house/detail/2/20734577.html',address:e.config.address,title:'用途補查測試',price:2688,area:51.93,floor:8};return s;});});await p.reload();await p.evaluate(()=>InventoryMarket.open());await p.waitForFunction(async()=>(await InventoryMarket.loadState('pw')).records['591:20734577'].usage==='住家用');assert.equal(await p.evaluate(()=>InventoryMarket.entries()[0].config.enabled),false);assert.equal(await p.evaluate(()=>invCalls.filter(c=>c.type==='inventorySearch').length),0);assert(await p.locator('#imResults>.im-row').filter({hasText:'用途補查測試'}).isVisible());await p.reload();await p.evaluate(()=>InventoryMarket.open());await p.waitForFunction(()=>document.querySelector('#imResults')?.textContent.includes('用途補查測試'));assert.equal(await p.evaluate(async()=>(await InventoryMarket.loadState('pw')).records['591:20734577'].usage),'住家用');assert.deepEqual(errors,[]);console.log('PASS automatic usage, manual cancel/confirm/reload/undo and 3 widths');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
