const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST')return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='buyerVerify'?{checks:payload.rows.map(p=>({id:p.id,...(p.id==='yungching:7417941'?{usage:'住家用',usageEvidence:'永慶謄本用途'}:{})}))}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');





await p.evaluate(async()=>{DB=[{id:'purpose',name:'測試',types:['庫存屋主'],sProperties:[{addr:'台北市中正區重慶南路三段4巷9號',listingPurpose:'住宅'}]}];const e=InventoryMarket.entries()[0];e.c.inventoryWatch={[e.slot]:{...e.config,id:'pw',enabled:true}};persist();InventoryMarket.open();const x=InventoryMarket.entries()[0];await InventoryMarket.ingest(x,{generatedAt:new Date().toISOString(),sources:[{id:'yungching',status:'ok'}],listings:[{id:'yungching:7417941',source:'yungching',url:'https://buy.yungching.com.tw/house/7417941',title:'用途自動補查',address:x.config.address,price:2288,area:28.51,floor:3,age:43},{id:'yungching:999',source:'yungching',url:'https://buy.yungching.com.tw/house/999',title:'待人工確認長名稱'.repeat(15),address:x.config.address,price:99999999,area:99999.99,floor:3,age:43}]});});
await p.waitForFunction(async()=>{const s=await InventoryMarket.loadState('pw');return s.records['yungching:7417941'].usage==='住家用';});
await p.locator('#imRefresh').click();await p.waitForTimeout(300);
const pending=p.locator('details.im-candidates').filter({hasText:'待確認用途'});await pending.locator('summary').first().click();
await p.locator('[data-purpose="yungching:999"]').click();await p.locator('.im-confirm [data-cancel]').click();assert(await p.locator('[data-purpose="yungching:999"]').isVisible());
await p.locator('[data-purpose="yungching:999"]').click();await p.locator('.im-confirm [data-confirm]').click();await p.waitForFunction(()=>document.querySelector('[data-purpose="yungching:999"]')?.textContent.includes('撤回'));
assert.equal(await p.locator('details.im-candidates').filter({hasText:'待確認用途'}).count(),0);
for(const width of [1440,1024,780]){await p.setViewportSize({width,height:1000});await p.screenshot({path:require('path').join(process.env.TEMP,'inventory-purpose-'+width+'.png'),fullPage:true});assert(await p.locator('#imResults').evaluate(e=>e.scrollWidth<=e.clientWidth+2));}
await p.reload();await p.evaluate(()=>InventoryMarket.open());await p.waitForFunction(()=>document.querySelector('[data-purpose="yungching:999"]')?.textContent.includes('撤回'));await p.locator('[data-purpose="yungching:999"]').click();await p.waitForFunction(()=>document.querySelector('#imResults').textContent.includes('待確認用途'));
assert.deepEqual(errors,[]);console.log('PASS automatic usage, manual cancel/confirm/reload/undo and 3 widths');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
