const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST')return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.11'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');



await p.evaluate(async()=>{DB=[{id:'owner-test',name:'測試屋主',types:['庫存屋主'],type:'庫存屋主',sProperties:[{addr:'新北市土城區中央路四段52巷8號',community:'皇翔泱美'},{addr:'新北市土城區延和路41巷2弄11號',community:'另一間物件長名稱'.repeat(8)}]},{id:'other-owner',name:'另一位屋主',types:['庫存屋主'],sProperties:[{addr:'新北市板橋區文化路一段1號',community:'不應出現'}]}];persist();InventoryMarket.open(InventoryMarket.entries()[0].key);});
assert.equal(await p.locator('[data-property]').count(),2);assert(!(await p.locator('#imProperty').innerText()).includes('不應出現'));
assert(await p.locator('#imOwnerPrev').isDisabled());assert.equal(await p.locator('#imOwnerPosition').innerText(),'1 / 2');await p.locator('#imTab-transactions').click();await p.locator('#imOwnerNext').click();assert.equal(await p.locator('.im-owner').innerText(),'另一位屋主');assert.equal(await p.locator('[data-property]').count(),1);assert.equal(await p.locator('#imView').getAttribute('data-value'),'transactions');assert(await p.locator('#imOwnerNext').isDisabled());await p.locator('#imOwnerPrev').click();assert.equal(await p.locator('.im-owner').innerText(),'測試屋主');await p.locator('#imTab-listings').click();await p.locator('.im-config').evaluate(e=>e.open=true);await p.locator('[name=priceMax]').fill('1234');await p.locator('#imOwnerNext').click();assert.equal(await p.locator('.im-owner').innerText(),'測試屋主');assert.equal(await p.locator('[name=priceMax]').inputValue(),'1234');await p.locator('[name=priceMax]').fill('');
await p.locator('.im-config').evaluate(e=>e.open=true);await p.locator('[name=enabled]').check();await p.locator('[name=priceMax]').fill('999999999');await p.locator('#imSave').click();await p.waitForFunction(()=>document.querySelector('#imSaveNotice').dataset.state==='success');assert.equal(await p.locator('.im-config[open]').count(),0);

await p.evaluate(()=>{invJob={buyerId:'inventory:'+InventoryMarket.entries()[0].config.id,status:'running',pages:5,doneScopes:7,totalScopes:14,sources:[]};});await p.locator('#imRefresh').click();await p.waitForFunction(()=>document.querySelector('#imStatus').textContent.includes('已讀 5 頁'));await p.locator('#imOwnerNext').click();assert(!(await p.locator('#imStatus').innerText()).includes('已讀 5 頁'));assert((await p.locator('#imStatus').innerText()).includes('其他物件搜尋中'));assert(await p.locator('#imStop').isHidden());await p.locator('#imOwnerPrev').click();await p.waitForFunction(()=>document.querySelector('#imStatus').textContent.includes('已讀 5 頁'));await p.locator('[data-property]').nth(1).click();assert(!(await p.locator('#imStatus').innerText()).includes('已讀 5 頁'));await p.locator('[data-property]').first().click();assert((await p.locator('#imStatus').innerText()).includes('已讀 5 頁'));
await p.evaluate(()=>{invJob.status='partial';invJob.failures=[{source:'sinyi',reason:'讀取超過 2 分鐘，請確認原站是否要求驗證'},{source:'yungching',reason:'找不到可確認的下一頁或末頁'}];});await p.locator('#imRefresh').click();await p.waitForFunction(()=>document.querySelector('#imStatus').textContent.includes('信義：讀取超過 2 分鐘'));assert((await p.locator('#imStatus').innerText()).includes('永慶：找不到'));for(const width of [1440,700]){await p.setViewportSize({width,height:1000});assert(await p.locator('#imStatus').evaluate(e=>e.scrollWidth<=e.clientWidth+2));if(process.argv[2])await p.screenshot({path:process.argv[2]+'/search-failure-'+width+'.png'});}await p.locator('#imSearch').click();await p.waitForFunction(()=>invCalls.some(x=>x.type==='retry'));assert.equal(await p.evaluate(()=>invCalls.filter(x=>x.type==='inventorySearch').length),0);await p.evaluate(()=>{invJob=null;});await p.locator('#imRefresh').click();
await p.evaluate(async()=>{const e=InventoryMarket.entries()[0],base={community:'皇翔泱美',address:'新北市土城區中央路四段',city:'新北市',district:'土城區',price:2188,area:40.21,age:null,floor:null,floorText:'22-23樓/23樓',rooms:2,title:'長標題測試皇翔泱美景觀兩房平面車位'.repeat(4)};await InventoryMarket.ingest(e,{schema:1,generatedAt:new Date().toISOString(),sources:['yungching','sinyi','591'].map(id=>({id,status:'ok'})),listings:['yungching','sinyi','591','591'].map((source,i)=>({...base,age:i===0?28:null,id:source+':'+i,source,url:source==='591'?'https://sale.591.com.tw/home/house/detail/2/'+i+'.html':source==='sinyi'?'https://www.sinyi.com.tw/buy/house/2159AZ':'https://buy.yungching.com.tw/house/123'}))});});
await p.locator('#imTab-listings').click();assert((await p.locator('#imCount').innerText()).includes('1 組 / 4 筆'));
assert.equal(await p.locator('.im-group>.im-row a.source-yungching').count(),1);assert.equal(await p.locator('.im-group>.im-row a.source-sinyi').count(),1);assert.equal(await p.locator('.im-group-toggle').innerText(),'591（2 筆） ▾');await p.locator('.im-group-toggle').click();assert.equal(await p.locator('.im-group-list .im-row:visible').count(),2);assert(!(await p.locator('.im-group-list').innerText()).includes('永慶'));await p.locator('.im-group-toggle').click();
for(const width of [1440,1024,700]){await p.setViewportSize({width,height:1000});assert(await p.locator('.im-dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+2));assert(await p.locator('#imProperty').evaluate(e=>e.scrollWidth<=e.clientWidth+2));if(process.argv[2])await p.screenshot({path:process.argv[2]+'/sources-tabs-'+width+'.png'});}
await p.locator('[data-property]').nth(1).click();assert.equal(await p.locator('[name=priceMax]').inputValue(),'');await p.locator('[data-property]').first().click();assert.equal(await p.locator('[name=priceMax]').inputValue(),'999999999');
await p.reload();await p.evaluate(()=>InventoryMarket.open(InventoryMarket.entries()[0].key));assert.equal(await p.locator('[name=priceMax]').inputValue(),'999999999');assert((await p.locator('#imCount').innerText()).includes('1 組 / 4 筆'));
assert((await p.locator('#imResults').innerText()).includes('22–23樓'));assert(!(await p.locator('#imResults').innerText()).includes('樓層待確認'));assert((await p.locator('#imResults').innerText()).includes('部分刊登缺屋齡'));assert(!(await p.locator('#imResults').innerText()).includes('條件待確認'));assert.deepEqual(errors,[]);console.log('PASS owner-only tabs, independent saved criteria/reload, missing lane ingestion, source links/count expansion, long labels/title and large number at three widths');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
