const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST')return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');




await p.evaluate(()=>{DB=[{id:'purpose-test',name:'用途測試',phone:'0900000000',type:'庫存屋主',types:['庫存屋主'],sProperties:[{community:'長社區名稱'.repeat(12),addr:'新北市板橋區文化路一段100號',price:'99999999'},{community:'另一個物件',addr:'新北市板橋區文化路一段102號'}]}];persist();openEdit('purpose-test');pickType('庫存屋主');});
assert.equal(await p.locator('#sPropertyList [data-f=listingPurpose]').first().inputValue(),'');await p.locator('#sPropertyList [data-f=listingPurpose]').first().selectOption('住宅');await p.evaluate(()=>saveClient());await p.reload();assert.equal(await p.evaluate(()=>DB[0].sProperties[0].listingPurpose),'住宅');assert.equal(await p.evaluate(()=>DB[0].sProperties[1].listingPurpose),'');await p.evaluate(()=>{openEdit('purpose-test');pickType('庫存屋主');});assert.equal(await p.locator('#sPropertyList [data-f=listingPurpose]').first().inputValue(),'住宅');
for(const width of [1440,700]){await p.setViewportSize({width,height:1000});assert(await p.locator('.sp-listing-purpose').first().evaluate(e=>e.scrollWidth<=e.clientWidth+2));if(process.argv[2])await p.screenshot({path:process.argv[2]+'/inventory-purpose-'+width+'.png'});}await p.evaluate(()=>saveClient());await p.evaluate(()=>InventoryMarket.open(InventoryMarket.entries()[0].key));await p.locator('.im-config>summary').click();assert((await p.locator('[name=searchPurpose] option').first().textContent()).includes('依庫存（住宅）'));assert.equal(await p.evaluate(()=>InventoryMarket.demands(InventoryMarket.entries()[0].config)[0].matchCriteria.searchPurpose),'住宅');await p.locator('[name=searchPurpose]').selectOption('店面');await p.locator('[name=enabled]').check();await p.locator('#imSave').click();await p.waitForFunction(()=>document.querySelector('#imSaveNotice').dataset.state==='success');assert.equal(await p.evaluate(()=>DB[0].sProperties[0].listingPurpose),'住宅');assert.equal(await p.evaluate(()=>InventoryMarket.demands(InventoryMarket.entries()[0].config)[0].matchCriteria.searchPurpose),'店面');await p.reload();await p.evaluate(()=>InventoryMarket.open(InventoryMarket.entries()[0].key));assert.equal(await p.locator('[name=searchPurpose]').inputValue(),'店面');await p.locator('[data-property]').nth(1).click();assert.equal(await p.locator('[name=searchPurpose]').inputValue(),'');assert((await p.locator('#imPurposeHint').textContent()).includes('耗時較長'));assert.deepEqual(errors,[]);console.log('PASS inventory purpose save/reload/per-property isolation, inherited and overridden search purposes, long content widths');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
