const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{
const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
const image=JSON.parse(fs.readFileSync('01-crm/data/buyer-feed.json','utf8')).listings.find(x=>x.image).image;
await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.request().url().startsWith('https://yccdn.yungching.com.tw/')?r.fulfill({contentType:'image/jpeg',body:fs.readFileSync(process.argv[2]+'/sample-photo.jpg')}):r.abort());
await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);return r.fulfill({contentType:f.endsWith('.html')?'text/html; charset=utf-8':f.endsWith('.js')?'text/javascript; charset=utf-8':'text/css',body:fs.readFileSync(f)});});
await p.addInitScript(()=>window.addEventListener('message',e=>{if(e.data?.channel==='CRM_BUYER_REQUEST')window.postMessage({channel:'CRM_BUYER_RESPONSE',id:e.data.id,result:e.data.type==='hello'?{version:3,extensionVersion:'1.2.6'}:e.data.type==='sync'?{saved:e.data.payload.length}:{}},'*');}));await p.goto('http://localhost:43123/index.html');await p.evaluate(async image=>{DB=[{id:'group-test',name:'範例買方',type:'經營買方',types:['經營買方'],buyerMatching:{auto:true},bDemands:[{areaDisplay:'新北市板橋區',areaCities:['新北市'],areaDists:['板橋區']}]}];persist();await BuyerResults.ready(['group-test']);const base={city:'新北市',district:'板橋區',address:'新北市板橋區民權路202巷',area:23.23,floor:1,age:52,price:1988,rooms:3,image};BuyerResults.ingest(DB[0],{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:['民權路方正可停車一樓','板橋車站 前後增建一樓','近板橋車站 民權方正一樓','板橋車站 前有小庭院','稀有雙面臨路一樓・大降價','近板橋車站公寓一樓門口可停車'].map((title,i)=>({...base,id:'sample:'+i,source:['yungching','sinyi','591','591','591','sinyi'][i],title,floor:i===3?null:1,rooms:i===3?5:3,address:i===3?'新北市板橋區民權路':base.address,area:i===3?23.02:i<4?23.23:22.61,price:i<4?1988:i===4?1880:2099,image:i===4?'https://invalid.example/missing.jpg':i===5?'':image,url:'https://sale.591.com.tw/home/house/detail/2/'+i+'.html'}))});await BuyerResults.flush();BuyerMatching.open('group-test');},image);
await p.waitForSelector('.bm-property-group');await p.waitForTimeout(1200);
assert.equal(await p.locator('.bm-property-group').count(),1);assert((await p.locator('#bmCount').innerText()).includes('3 組符合需求／6 則廣告'));assert((await p.locator('.bm-group-heading').innerText()).includes('591 2 則'));
await p.getByRole('button',{name:'確認同一物件',exact:true}).click();assert((await p.locator('.bm-group-heading').innerText()).includes('已確認同一物件'));await p.getByRole('button',{name:'撤回同物件確認',exact:true}).click();
const expand=async()=>{if(!(await p.locator('.bm-variants').evaluate(e=>e.open)))await p.locator('.bm-variants>summary').click();};await expand();assert.equal(await p.locator('.bm-card:visible').count(),6);
const target=p.locator('[data-id="sample:3"]');await target.locator('[data-action=save]').click();await expand();await target.locator(':scope > .bm-row-main > [data-track=status]').selectOption('contacted');await expand();await target.locator('.bm-detail-button').click();await target.locator('textarea[data-track=reason]').fill('已聯絡，請確認屋主可看屋時間與完整地址。'.repeat(30));await target.locator('textarea[data-track=reason]').blur();await BuyerPause();
async function BuyerPause(){await p.waitForTimeout(100);}
assert.equal(await p.evaluate(()=>DB[0].buyerMatching.tracking['sample:3'].status),'contacted');
for(const width of [1440,1024]){await p.setViewportSize({width,height:1000});await expand();assert(await p.locator('#buyerMatchDialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await p.screenshot({path:process.argv[2]+'/market-buyers-'+width+'.png'});}
await p.reload();await p.evaluate(()=>BuyerMatching.open('group-test'));await p.waitForSelector('.bm-property-group');await p.locator('#bmFavorites').click();assert.equal(await p.locator('.bm-card').count(),1);assert.equal(await p.locator('[data-track=status]').inputValue(),'contacted');assert((await p.locator('textarea[data-track=reason]').inputValue()).length>100);
await p.locator('#bmView').selectOption('all');await p.getByRole('button',{name:'保持分開',exact:true}).click();assert.equal(await p.locator('.bm-property-group').count(),0);await p.reload();await p.evaluate(()=>BuyerMatching.open('group-test'));await p.waitForSelector('.bm-reset-group');assert.equal(await p.locator('.bm-property-group').count(),0);while(await p.locator('.bm-reset-group').count())await p.locator('.bm-reset-group').first().click();assert.equal(await p.locator('.bm-property-group').count(),1);
await p.locator('#bmAcknowledge').click();assert.equal(await p.locator('.bm-change-new').count(),0);await p.evaluate(()=>BuyerMatching.open('group-test',false,{view:'changes'}));assert((await p.locator('#bmResults').innerText()).includes('目前沒有未讀變化'));
await p.locator('#bmView').selectOption('all');await p.locator('.bm-card').first().evaluate(e=>{e.querySelector('h3').textContent='長社區名稱與物件說明'.repeat(25);e.querySelector('.bm-address').textContent='新北市板橋區文化路一段長地址'.repeat(20);e.querySelector('.bm-price').textContent='99,999,999 萬';});for(const width of [1440,1024]){await p.setViewportSize({width,height:1000});assert(await p.locator('.bm-card').first().evaluate(e=>e.scrollWidth<=e.clientWidth+1));assert(await p.locator('h3').first().evaluate(e=>e.scrollHeight<=e.clientHeight+1));await p.screenshot({path:process.argv[2]+'/market-buyers-long-'+width+'.png'});}
assert.deepEqual(errors,[]);console.log('PASS buyer grouping, confirmation, split/restore, per-ad save/contact/memo/reload, all-read, report view, photos and long layout');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});