const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST')return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='buyerVerify'?{checks:payload.rows.map(p=>({id:p.id,...(['yungching:7417941','591:20734577'].includes(p.id)?{usage:'住家用',usageEvidence:'法定用途',availability:'available'}:{})}))}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');






await p.evaluate(async()=>{DB=[{id:'group-test',name:'長姓名測試',types:['庫存屋主'],sProperties:[{addr:'新北市土城區莊園街100號',community:'世界花園',listingPurpose:'住宅'}]}];const e=InventoryMarket.entries()[0];e.c.inventoryWatch={[e.slot]:{...e.config,id:'group-watch',enabled:true,transactionsEnabled:true}};persist();InventoryMarket.open();await InventoryMarket.updateState('group-watch',()=>{const old=new Date(Date.now()-86400000).toISOString(),now=new Date().toISOString();const base={source:'591',title:'世界花園精美兩房',community:'世界花園',address:'新北市土城區莊園街100號',city:'新北市',district:'土城區',price:1598,area:24.1,floor:6,age:1,rooms:2,usage:'住家用',seenAt:now};return {records:{a:{...base,id:'a',availability:'active',url:'https://sale.591.com.tw/home/house/detail/2/123.html'},b:{...base,id:'b',title:'世界花園兩房新廣告',availability:'off',offConfirmedAt:now},c:{...base,id:'c',availability:'off',offConfirmedAt:old},t:{id:'t',source:'moi',kind:'transaction',title:'成交資料',community:'世界花園',address:base.address,tradeDate:'2026-08-01',floorText:'六層',price:1580,area:24.1,parkingPrice:200,parkingArea:4,notes:'長備註'.repeat(40)}},events:[{id:'new-off',listingId:'b',kind:'其中一筆已下架',at:now}],ackListings:Date.now()-3600000,sourceStatus:{'591':{status:'ok'}},baselines:{}};});});
await p.locator('#imTab-listings').click();await p.locator('button[data-inventory-view=expired]').click();
assert.equal(await p.locator('.im-expired-panel .market-property').count(),1);assert((await p.locator('#imCount').innerText()).includes('1 組物件／2 則下架廣告'));assert((await p.locator('.im-expired-panel').innerText()).includes('部分廣告下架'));assert((await p.locator('.im-expired-panel').innerText()).includes('本次新下架 1 則'));
await p.locator('.im-expired-panel .market-records>summary').click();assert.equal(await p.locator('.im-expired-panel .market-record').count(),3);
await p.locator('.im-expired-panel [data-group-decision=confirm]').click();assert((await p.locator('.im-expired-panel .market-property-head').innerText()).includes('已確認同一物件'));
await p.locator('.im-expired-panel [data-group-decision=undo]').click();await p.locator('.im-expired-panel [data-group-decision=separate]').click();assert.equal(await p.locator('.im-expired-panel .market-property').count(),2);
for(const b of await p.locator('.im-expired-panel [data-group-decision=restore]').all()){await b.click().catch(()=>{});break;}
await p.evaluate(()=>{const e=InventoryMarket.entries()[0];e.c.inventoryWatch[e.slot].separateListings=[];persist();});await p.locator('#imTab-listings').click();await p.locator('button[data-inventory-view=expired]').click();
for(const width of [1440,1024,780]){await p.setViewportSize({width,height:1000});await p.locator('.im-expired-panel .market-records>summary').click();assert(await p.locator('#imResults').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await p.screenshot({path:path.join(process.env.TEMP,'market-groups-'+width+'.png')});}
await p.locator('#imTab-changes').click();assert((await p.locator('#imResults').innerText()).includes('新下架'));
await p.evaluate(async()=>{await InventoryMarket.updateState('group-watch',s=>{s.events.push({id:'trade-new',listingId:'t',kind:'成交',at:new Date().toISOString()});s.records.bad={...s.records.a,id:'bad',price:999999};const e=InventoryMarket.entries()[0];e.c.inventoryWatch[e.slot].criteria={priceMax:2000};persist();return s;});});await p.locator('#imTab-changes').click();assert.equal(await p.locator('.market-trade-row').count(),1);await p.locator('#imTab-listings').click();assert(!(await p.locator('#imResults>.market-property').innerText()).includes('999,999'));
await p.locator('button[data-inventory-view=expired]').click();await p.locator('#imRead').click();await p.waitForFunction(()=>!document.querySelector('.im-expired-panel .market-fresh'));assert.equal(await p.locator('.im-expired-panel .market-fresh').count(),0);
await p.locator('#imTab-transactions').click();assert.equal(await p.locator('.market-trade-row').count(),1);assert((await p.locator('.market-trade-row').innerText()).includes('200 萬'));await p.locator('.market-trade-row summary').click();for(const width of [1440,1024,780]){await p.setViewportSize({width,height:1000});assert(await p.locator('.market-trade-row').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await p.screenshot({path:path.join(process.env.TEMP,'market-trades-'+width+'.png')});}
await p.evaluate(async()=>{const e=InventoryMarket.entries()[0];e.c.inventoryWatch[e.slot].searchPurpose='住宅';persist();await InventoryMarket.updateState('group-watch',s=>{s.records.pending={...s.records.a,id:'pending',title:'用途待確認測試',price:1800,usage:null};return s;});});await p.locator('#imTab-listings').click();await p.locator('button[data-inventory-view=purpose]').click();await p.locator('[data-purpose=pending]').click();await p.locator('.im-confirm [data-confirm]').click();await p.waitForFunction(()=>document.querySelector('[data-purpose=pending]')?.textContent.includes('用途已確認'));await p.locator('button[data-inventory-view=active]').click();await p.locator('.market-property').filter({has:p.locator('[data-purpose=pending]')}).locator('.market-records>summary').click();await p.locator('[data-purpose=pending]').click();await p.locator('.im-confirm [data-confirm]').click();await p.waitForFunction(()=>!!document.querySelector('.im-purpose-panel [data-purpose=pending]'));
await p.evaluate(async()=>{await InventoryMarket.updateState('group-watch',s=>{for(const id of ['a','b','c']){s.records[id].community='世界花園長社區名稱'.repeat(20);s.records[id].address+='（長地址說明'.repeat(30)+'）';}s.records.t.notes='車位及特殊交易長備註'.repeat(100);s.records.t.price=99999999;s.records.t.area=99999;return s;});});await p.locator('#imTab-transactions').click();await p.locator('.market-trade-row summary').click();assert((await p.locator('.market-trade-row').innerText()).includes('99,999,999'));assert(await p.locator('.market-trade-row').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await p.screenshot({path:path.join(process.env.TEMP,'market-trades-long.png')});await p.locator('#imTab-listings').click();await p.locator('button[data-inventory-view=expired]').click();assert(await p.locator('.market-property').first().evaluate(e=>e.scrollWidth<=e.clientWidth+2));await p.screenshot({path:path.join(process.env.TEMP,'market-groups-long.png')});
await p.reload();await p.evaluate(()=>InventoryMarket.open());await p.waitForSelector('.market-property');assert.deepEqual(errors,[]);console.log('PASS mixed active/off grouping, counts, confirm/undo/split, histories, read state, trades, reload and widths');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
