const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST')return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');

const evidence=[];
await p.evaluate(async()=>{DB=[{id:'adversarial',name:'跨流程測試屋主',phone:'0900000000',types:['庫存屋主'],type:'庫存屋主',sProperties:[{community:'原社區',addr:'台北市內湖區民權東路六段136巷26號',listingPurpose:'住宅'}]}];const e=InventoryMarket.entries()[0];e.c.inventoryWatch={[e.slot]:{...e.config,id:'original-watch',enabled:true,transactionsEnabled:true}};persist();openEdit('adversarial');pickType('庫存屋主');});
await p.locator('#sPropertyList [data-f=listingPurpose]').first().selectOption('店面');await p.evaluate(()=>saveClient());await p.waitForTimeout(400);let entry=await p.evaluate(()=>InventoryMarket.entries()[0]);evidence.push({case:'inherit-purpose-revision',expected:true,actual:entry.config.id!=='original-watch'});
await p.evaluate(()=>{openEdit('adversarial');pickType('庫存屋主');});await p.locator('#sPropertyList [data-f=community]').first().fill('更正社區名稱');await p.evaluate(()=>saveClient());await p.waitForTimeout(400);entry=await p.evaluate(()=>InventoryMarket.entries()[0]);evidence.push({case:'rename-preserves-enabled',expected:true,actual:!!entry.config.enabled});
await p.evaluate(async()=>{DB.push({id:'legacy-buyer',name:'舊格式買方',types:['經營買方'],areaCity:'臺北市',areaDists:['中正區'],budgetMax:'2000'});persist();await BuyerMatching.setAutomatic('legacy-buyer',true);});const sent=await p.evaluate(()=>invCalls.filter(x=>x.type==='sync').at(-1).payload.find(x=>x.id==='legacy-buyer').demands[0]);evidence.push({case:'buyer-sent-city-preserved',expected:'台北市',actual:sent.areaCities?.[0]||''});
await p.evaluate(()=>{const c=DB.find(x=>x.id==='adversarial');c.sProperties.push({community:'第二間',addr:'台北市內湖區成功路一段88號',listingPurpose:'住宅',price:'2000'});c.sProperties[0].price='3000';persist();openEdit(c.id);pickType('庫存屋主');});await p.evaluate(()=>{const list=document.querySelector('#sPropertyList'),blocks=list.querySelectorAll('.person-block');list.insertBefore(blocks[1],blocks[0]);saveClient();});await p.waitForTimeout(400);const order=await p.evaluate(()=>DB.find(x=>x.id==='adversarial').sProperties);evidence.push({case:'reorder-no-false-price-history',expected:true,actual:order.every(x=>!(x.spPriceHistory||[]).length)});
await p.reload();evidence.push({case:'reload-tracking-survives',expected:true,actual:await p.evaluate(()=>InventoryMarket.entries().some(e=>e.config.enabled&&e.p.community==='更正社區名稱'))});
await p.evaluate(async()=>{const e=InventoryMarket.entries().find(x=>x.config.enabled),p={id:'591:unsafe',source:'591',city:'台北市',district:'內湖區',address:e.config.address,price:1000,floor:1,type:'店面',title:'<img src=x onerror="window.__auditXSS=1">店面',url:'javascript:window.__auditXSS=1',image:'javascript:window.__auditXSS=1'};await InventoryMarket.updateState(e.config.id,()=>({records:{[p.id]:p},events:[],baselines:{}}));InventoryMarket.open(e.key);});await p.waitForSelector('.im-row');evidence.push({case:'inventory-untrusted-title-and-url-inert',expected:true,actual:await p.evaluate(()=>!window.__auditXSS&&!document.querySelector('.im-row a[href^="javascript:"]')&&!document.querySelector('.im-row img[src="x"]')&&document.querySelector('.im-row').textContent.includes('<img src=x'))});await p.locator('#imClose').click();
await p.evaluate(async()=>{const c=DB.find(x=>x.id==='legacy-buyer');await BuyerResults.ready([c.id]);BuyerResults.ingest(c,{generatedAt:new Date().toISOString(),sources:[{id:'591',status:'ok'}],listings:[{id:'591:unsafe',source:'591',city:'台北市',district:'中正區',price:1000,title:'<img src=x onerror="window.__auditXSS=1">測試',url:'javascript:window.__auditXSS=1'}]});await BuyerResults.flush();BuyerMatching.open(c.id);});await p.waitForSelector('[data-id="591:unsafe"]');evidence.push({case:'buyer-untrusted-title-and-url-inert',expected:true,actual:await p.evaluate(()=>!window.__auditXSS&&!document.querySelector('[data-id="591:unsafe"] a[href^="javascript:"]')&&!document.querySelector('[data-id="591:unsafe"] img[src="x"]')&&document.querySelector('[data-id="591:unsafe"]').textContent.includes('<img src=x'))});
console.log(JSON.stringify(evidence,null,2));assert(evidence.every(x=>x.actual===x.expected));assert.deepEqual(errors,[]);
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
