const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');const{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1707,height:920}});await p.route('https://**/*',r=>r.abort());await p.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);
await p.evaluate(()=>{DB=[{id:'owner',name:'測試',phone:'0900000000',type:'房東',types:['房東'],rProperties:[{rCommunity:'分租物件',rSz:'8.74',rParking:'坡道平面',rParkingNo:'8',rent:'10000'}]},{id:'tenant',name:'租客',linkedLandlordId:'owner',linkedPropertyIdx:0}];window.persist=()=>true;window.render=()=>{};openEdit('owner');});
await p.locator('#rPropertyList .purpose-button').click();assert(await p.locator('.purpose-keep input').isDisabled());await p.locator('.purpose-target').selectOption('s');await p.locator('.purpose-cancel').click();await p.waitForSelector('.purpose-dialog',{state:'detached'});assert.equal(await p.locator('#sPropertyList>.person-block').count(),0);
await p.locator('#rPropertyList .purpose-button').click();await p.locator('.purpose-target').selectOption('s');await p.locator('.purpose-confirm').click();await p.waitForSelector('.purpose-dialog',{state:'detached'});assert.equal(await p.locator('#rPropertyList>.person-block').count(),1);const copied=await p.evaluate(()=>getSellerProperties()[0]);assert.equal(copied.mainBldg,'','rental usable area must not become main building');assert.equal(copied.parking,'坡道平面');assert(copied.conversionEstimate.includes('8.74'));
await p.evaluate(()=>pickType('房東'));await p.locator('#rPropertyList .purpose-button').click();await p.locator('.purpose-target').selectOption('s');await p.locator('.purpose-confirm').click();assert((await p.locator('.purpose-warning').innerText()).includes('已在'));assert.equal(await p.locator('#sPropertyList>.person-block').count(),1);await p.locator('.purpose-cancel').click();await p.waitForSelector('.purpose-dialog',{state:'detached'});
await p.locator('#rPropertyList .purpose-area>summary').click();assert.equal(await p.locator('#rPropertyList .transcript-toolbar').count(),1);await p.locator('#rPropertyList input[aria-label="主建物"]').fill('100');const draft=await p.evaluate(()=>getRentalProperties()[0]);assert.equal(draft.rSz,'8.74');assert.equal(Number(draft.registeredArea.mainBldg),30.25);await p.locator('#rPropertyList .purpose-area').screenshot({path:require('node:os').tmpdir()+'/crm-purpose-area.png'});
await p.locator('#rPropertyList input[aria-label="主建物"]').fill('-2');await p.locator('#rPropertyList .purpose-button').click();await p.locator('.purpose-target').selectOption('d');await p.locator('.purpose-confirm').click();assert((await p.locator('.purpose-warning').innerText()).includes('修正'));assert.equal(await p.locator('#dAddrList>.person-block').count(),0);await p.keyboard.press('Escape');await p.waitForSelector('.purpose-dialog',{state:'detached'});assert(await p.locator('#fModal').isVisible());await p.locator('#rPropertyList input[aria-label="主建物"]').fill('100');await p.evaluate(()=>saveClient());await p.waitForTimeout(80);assert.equal(await p.evaluate(()=>DB[1].linkedPropertyIdx),0);assert.equal(await p.evaluate(()=>DB[0].rProperties[0].rCommunity),'分租物件');const detail=await p.evaluate(()=>typeDetail({...DB[0],type:'房東'}));assert(detail.includes('主建物'));assert(detail.includes('30.25'));
console.log('PASS cancel, duplicate protection, rental/registered area separation, parking without area, linked tenants, area input, invalid-area blocking, detail display and Escape');await p.close();}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
