const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');const{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{for(const width of [1707,390]){const p=await b.newPage({viewport:{width,height:920}});await p.route('https://**/*',r=>r.abort());await p.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);const errors=[];p.on('pageerror',e=>errors.push(e.message));
const config={s:['sPropertyList','sProperties','庫存屋主'],r:['rPropertyList','rProperties','房東'],d:['dAddrList','dAddrs','商機募集']};
for(const from of ['s','r','d'])for(const to of ['s','r','d'].filter(k=>k!==from)){
 await p.evaluate(({from})=>{const area={version:3,main:{area:'100',unit:'sqm'},ancillary:{area:'10',unit:'sqm'},parking:{area:'',unit:'sqm'},extraBuildings:[],parkingIncluded:false,land:[{id:'L',area:'1000',unit:'sqm',mode:'fraction',numerator:'1',denominator:'10'}],common:[{id:'C',kind:'common',area:'200',unit:'sqm',mode:'fraction',numerator:'1',denominator:'10'},{id:'P',kind:'parking',area:'100',unit:'sqm',mode:'fraction',numerator:'1',denominator:'10',parking:'坡道平面',parkingNo:'B2-7',parkingPrice:'200'}]};const reg={areaInput:area,mainBldg:'30.25',ancBldg:'3.025',common:'6.05',parkingSz:'3.025',baseLand:'302.5',landShare:'30.25',parking:'坡道平面',parkingNo:'B2-7',parkingPrice:'200'};const a={s:{community:'測試物件',addr:'測試路1號',price:'1800',contractStart:'2026-01-01',spPriceHistory:[{price:'1900'}],spDriveUrl:'https://drive.google.com/drive/folders/test',...reg},r:{rCommunity:'測試物件',rAddr:'測試路1號',rent:'23000',rSz:'8.74',rConditions:{rPet:true},rStartDate:'2026-01-01',rpRenewals:[{oldEnd:'2026-01-01'}],rParking:'坡道平面',rParkingNo:'B2-7',registeredArea:reg,rpDriveUrl:'https://drive.google.com/drive/folders/test'},d:{community:'測試物件',addr:'測試路1號',devType:'出售',houseType:'公寓',registeredArea:reg,dAddrDriveUrl:'https://drive.google.com/drive/folders/test'}};const keys={s:'sProperties',r:'rProperties',d:'dAddrs'},types={s:'庫存屋主',r:'房東',d:'商機募集'};DB=[{id:'test',name:'測試',phone:'0900000000',type:types[from],types:[types[from]],[keys[from]]:[a[from],{...a[from],community:'另一物件',rCommunity:'另一物件'}]}];window.originalDB=JSON.stringify(DB);window.persist=()=>true;window.render=()=>{};openEdit('test');}, {from});
 await p.evaluate(t=>pickType(t),config[from][2]);await p.locator('#'+config[from][0]+' >.person-block:not([hidden]) .purpose-button').click();await p.locator('.purpose-target').selectOption(to);await p.locator('.purpose-keep input').uncheck();await p.locator('.purpose-confirm').click();await p.waitForSelector('.purpose-dialog',{state:'detached'});assert.equal(await p.locator('#'+config[from][0]+' >.person-block').count(),1);assert.equal(await p.locator('#'+config[to][0]+' >.person-block').count(),1);assert(await p.evaluate(()=>JSON.stringify(DB)===originalDB),'draft conversion must not mutate DB');
 await p.evaluate(()=>saveClient());await p.waitForTimeout(80);let saved=await p.evaluate(key=>DB[0][key][0],config[to][1]);assert(saved.purposeHistory[from]);assert.equal(saved[to==='s'?'spDriveUrl':to==='r'?'rpDriveUrl':'dAddrDriveUrl'],'https://drive.google.com/drive/folders/test');assert(Math.abs(Number((to==='s'?saved:saved.registeredArea).mainBldg)-30.25)<.001);assert.equal(saved.purposeHistory[from][from==='r'?'rent':from==='s'?'price':'houseType'],from==='r'?'23000':from==='s'?'1800':'公寓');
 await p.evaluate(({type})=>{openEdit('test');pickType(type);},{type:config[to][2]});await p.locator('#'+config[to][0]+' >.person-block:not([hidden]) .purpose-button').click();await p.locator('.purpose-target').selectOption(from);await p.locator('.purpose-keep input').uncheck();await p.locator('.purpose-confirm').click();await p.waitForSelector('.purpose-dialog',{state:'detached'});await p.evaluate(()=>saveClient());await p.waitForTimeout(80);saved=await p.evaluate(key=>DB[0][key].find(x=>(x.community||x.rCommunity)==='測試物件'),config[from][1]);assert.equal(saved[from==='r'?'rent':from==='s'?'price':'houseType'],from==='r'?'23000':from==='s'?'1800':'公寓');if(from==='r'){assert.equal(saved.rSz,'8.74');assert(saved.rConditions.rPet);assert.equal(saved.rpRenewals.length,1);}if(from==='s')assert.equal(saved.spPriceHistory.length,1);
 console.log('PASS '+width+' '+from+' → '+to+' → '+from+' with save/reopen, area, folder, histories and sibling preservation');
}
await p.evaluate(()=>{openEdit('test');pickType('房東');addRentalProperty({rCommunity:'截圖測試',rSz:'8.74'});});await p.waitForTimeout(80);await p.locator('#fModal>.modal').screenshot({path:require('node:os').tmpdir()+'/crm-purpose-'+width+'.png'});assert.deepEqual(errors,[]);await p.close();}}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
