const assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE),{pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{for(const width of [1707,1100,390,320]){
const page=await browser.newPage({viewport:{width,height:900}});await page.route('https://**/*',r=>r.abort());await page.goto(pathToFileURL(path.resolve('01-crm/index.html')).href);
await page.evaluate(()=>{window.persist=()=>true;window.persistAndSyncNow=()=>true;const date=new Date();date.setDate(date.getDate()-3);const iso=date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0');DB=[{id:'head',name:'鄭勝元',type:'成交客戶',types:['成交客戶'],schedules:[{id:'s',date:iso,time:'11:00',memo:'服務費匯款',schedType:'成交客戶',propertyRef:{clientId:'head',type:'成交客戶',propertyKey:'p',label:'NY璞緻',address:'測試地址'}}]}];render();});
const tag=page.locator('#dashSchedule .dash-sched-row1 .schedule-property-tag');assert.equal(await tag.innerText(),'成交・NY璞緻');assert.equal(await page.locator('#dashSchedule .dash-sched-memo .schedule-property-tag').count(),0);const circle=page.locator('#dashSchedule .schedule-overdue-days');assert.equal(await circle.innerText(),'3');assert.equal(await circle.getAttribute('aria-label'),'已逾期 3 天');
const bad=await page.locator('#dashSchedule .dash-sched-item').evaluate(el=>{const r=el.getBoundingClientRect();return [...el.querySelectorAll('button,.schedule-overdue-days')].filter(x=>{const b=x.getBoundingClientRect();return b.right>r.right+1||b.left<r.left-1}).length;});assert.equal(bad,0,'heading controls fit '+width);
assert.equal(await page.locator('#dashSchedule .schedule-overdue-alert').count(),1);
await page.evaluate(()=>{const first=DB[0].schedules[0];first.time='';first.date='2026-10-01';DB[0].schedules.push({...first,id:'second',date:'2026-09-29'});renderDashboard();});
const circles=await page.locator('#dashSchedule .schedule-overdue-days').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect();return {x:r.x,center:r.y+r.height/2,rowCenter:el.parentElement.getBoundingClientRect().y+el.parentElement.getBoundingClientRect().height/2};}));
assert.equal(circles.length,2);assert(Math.abs(circles[0].x-circles[1].x)<1,'circle columns align for different date lengths');assert(circles.every(c=>Math.abs(c.center-c.rowCenter)<1),'circles vertically centered');
await page.screenshot({path:path.join(require('node:os').tmpdir(),'crm-heading-'+width+'.png')});await page.close();console.log('PASS '+width+' heading, overdue warning and circle alignment');
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
