const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync(process.env.CRM_TEST_HTML || require('node:path').join(__dirname,'../index.html'),'utf8');const src=html.slice(html.indexOf('function _crmMarkPending()'),html.indexOf('\nstartAutoCheck();'));
function setup(db=[],storage=new Map()){const scripts=[],timers=[],status={textContent:'',innerHTML:''};const body={appendChild(s){s.parentNode=body;scripts.push(s)},removeChild(s){s.parentNode=null}};
 const c={DB:db,console,JSON,Date,URLSearchParams,Blob,navigator:{onLine:true},CLOUD_URL:'https://example.test/cloud',localStorage:{setItem:(k,v)=>storage.set(k,v),getItem:k=>storage.get(k)||null,removeItem:k=>storage.delete(k)},document:{hidden:false,body,createElement:()=>({remove(){this.parentNode=null}}),getElementById:()=>status,addEventListener(){}},setTimeout:(fn,ms)=>{timers.push({fn,ms});return timers.length},clearTimeout(){},setInterval(){},clearInterval(){},showToast(){},render(){},migrateDB(){},mergeCheckIn(){},getCheckInData:()=>({}),_perfRecords:[],_perfLoaded:true,_templates:[],_signingTemplates:[],_otherTemplates:[],_otplLoaded:true,_syncTimer:null};c.alert=()=>{};c.window=c;c.addEventListener=()=>{};c.fetch=async()=>{};vm.createContext(c);vm.runInContext(src,c);
 return {c,storage,scripts,timers,status,reply(data){const script=scripts.at(-1),name=new URL(script.src).searchParams.get('callback');c[name](data)}};
}

function install(c,name){const start=html.indexOf('function '+name+'()'),end=name==='_setDirty'?html.indexOf('\n',start):html.indexOf('\n}',start)+2;vm.runInContext(html.slice(start,end),c);}
function installSave(e){for(const n of ['_stampUpdatedAt','_setDirty','persist','persistAndSyncNow'])install(e.c,n);e.c._lastSyncJSON=JSON.stringify(e.c.DB);e.c._safeSetItem=(k,v)=>{e.storage.set(k,v);return true;};}
const row=()=>({id:'client',name:'測試客戶',updatedAt:'2026-09-01',schedules:[]});
const item=id=>({id,date:'2026-09-28',time:'10:00',memo:id,updatedAt:'2026-09-27T01:00:00Z'});
test('client save durably queues upload before delayed timer and survives restart',()=>{const e=setup([row()]);installSave(e);e.c.DB[0].schedules.push(item('phone'));e.c.persist();assert(e.c._crmHasPending());assert(e.timers.some(t=>t.ms===3000));const reopened=setup(JSON.parse(e.storage.get('reCRM')),e.storage);let uploads=0;reopened.c.autoSync=()=>uploads++;reopened.c.startAutoCheck();reopened.timers.find(t=>t.ms===2000).fn();assert.equal(uploads,1);});
test('immediate save while another upload runs retains pending flag',()=>{const e=setup([row()]);installSave(e);e.c._syncInFlight=true;e.c.DB[0].schedules.push(item('phone'));e.c.persistAndSyncNow();assert(e.c._crmHasPending());assert.equal(e.scripts.length,0);});
test('old stranded phone schedule is recovered and merged with desktop schedule',()=>{const local=row();local.schedules=[item('phone')];const e=setup([local]);const remote=row();remote.schedules=[item('desktop')];e.c.autoFetchCloud(true);e.reply([remote]);assert.deepEqual(Array.from(e.c.DB[0].schedules,x=>x.id).sort(),['desktop','phone']);assert(e.c._crmHasPending());assert(e.timers.some(t=>t.ms===500));assert.match(e.status.textContent,/待上傳/);});
test('download-only schedule does not trigger unnecessary upload',()=>{const e=setup([row()]);const remote=row();remote.schedules=[item('desktop')];e.c.autoFetchCloud(true);e.reply([remote]);assert.equal(e.c._crmHasPending(),false);});
test('two isolated devices retain both client schedules through upload and download',()=>{const phone=setup([row()]),desktop=setup([row()]);installSave(phone);phone.c.DB[0].schedules.push(item('phone'));phone.c.persistAndSyncNow();const cloud=row();cloud.schedules=[item('desktop')];phone.reply([cloud]);const uploaded=structuredClone(phone.c._expectedCloudData);assert.equal(uploaded.find(x=>x.id==='client').schedules.length,2);phone.c.verifySyncResult(phone.status);phone.reply(uploaded);assert(!phone.c._crmHasPending());desktop.c.autoFetchCloud(true);desktop.reply(uploaded);assert.deepEqual(Array.from(desktop.c.DB[0].schedules,x=>x.id).sort(),['desktop','phone']);assert(!desktop.c._crmHasPending());});
test('failed local save does not queue nonexistent data',()=>{const e=setup([row()]);installSave(e);e.c._safeSetItem=()=>false;assert.equal(e.c.persistAndSyncNow(),false);assert(!e.c._crmHasPending());});
