const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{
for(const width of [1440,1024]){
 const p=await browser.newPage({viewport:{width,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('https://**/*',r=>r.abort());await p.route('http://localhost:43123/**',r=>{const name=new URL(r.request().url()).pathname;if(name.endsWith('buyer-feed.json'))return r.fulfill({json:{schema:1,sources:[],listings:[]}});const f=path.resolve('01-crm','.'+name);return r.fulfill({contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css',body:fs.readFileSync(f)});});
 await p.addInitScript(()=>window.addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST')return;const {id,type,payload}=e.data;(window.helperCalls||=[]).push(type);let result={};if(type==='hello')result={version:3,extensionVersion:'1.2.19'};if(type==='sync')result={saved:payload.length};if(type==='progress')result={job:null};if(type==='buyerVerify'){window.verifyCalls=(window.verifyCalls||0)+1;result={checks:payload.rows.map(p=>({id:p.id,detailCheckedAt:new Date(Date.now()+1000).toISOString(),...(p.id==='591:2'?{availability:'unavailable',availabilityReason:'HTTP 404'}:{})}))};}window.postMessage({channel:'CRM_BUYER_RESPONSE',id,result},'*');}));await p.goto('http://localhost:43123/index.html');await p.evaluate(()=>{DB=[{id:'confirmation',name:'買方長姓名測試',types:['經營買方'],bDemands:[{areaCities:['新北市'],matchCriteria:{searchPurpose:'住宅',ageMax:10}}],buyerMatching:{auto:true}}];persist();BuyerMatching.open('confirmation');});
 await p.waitForFunction(()=>document.querySelector('#bmStatus').textContent.includes('最後取得'));
 const samples=require('./source-audit-parsed.json');await p.evaluate(samples=>{BuyerResults.ingest(DB[0],{schema:1,includeExcluded:true,generatedAt:new Date().toISOString(),sources:['591','sinyi','yungching'].map(id=>({id,status:'ok'})),listings:samples});},samples);await p.evaluate(()=>BuyerResults.flush());await p.reload();await p.waitForFunction(()=>typeof BuyerResults!=='undefined');await p.evaluate(()=>BuyerResults.ready(['confirmation']));const saved=await p.evaluate(()=>BuyerResults.rows(DB.find(c=>c.id==='confirmation')));for(const sample of samples){const row=saved.find(p=>p.id===sample.id);assert(row);for(const k of ['mainArea','parking','parkingType','totalFloors','floorText','usage','sinyiDetails','details591','yungchingDetails'])if(k in sample)assert.deepEqual(row[k],sample[k],sample.id+' '+k);}console.log('PASS all seven source detail records save and reload',width);
 assert.deepEqual(errors,[]);await p.close();
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});