const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),B=require('../buyer-match-engine.js'),I=require('../inventory-market-engine.js');const c=vm.createContext({});for(const p of ['read.js','read591.js'])vm.runInContext(fs.readFileSync('01-crm/tools/buyer-browser/'+p,'utf8'),c);const samples=require('./source-audit-samples.json');let checked=0;
for(const x of samples){let p;if(x.source==='591'){p={source:x.source,...c.crmRead591API(x,x.id)};assert(p.mainArea>0);assert.equal(p.parking,true);assert.match(p.parkingType,/平面/);assert(p.totalFloors>0);assert.equal(p.rooms,x.ware.room);assert.equal(p.halls,x.ware.hall);assert.equal(p.bathrooms,x.ware.toilet);assert.equal(B.evaluate({matchCriteria:{parking:'flat'}},p).status,'matched');if(x.id==='20743268'){assert.equal(B.normalizeListing(p).age,8/12);assert.equal(B.evaluate({matchCriteria:{searchPurpose:'住宅',ageMax:10,areaBasis:'main',areaMin:20,parking:'flat',exclude:['presale']}},p).status,'matched');}if(x.id==='20970884')assert.equal(B.evaluate({matchCriteria:{searchPurpose:'住宅'}},p).status,'excluded');if(x.id==='20779075')assert.equal(B.evaluate({matchCriteria:{exclude:['presale']}},p).status,'excluded');}
else if(x.source==='sinyi'){p=c.crmReadSinyiDetail({querySelector:()=>({textContent:JSON.stringify({props:{initialReduxState:{buyReducer:{detailData:{houseNo:x.id,detail:x.detail},contentData:x.content}}}})})},x.id);assert.equal(p.mainArea,x.id==='1215MT'?19.34:21.6);assert.equal(B.evaluate({matchCriteria:{parking:'flat'}},p).status,x.id==='5134LW'?'excluded':'matched');assert.equal(B.evaluate({matchCriteria:{parking:'yes'}},p).status,'matched');}
else{const items=x.fields.map(f=>({querySelector:q=>({textContent:q==='.item-title'?f.label:q==='.item-detail > div'?f.value.match(/坡道平面|塔式|機械/)?.[0]||'':f.value})}));p=c.crmReadYCDetail({querySelectorAll:()=>items,querySelector:q=>q==='.case-type'?{textContent:'住宅大樓'}:null});assert.equal(p.mainArea,x.id==='7139820'?17.93:20.03);assert.equal(B.evaluate({matchCriteria:{areaBasis:'main',areaMin:20}},p).status,x.id==='7139820'?'excluded':'matched');assert.equal(p.usage,'集合住宅');}if(x.source==='591'){for(const f of Object.values(x.info).flatMap(g=>Object.values(g)))if(f?.name&&typeof f.value==='string')assert.equal(p.details591.fields[f.name],f.value);assert.deepEqual(JSON.parse(JSON.stringify(p.details591.areas)),x.areaTips);}if(x.source==='yungching')for(const f of x.fields)if(f.label&&f.value)assert.equal(p.yungchingDetails.fields[f.label],f.value);if(x.source==='sinyi')for(const [k,v]of Object.entries(x.content))if(!['building','features','neighborhood'].includes(k))assert.deepEqual(JSON.parse(JSON.stringify(p.sinyiDetails[k])),v);checked++;}
assert.equal(B.evaluate({matchCriteria:{parking:'flat'}},{parking:true,parkingType:'1'}).status,'pending');assert.equal(I.assess({criteria:{ageMax:1}},{age:null,ageText:'8個月'}).missing.length,0);assert.equal(B.normalizeListing({age:null,ageText:'5年'}).age,5);console.log('PASS',checked,'source fixtures plus unknown parking codes, inventory month age, year detail backfill');

for(const [code,type] of Object.entries({A:'公寓',B:'電梯大樓',C:'套房',D:'透天',L:'電梯大樓',M:'華廈',N:'透天'}))assert.equal(c.crmSinyiBuildingType([code]),type);for(const codes of [[],['?'],['A','L']])assert.equal(c.crmSinyiBuildingType(codes),'');
assert.equal(B.normalizeListing({source:'yungching',mainArea:20.06}).mainArea,null);assert.equal(B.normalizeListing({source:'yungching',mainArea:17.93,mainAreaEvidence:'永慶主建物'}).mainArea,17.93);assert.equal(B.normalizeListing({source:'yungching',mainArea:20.06,yungchingDetails:{fields:{'・主建物':'17.93坪'}}}).mainArea,17.93);
for(const [label,main,balcony]of [['主15.79',15.79,null],['主建物27.95',27.95,null],['主+陽20.06',null,20.06]]){const card={checkVisibility:()=>true,textContent:'',querySelector:q=>q==='a[href*="house/"]'?{href:'https://buy.yungching.com.tw/house/1'}:{textContent:q==='.mainArea'?label:q==='.caseName'?'測試':q==='.price'?'1000':q==='.address'?'新北市板橋區文化路':''}};c.document={querySelectorAll:()=>[card]};const p=c.crmReadListings('yungching','新北市')[0];assert.equal(p.mainArea,main);assert.equal(p.mainAndBalconyArea,balcony);assert.equal(B.normalizeListing(p).mainArea,main);}
console.log('PASS Sinyi building forms and conservative Yungching main-area migration');
