const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.request().url().includes('buyer-feed.json')?r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[],listings:[]}}):r.abort());await p.route('http://localhost:43123/**',r=>{const f=path.resolve('01-crm','.'+new URL(r.request().url()).pathname);if(f.endsWith('inventory-transactions.json'))return r.fulfill({json:{schema:1,generatedAt:new Date().toISOString(),sources:[{id:'moi',status:'ok'}],listings:[]}});if(!fs.existsSync(f)||!fs.statSync(f).isFile())return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css'});});await p.addInitScript(()=>{window.invCalls=[];window.invJob=null;addEventListener('message',e=>{if(e.data?.channel!=='CRM_BUYER_REQUEST')return;const {id,type,payload}=e.data;invCalls.push({type,payload});if(type==='cancel'&&invJob)invJob.status='cancelled';let result=type==='hello'?{version:3,extensionVersion:'1.2.14'}:type==='inventorySync'||type==='sync'?{saved:payload.length}:type==='progress'?{job:invJob}:type==='last'?{inventoryFeeds:{}}:type==='buyerVerify'?{checks:payload.rows.map(p=>({id:p.id,...(['yungching:7417941','591:20734577'].includes(p.id)?{usage:'住家用',usageEvidence:'法定用途',availability:'available'}:{})}))}:type==='inventorySearch'?{jobId:'test'}:{};postMessage({channel:'CRM_BUYER_RESPONSE',id,result},location.origin);});});await p.goto('http://localhost:43123/index.html');





await p.evaluate(()=>{DB=[{id:'archive-client',name:'測試屋主',types:['庫存屋主'],mktTemplates:[{title:'長範本名稱'.repeat(14),content:'新北市很長地址'.repeat(20)+'\n金額 99,999,999 萬\n'+'長備註'.repeat(200)},{title:'第二筆',content:'保留內容'}]}];persist();_templates=[{title:'租賃',content:'內容'}];persistTemplates();_signingTemplates=[{title:'簽約',content:'內容'}];persistSigningTemplates();_otherTemplates=[{title:'其他',content:'內容'}];persistOtherTemplates();openTemplates();});
for(const tab of ['stock','rental','signing','other']){await p.evaluate(t=>setTplTab(t),tab);await p.locator('#tplBody .tpl-archive-action:visible').click();await p.locator('#tplBody .tpl-archive-toggle').click();assert.equal(await p.locator('#tplBody .tpl-archive-action:visible').innerText(),'還原');await p.locator('#tplBody .tpl-archive-action:visible').click();await p.locator('#tplBody .tpl-archive-toggle').click();assert.equal(await p.locator('#tplBody .tpl-archive-action:visible').innerText(),'封存');}
await p.evaluate(()=>setTplTab('stock'));for(const width of [1440,1024,780]){await p.setViewportSize({width,height:1000});assert(await p.locator('#tplBody').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await p.screenshot({path:path.join(process.env.TEMP,'template-archive-'+width+'.png'),fullPage:true});}
await p.locator('#tplBody .tpl-archive-action:visible').click();await p.reload();await p.evaluate(()=>openTemplates());assert.equal(await p.locator('#tplBody .tpl-archive-toggle').innerText(),'已封存（1）');await p.locator('#tplBody .tpl-archive-toggle').click();assert((await p.locator('#tplBody pre:visible').innerText()).includes('99,999,999'));await p.locator('#tplBody button[aria-label="編輯範本"]:visible').click();await p.locator('#mktEditContent').fill('封存後修改內容，地址保留完整，99,999,999 萬');await p.locator('#mktSaveBtn').click();assert.equal(await p.evaluate(()=>DB[0].mktTemplates[0].archived),true);assert((await p.locator('#tplBody pre:visible').innerText()).includes('封存後修改內容'));await p.evaluate(()=>{closeTemplates();openMktTemplates('archive-client');});assert.equal(await p.locator('#mktBody .tpl-archive-action').count(),1);await p.locator('#mktBody .tpl-archive-toggle').click();assert.equal(await p.locator('#mktBody .tpl-archive-action').innerText(),'還原');await p.locator('#mktBody .tpl-archive-action').click();assert.equal(await p.evaluate(()=>DB[0].mktTemplates[0].archived),false);assert.deepEqual(errors,[]);console.log('PASS archive/restore all categories, reload persistence, stock secondary entry and long content at 3 widths');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});