// Public search pages only. Never reads CRM customer files or executes source scripts.
const fs=require('node:fs'),path=require('node:path'),cheerio=require('cheerio'),acorn=require('acorn');
const ROOT=path.resolve(__dirname,'../..'),OUT=process.env.BUYER_FEED_OUTPUT||path.join(ROOT,'data/buyer-feed.json');
const number=v=>v===null||v===undefined||v===''?null:Number.isFinite(Number(String(v).replace(/,/g,'')))?Number(String(v).replace(/,/g,'')):null;
const firstNumber=v=>{const m=String(v??'').match(/[\d.]+/);return m?number(m[0]):null;};
const location=address=>{const m=String(address||'').replaceAll('臺','台').match(/^(台北市|新北市)([^市縣]{1,4}[區鄉鎮市])/);return {city:m?.[1]||'',district:m?.[2]||''};};
// Decode Nuxt's literal-only data envelope. No eval/vm or arbitrary calls.
function literal(n,env={}){if(!n)throw Error('資料缺漏');switch(n.type){case'Literal':return n.value;case'Identifier':if(Object.hasOwn(env,n.name))return env[n.name];throw Error('未知資料變數');case'UnaryExpression':if(n.operator==='void'&&n.argument.type==='Literal'&&n.argument.value===0)return null;if(n.operator==='-')return -literal(n.argument,env);if(n.operator==='!')return !literal(n.argument,env);throw Error('不支援的資料格式');case'NewExpression':if(n.callee.type==='Identifier'&&n.callee.name==='Set'&&n.arguments.length===1&&n.arguments[0].type==='ArrayExpression')return literal(n.arguments[0],env);throw Error('不支援的資料結構');case'ArrayExpression':return n.elements.map(x=>literal(x,env));case'ObjectExpression':return Object.fromEntries(n.properties.map(p=>{if(p.type!=='Property'||p.computed||p.method)throw Error('不支援的資料欄位');return [p.key.name??p.key.value,literal(p.value,env)];}));default:throw Error('不支援的資料節點 '+n.type);}}
function nuxt(html){const $=cheerio.load(html),script=$('script').toArray().map(x=>$(x).html()).find(s=>s?.startsWith('window.__NUXT__='));if(!script)throw Error('找不到公開物件資料');const ast=acorn.parse(script,{ecmaVersion:2020}),assign=ast.body[0]?.expression,call=assign?.right;if(assign?.type!=='AssignmentExpression'||call?.type!=='CallExpression'||call.callee.type!=='FunctionExpression'||call.callee.body.body.length!==1||call.callee.body.body[0].type!=='ReturnStatement')throw Error('資料格式已變更');const env={};call.callee.params.forEach((p,i)=>{if(p.type!=='Identifier')throw Error('資料格式已變更');env[p.name]=literal(call.arguments[i]);});return literal(call.callee.body.body[0].argument,env);}
function walk(o,predicate,out=[]){if(!o||typeof o!=='object')return out;if(predicate(o))out.push(o);else for(const v of Object.values(o))walk(v,predicate,out);return out;}
function parse591(html){return walk(nuxt(html),o=>o.houseid&&o.title&&o.region_name&&o.price!==undefined).filter(o=>o.kind&&o.address&&!o.is_newhouse).map(o=>({id:'591:'+o.houseid,source:'591',url:'https://sale.591.com.tw/home/house/detail/2/'+o.houseid+'.html',title:o.title,address:(o.region_name||'')+(o.section_name||'')+(o.address||''),city:o.region_name,district:o.section_name,price:number(o.price),area:number(o.area),mainArea:number(o.mainarea)||null,floor:number(String(o.floor||'').split('/')[0].replace(/F$/,'')),totalFloors:number(String(o.floor||'').split('/')[1]?.replace(/F$/,'')),parkingType:o.cartmodel||'',rooms:firstNumber(o.room),age:o.showhouseage&&/年/.test(o.showhouseage)?firstNumber(o.showhouseage):null,type:o.shape_name||o.kind_name||'',parking:o.has_carport===1?true:o.has_carport===0?false:null,image:o.photo_url||'',community:o.community_name||'',description:(o.tag||[]).map(t=>typeof t==='string'?t:t.name||'').join(' ')}));}
function parseSinyi(html){const $=cheerio.load(html),j=JSON.parse($('#__NEXT_DATA__').text()),rows=j.props?.initialReduxState?.buyReducer?.list;if(!Array.isArray(rows))throw Error('信義資料格式已變更');return rows.filter(o=>!o.isOff).map(o=>({id:'sinyi:'+o.houseNo,source:'sinyi',url:'https://www.sinyi.com.tw/buy/house/'+o.houseNo,title:o.name,address:o.address,...location(o.address),price:number(o.totalPrice),area:number(o.areaBuilding),rooms:firstNumber(String(o.layout||'').match(/([\d.]+)房/)?.[1]),age:firstNumber(o.age),type:$('a[href*="'+o.houseNo+'"]').first().find('[class*="type-badge"]').first().text().trim(),floor:number(o.floor),totalFloors:number(o.totalfloor),parkingType:typeof o.parking==='string'?o.parking:'',parking:typeof o.isParking==='boolean'?o.isParking:null,image:o.image?.[0]||'',community:o.commName||'',description:o.layout||''}));}
function parseYungching(html){const $=cheerio.load(html),rows=[];$('yc-ng-buy-house-card').each((_,el)=>{const c=$(el),href=c.find('a[href]').first().attr('href')||'',id=href.match(/house\/(\d+)/)?.[1];if(!id)return;const text=cls=>c.find('.'+cls).first().text().trim(),address=text('address');rows.push({id:'yungching:'+id,source:'yungching',url:'https://buy.yungching.com.tw/house/'+id,title:text('caseName'),address,...location(address),price:number(text('price')),area:firstNumber(text('regArea')),rooms:firstNumber(text('room').match(/([\d.]+)房/)?.[1]),age:firstNumber(c.find('.case-info').text().match(/([\d.]+)年/)?.[1]),type:text('caseType'),floor:number(text('floor').split('/')[0]),totalFloors:number(text('floor').split('/')[1]?.replace('樓','')),parking:/含車位|坡道平面|坡道機械|升降平面|升降機械/.test(c.text())?true:null,image:c.find('img').first().attr('src')||'',community:'',description:text('note')+' '+text('tag-list')});});if(!rows.length)throw Error('永慶未取得可解析物件');return rows;}
const parsers={yungching:parseYungching,sinyi:parseSinyi,'591':parse591};
async function request(url){const r=await fetch(url,{headers:{'User-Agent':'CRM-BuyerMatch/1.0 (public listing digest)'},signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error('HTTP '+r.status);const text=await r.text();if(text.length>6000000)throw Error('回應過大');return text;}
async function collect(){const now=new Date().toISOString();let old={listings:[]};try{old=JSON.parse(fs.readFileSync(OUT,'utf8'));}catch{}const previous=new Map(old.listings.map(x=>[x.id,x])),items=new Map(),sources=[];const areas=JSON.parse(fs.readFileSync(path.join(__dirname,'areas.json'),'utf8'));
 for(const source of (process.env.BUYER_FEED_SOURCES||'yungching,sinyi,591').split(',').filter(s=>Object.hasOwn(parsers,s))){let ok=0,fail=0,errors=[],count=0;const tasks=source==='591'?['1','3'].flatMap(id=>[0,30,60,90,120].map(first=>'https://sale.591.com.tw/?shType=list&regionid='+id+'&firstRow='+first)):areas.map(a=>source==='yungching'?'https://buy.yungching.com.tw/region/'+encodeURIComponent(a.city+'-'+a.district)+'_c':'https://www.sinyi.com.tw/buy/list/'+(a.city==='台北市'?'Taipei':'NewTaipei')+'-city/'+a.zip+'-zip');
  for(const url of tasks){try{const rows=parsers[source](await request(url));if(!rows.length)throw Error('未取得物件，待核對');for(const row of rows){if(!row.title||!row.city||!row.district||row.price===null||row.price<=0)continue;const prior=previous.get(row.id);items.set(row.id,{...row,firstSeenAt:prior?.firstSeenAt||now,seenAt:now,previousPrice:prior?.price!==row.price?prior?.price:prior?.previousPrice,priceChangedAt:prior&&prior.price!==row.price?now:prior?.priceChangedAt});count++;}ok++;}catch(e){fail++;errors.push(e.message);}await new Promise(r=>setTimeout(r,700));}
  // Keep last-known records only when source retrieval failed; mark them stale explicitly.
  if(fail)for(const row of old.listings.filter(x=>x.source===source))if(!items.has(row.id)&&Date.now()-Date.parse(row.seenAt)<7*86400000)items.set(row.id,{...row,stale:true});
  sources.push({id:source,status:ok?(fail?'partial':'ok'):'error',checkedAt:now,pages:ok,failedPages:fail,count,reason:fail?[...new Set(errors)].join('；'):'',coverage:source==='591'?'台北、新北各前五頁':'雙北各行政區搜尋第一頁'});console.log(source,ok,'pages',count,'rows',fail,'failed');
 }
 for(const source of old.sources||[])if(!sources.some(s=>s.id===source.id)){sources.push(source);for(const row of old.listings.filter(p=>p.source===source.id))items.set(row.id,row);}
 if(!sources.some(s=>s.id==='leju'))sources.push({id:'leju',status:'manual',checkedAt:now,pages:0,count:0,reason:'公開頁面回覆 HTTP 403，請至原站查看',coverage:'尚未自動取得'});
 const feed={schema:1,generatedAt:now,coverage:'台北市、新北市公開搜尋首批物件，非全站完整清單；未出現在本次搜尋不代表已下架。',sources,listings:[...items.values()]};fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(feed));console.log('saved',feed.listings.length,'unique listings');if(!sources.some(s=>s.status==='ok'||s.status==='partial'))process.exitCode=1;return feed;
}
module.exports={parse591,parseSinyi,parseYungching,literal,nuxt,collect};if(require.main===module)collect().catch(e=>{console.error(e.message);process.exitCode=1;});
