(function(){
'use strict';
const names={buyers:'一鍵配案',inventory:'一鍵追蹤'},sources={yungching:'永慶',sinyi:'信義','591':'591'},esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let dialog,scope,launchBusy=false,timer;const latest={},imported={};
function request(type,payload){return new Promise((resolve,reject)=>{const id=crypto.randomUUID(),timer=setTimeout(()=>{removeEventListener('message',listen);reject(Error('搜尋助手未回應，請確認 Chrome 助手已更新至 1.2.24。'));},10000);function listen(e){if(e.source!==window||e.origin!==location.origin||e.data?.channel!=='CRM_BUYER_RESPONSE'||e.data.id!==id)return;clearTimeout(timer);removeEventListener('message',listen);e.data.result?.error?reject(Error(e.data.result.error)):resolve(e.data.result);}addEventListener('message',listen);postMessage({channel:'CRM_BUYER_REQUEST',id,type,payload},location.origin);});}
function message(text){if(dialog?.open){dialog.querySelector('.bulk-content').textContent=text;dialog.querySelector('[data-retry]').hidden=true;}}
function open(kind){scope=kind;if(!dialog?.open){dialog=document.createElement('dialog');dialog.className='bulk-dialog';dialog.innerHTML='<header><h2></h2><button type="button" data-close aria-label="關閉">×</button></header><div class="bulk-content" role="status"></div><footer><button type="button" data-retry hidden>重試未完成</button><button type="button" data-results>查看結果</button><button type="button" data-close>關閉</button></footer>';document.body.append(dialog);dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());const owner=dialog;dialog.addEventListener('close',()=>{if(dialog===owner)clearTimeout(timer);owner.remove();},{once:true});dialog.querySelector('[data-results]').onclick=()=>{const kind=scope,owner=dialog;if(kind==='buyers')BuyerMatching.open();else InventoryMarket.open();const results=document.querySelector(kind==='buyers'?'#buyerMatchDialog':'.im-dialog');results?.addEventListener('close',()=>{if(dialog!==owner||!owner.isConnected||!owner.open)return;refresh(kind).catch(e=>message('進度暫時無法讀取：'+e.message));watch(kind);},{once:true});};dialog.querySelector('[data-retry]').onclick=()=>retry();dialog.showModal();}dialog.querySelector('h2').textContent=names[kind];message('正在確認已開啟的搜尋設定…');}
function render(data){latest[data.scope]=data;const b=document.querySelector('[data-bulk="'+data.scope+'"]');if(b){b.dataset.running=String(data.report?.status==='running');b.title=data.report?.status==='running'?'搜尋中，點選查看進度':data.scope==='buyers'?'搜尋所有已開啟自動配對的買方':'搜尋所有已開啟案件追蹤的庫存';}if(!dialog?.open||scope!==data.scope)return;const r=data.report;if(!r){message('尚無手動整批搜尋紀錄。');return;}const group=data.scope==='buyers'?r.buyers:r.inventory,unit=data.scope==='buyers'?'位買方':'件庫存',status=r.status==='completed'?'全部完成':r.status==='running'?'搜尋中':'部分未完成';dialog.querySelector('.bulk-content').innerHTML='<p class="bulk-state">'+status+' · '+group.completed+' / '+group.total+' '+unit+'完成</p><p>開始：'+esc(new Date(r.startedAt).toLocaleString('zh-TW'))+(r.finishedAt?' · 結束：'+esc(new Date(r.finishedAt).toLocaleString('zh-TW')):'')+'</p><div class="bulk-sources">'+r.sources.map(s=>'<div><b>'+sources[s.id]+'</b><span>'+s.completed+' / '+s.total+' 範圍完成'+(s.total===s.completed&&s.count===0?'，0 筆刊登':'')+'</span></div>').join('')+'</div>'+(r.error?'<p>'+esc(r.error)+'</p>':'')+(r.status==='partial'?'<ul>'+r.scopes.slice(0,3).map(s=>'<li>'+esc([sources[s.source],s.district,s.keyword,s.reason||'尚未完成'].filter(Boolean).join(' · '))+'</li>').join('')+'</ul>':'')+'<p class="bulk-note">'+(r.status==='running'?'可關閉此視窗，搜尋會繼續執行。':'結果已保留，可進入各買方或案件查看。')+'早上自動搜尋設定保持不變。</p>';dialog.querySelector('[data-retry]').hidden=r.status!=='partial'||!r.canRetry;dialog.querySelector('[data-retry]').disabled=data.busy;}
async function refresh(kind){const data=await request('batchStatus',{scope:kind});render(data);if(data.report&&data.report.status!=='running'&&imported[kind]!==data.id){if(kind==='buyers')await BuyerMatching.refreshBulkResults();else await InventoryMarket.tick();imported[kind]=data.id;}return data;}
function watch(kind){clearTimeout(timer);if(!dialog?.open||scope!==kind)return;timer=setTimeout(async()=>{try{await refresh(kind);}catch(e){message('進度暫時無法讀取：'+e.message+' 搜尋不一定已停止，稍後會再確認。');}if(dialog?.open&&scope===kind)watch(kind);},3000);}
function lock(value){launchBusy=value;document.querySelectorAll('[data-bulk]').forEach(b=>b.disabled=value);}
async function start(kind){if(launchBusy)return;open(kind);lock(true);try{const hello=await request('hello');if(!hello.extensionVersion||hello.extensionVersion.localeCompare('1.2.24',undefined,{numeric:true})<0)throw Error('請先執行搜尋助手更新至 1.2.24，再重新整理 CRM。');const status=await refresh(kind);if(status.report?.status==='running'){watch(kind);return;}if(status.busy)throw Error('目前已有搜尋進行中，請等完成後再執行'+names[kind]+'。');if(kind==='buyers')await BuyerMatching.prepareBulk();else await InventoryMarket.prepareBulk();message('正在啟動'+names[kind]+'…');await request('batchSearch',{scope:kind});await refresh(kind);dispatchEvent(new Event('crm:daily-search-started'));watch(kind);}catch(e){message(e.message);}finally{lock(false);}}
async function retry(){if(launchBusy)return;lock(true);try{if(scope==='buyers')await BuyerMatching.prepareBulk();else await InventoryMarket.prepareBulk();await request('batchRetry',{scope});await refresh(scope);watch(scope);}catch(e){message(e.message);}finally{lock(false);}}
document.querySelectorAll('[data-bulk]').forEach(b=>b.onclick=()=>start(b.dataset.bulk));
setInterval(()=>{if(document.hidden||dialog?.open||launchBusy)return;for(const kind of ['buyers','inventory'])refresh(kind).catch(()=>{});},15000);
window.BulkSearch={start};
})();
