(function(){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const types=['公寓','華廈','電梯大樓','透天','別墅','套房','店面','辦公','土地'];
function initial(d){if(d.matchCriteria)return structuredClone(d.matchCriteria);const old=String(d.roomTypes||'').split(',');return {version:1,rooms:old.flatMap(x=>x==='套房'?['1']:x==='二房'?['2']:x==='三房+'?['3+']:[]),types:old.filter(x=>types.includes(x)&&x!=='套房'),legacyTypes:old.includes('店辦豪土')?'店辦豪土':''};}
function chips(key,values,selected){return '<div class="bd-options" data-bd-options="'+key+'">'+values.map(([v,label])=>'<label><input type="checkbox" value="'+esc(v)+'" '+(selected?.includes(v)?'checked':'')+'><span>'+esc(label)+'</span></label>').join('')+'</div>';}
function field(k,label,value,unit){return '<label class="bd-field">'+label+'<div class="bd-number"><input inputmode="decimal" data-bm="'+k+'" value="'+esc(value)+'" aria-label="'+label+'"><span>'+unit+'</span></div></label>';}
function select(k,label,value,options){return '<label class="bd-field">'+label+'<select data-bm="'+k+'">'+options.map(([v,t])=>'<option value="'+v+'" '+(v===(value||'')?'selected':'')+'>'+t+'</option>').join('')+'</select></label>';}
const add=window.addBuyerDemand;window.addBuyerDemand=function(d={}){const r=add.apply(this,arguments),b=document.querySelector('#bDemandList .person-block:last-child'),m=initial(d);b.classList.add('bd-precise');b.querySelector('[data-f="budgetMin"]').parentElement.parentElement.parentElement.classList.add('bd-budget');b._matchLegacy=m.legacyTypes||'';
 const room=b.querySelector('.room-picker').parentElement;room.outerHTML='<div class="bd-group"><label>房間數 <small>可複選，未選不限</small></label>'+chips('rooms',[['1','1房'],['2','2房'],['3','3房'],['4','4房'],['5+','5房以上'],['3+','3房以上']],m.rooms)+'</div><div class="bd-group"><label>房屋類型 <small>與房數分開篩選</small></label>'+chips('types',types.map(x=>[x,x]),m.types)+(m.legacyTypes?'<p class="bd-hint">舊條件「店辦豪土」請改選明確類型；尚未選擇前標為待確認。</p>':'')+'</div>';
 const want=b.querySelector('[data-f="want"]'),noWant=b.querySelector('[data-f="noWant"]');for(const el of [want,noWant,b.querySelector('[data-f="areaOther"]')].filter(Boolean)){const t=document.createElement('textarea');t.dataset.f=el.dataset.f;t.rows=2;t.value=el.value;el.replaceWith(t);}b.querySelector('[data-f="want"]').previousElementSibling.textContent='偏好與補充（例如：採光佳、近公園）';b.querySelector('[data-f="noWant"]').previousElementSibling.textContent='排除與待確認事項（例如：不要壁癌、漏水）';
 const advanced=document.createElement('details');advanced.className='bd-advanced';advanced.innerHTML='<summary>進階條件 <span>坪數・屋齡・樓層・車位</span></summary><div class="bd-grid">'+select('areaBasis','坪數基準',m.areaBasis,[['','建坪'],['main','主建物坪數']])+field('areaMin','坪數最低',m.areaMin,'坪')+field('areaMax','坪數最高',m.areaMax,'坪')+field('ageMax','屋齡上限',m.ageMax,'年')+field('floorMin','最低樓層',m.floorMin,'樓')+field('floorMax','最高樓層',m.floorMax,'樓')+select('parking','車位需求',m.parking,[['','不限'],['yes','有車位'],['flat','平面車位']])+select('elevator','電梯需求',m.elevator,[['','不限'],['yes','有電梯'],['no','無電梯']])+select('purpose','購屋用途',m.purpose,[['','未指定'],['live','自住'],['invest','投資'],['business','營業']])+'</div>'+chips('exclude',[['first','排除1樓'],['top','排除頂樓'],['basement','排除地下室']],m.exclude)+'<label class="bd-field">指定社區／路段 <textarea rows="2" data-bm="keywords" placeholder="多個條件以逗號分隔，符合任一即可">'+esc(m.keywords)+'</textarea></label><div class="bd-group"><label>下列條件改為偏好 <small>勾選後只影響排序，不排除物件</small></label>'+chips('optional',['房間數','房屋類型','建坪','主建物坪數','屋齡','樓層','車位','平面車位','電梯','社區／路段'].map(x=>[x,x]),m.optional)+'</div><p class="bd-hint">區域、預算與排除樓層仍是必要條件。未改為偏好的條件亦為必要；原站缺少必要資料列待確認。自由文字需人工核對。</p>';const target=b.querySelector('[data-f="want"]').parentElement;target.before(advanced);if(Object.entries(m).some(([k,v])=>!['version','rooms','types','legacyTypes'].includes(k)&&v?.length))advanced.open=true;
 b.querySelectorAll('textarea').forEach(t=>{const resize=()=>{t.style.height='auto';t.style.height=Math.max(54,t.scrollHeight)+'px';};t.addEventListener('input',resize);requestAnimationFrame(resize);});return r;};
const get=window.getBuyerDemands;window.getBuyerDemands=function(){const rows=get.apply(this,arguments);document.querySelectorAll('#bDemandList .person-block').forEach((b,i)=>{const m={version:1};b.querySelectorAll('[data-bm]').forEach(el=>m[el.dataset.bm]=el.value.trim());b.querySelectorAll('[data-bd-options]').forEach(el=>m[el.dataset.bdOptions]=Array.from(el.querySelectorAll('input:checked'),x=>x.value));if(b._matchLegacy&&!m.types?.length)m.legacyTypes=b._matchLegacy;rows[i].matchCriteria=m;rows[i].roomTypes=[...(m.rooms||[]).map(x=>x==='3+'?'三房+':x==='5+'?'5房以上':x==='2'?'二房':x+'房'),...(m.types||[])].join(',');});return rows;};
window.BuyerDemandFields={initial,validate(d){const m=d.matchCriteria||{};for(const [k,label] of Object.entries({budgetMin:'預算最低',budgetMax:'預算最高',downPayment:'自備款'})){if(d[k]&&!/^\d+(?:\.\d+)?$/.test(d[k]))return label+'請填非負數字';}for(const k of ['areaMin','areaMax','ageMax','floorMin','floorMax'])if(m[k]&&!/^\d+(?:\.\d+)?$/.test(m[k]))return '進階條件請填非負數字';for(const [a,z,label] of [['budgetMin','budgetMax','預算'],['areaMin','areaMax','坪數'],['floorMin','floorMax','樓層']]){const v=a.startsWith('budget')?d:m;if(v[a]!==''&&v[a]!=null&&v[z]!==''&&v[z]!=null&&Number(v[a])>Number(v[z]))return label+'最低值不可大於最高值';}return '';}};
const save=window.saveClient;window.saveClient=function(){for(const d of getBuyerDemands()){const error=BuyerDemandFields.validate(d);if(error){showToast(error,'warn');return;}}return save.apply(this,arguments);};
})();
