(function(){
'use strict';
const names={yungching:'永慶',sinyi:'信義','591':'591',rakuya:'樂屋',leju:'樂居'},esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let dialog,feed,customerId,demandIndex=0;
function safeURL(s,image=false){try{const u=new URL(s);if(u.protocol!=='https:')return '';const domains=image?['yungching.com.tw','591.com.tw','sinyi.com.tw','rakuya.com.tw']:['buy.yungching.com.tw','sale.591.com.tw','www.sinyi.com.tw','www.rakuya.com.tw','www.leju.com.tw'];return domains.some(d=>u.hostname===d||(image&&u.hostname.endsWith('.'+d)))?u.href:'';}catch{return '';}}
function buyers(){return DB.filter(c=>!c._deleted&&(hasType(c,'經營買方')||c.bDemands?.length));}function current(){return DB.find(c=>c.id===customerId);}function demands(c){return c?.bDemands?.length?c.bDemands:[c||{}];}const $=id=>dialog.querySelector('#'+id);
function textStatus(t){$('bmStatus').textContent=t;}
function sourceLinks(d){const q=encodeURIComponent([d.areaDisplay,d.roomTypes,d.budgetMax?d.budgetMax+'萬以下':''].filter(Boolean).join(' '));return '<a target="_blank" rel="noopener" href="https://buy.yungching.com.tw/region/'+encodeURIComponent((d.areaCities?.[0]||'新北市')+(d.areaDists?.[0]?'-'+d.areaDists[0]:''))+'_c">永慶原站</a><a target="_blank" rel="noopener" href="https://www.sinyi.com.tw/buy/list">信義原站</a><a target="_blank" rel="noopener" href="https://sale.591.com.tw/?shType=list&regionid='+(d.areaCities?.[0]==='台北市'?'1':'3')+'">591 原站</a><a target="_blank" rel="noopener" href="https://www.rakuya.com.tw/sell/result">樂屋原站</a><a target="_blank" rel="noopener" href="https://www.leju.com.tw/">樂居原站</a>';}
function renderDemands(){const c=current();$('bmDemand').innerHTML=demands(c).map((d,i)=>'<option value="'+i+'">需求 '+(i+1)+' · '+esc(d.areaDisplay||'未指定區域')+'</option>').join('');demandIndex=0;render();}
function render(){const c=current(),d=demands(c)[demandIndex]||{};$('bmSummary').textContent=(c?(c.bName||c.name)+'：':'')+BuyerMatchEngine.summary(d);$('bmLinks').innerHTML=sourceLinks(d);$('bmEdit').disabled=!c;if(!feed){$('bmResults').innerHTML='<p class="bm-empty">正在讀取物件資料…</p>';return;}
 const source=$('bmSource').value,view=$('bmView').value,state=c?.buyerMatching||{},saved=new Set(state.saved||[]),hidden=new Set(state.hidden||[]);let rows=feed.listings.filter(p=>!source||p.source===source).map(p=>({p,r:BuyerMatchEngine.evaluate(d,p)})).filter(({p,r})=>view==='saved'?saved.has(p.id):view==='hidden'?hidden.has(p.id):!hidden.has(p.id)&&r.status!=='excluded'&&(view==='all'||r.status===view));rows.sort((a,b)=>Number(b.r.status==='matched')-Number(a.r.status==='matched')||b.r.yes.length-a.r.yes.length||Date.parse(b.p.firstSeenAt)-Date.parse(a.p.firstSeenAt));
 $('bmCount').textContent='本次 '+rows.length+' 筆候選 · 公開資料共 '+feed.listings.length+' 筆（不代表全站）';$('bmResults').innerHTML=rows.slice(0,100).map(({p,r})=>{const url=safeURL(p.url),img=safeURL(p.image,true),change=p.previousPrice&&p.price<p.previousPrice?' · 降價 '+(p.previousPrice-p.price).toLocaleString()+'萬':'';return '<article class="bm-card" data-id="'+esc(p.id)+'">'+(img?'<img src="'+esc(img)+'" alt="'+esc(p.title)+'" loading="lazy" referrerpolicy="no-referrer">':'')+'<h3>'+esc(p.title)+'</h3><p>'+esc(p.address)+'</p><div class="bm-price">'+esc(p.price?.toLocaleString()??'待確認')+' 萬</div><p>'+esc([p.rooms!=null?p.rooms+'房':'房數待確認',p.area!=null?'建坪 '+p.area+'坪':'坪數待確認',p.age!=null?p.age+'年':'屋齡待確認'].join(' · '))+'</p><p>'+esc(names[p.source])+esc(change)+'</p><div>'+r.yes.map(t=>'<span class="bm-tag">'+esc(t)+'</span>').join('')+r.pending.map(t=>'<span class="bm-tag pending">待確認：'+esc(t)+'</span>').join('')+'</div><footer>'+(url?'<a href="'+esc(url)+'" target="_blank" rel="noopener">查看原物件 ↗</a>':'')+'<button data-action="save" aria-pressed="'+saved.has(p.id)+'">'+(saved.has(p.id)?'已收藏':'收藏')+'</button><button data-action="hide">'+(hidden.has(p.id)?'恢復顯示':'略過')+'</button></footer></article>';}).join('')||'<p class="bm-empty">這批資料沒有符合目前條件的候選。可調整需求或到原站搜尋；不代表市場上沒有物件。</p>';
 if(rows.length>100)$('bmResults').insertAdjacentHTML('beforeend','<p>先顯示前 100 筆，請縮小需求或來源範圍。</p>');$('bmResults').querySelectorAll('img').forEach(img=>img.onerror=()=>{const note=document.createElement('span');note.textContent='照片暫無法載入';img.replaceWith(note);});
 $('bmSources').innerHTML=feed.sources.map(s=>'<p><strong>'+esc(names[s.id]||s.id)+'</strong>：'+esc(s.status==='ok'?'已更新':s.status==='partial'?'部分更新':s.status==='manual'?'原站查看':'讀取失敗')+' · '+esc(s.coverage||'')+(s.reason?' · '+esc(s.reason):'')+'</p>').join('')+'<p>樂屋：第一版提供原站入口，自動取得尚未啟用。</p>';
}
async function load(){textStatus('正在取得最新公開物件…');$('bmRefresh').disabled=true;try{const url='https://raw.githubusercontent.com/dsiqke8d1w5q2zz5/jijdspwl3115djsjlp/main/01-crm/data/buyer-feed.json?t='+Date.now();let r;try{r=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error();}catch{r=await fetch('./data/buyer-feed.json',{cache:'no-store',signal:AbortSignal.timeout(10000)});}if(!r.ok)throw Error('公開資料暫時無法取得');const next=await r.json();if(next.schema!==1||!Array.isArray(next.listings)||!Array.isArray(next.sources))throw Error('資料格式不正確');feed=next;const stale=Date.now()-Date.parse(feed.generatedAt)>36*3600000;textStatus((stale?'資料已超過 36 小時未更新。':'')+'最後取得：'+new Date(feed.generatedAt).toLocaleString('zh-TW')+'。每日台灣時間上午 8:07 由雲端排程更新，實際完成時間可能延後；不需開啟電腦。開啟此頁時依需求配對。');render();}catch(e){textStatus('更新失敗：'+e.message+(feed?'，目前保留上次資料。':''));if(!feed)$('bmResults').innerHTML='<p class="bm-empty">目前無法讀取公開物件，仍可使用原站連結。</p>';}finally{$('bmRefresh').disabled=false;}}
function storeAction(id,kind){const c=current();if(!c)return;const previous=structuredClone(c.buyerMatching||{}),next=structuredClone(previous),key=kind==='save'?'saved':'hidden',set=new Set(next[key]||[]);set.has(id)?set.delete(id):set.add(id);next[key]=[...set];c.buyerMatching=next;if(!persist()){c.buyerMatching=previous;showToast('未能儲存，請重試','error');return;}render();}
function open(id){if(dialog?.open){dialog.focus();return;}const list=buyers();customerId=list.some(c=>c.id===id)?id:list[0]?.id;dialog=document.createElement('dialog');dialog.className='bm-dialog';dialog.id='buyerMatchDialog';dialog.innerHTML='<header><h2>買方需求配對</h2><button id="bmClose" aria-label="關閉配對">✕</button></header><div class="bm-body"><div class="bm-filters"><label>買方<select id="bmBuyer">'+list.map(c=>'<option value="'+esc(c.id)+'" '+(c.id===customerId?'selected':'')+'>'+esc(c.bName||c.name)+'</option>').join('')+'</select></label><label>需求<select id="bmDemand"></select></label><button id="bmEdit">編輯需求</button><button id="bmRefresh" class="bm-primary">讀取最新</button></div><div id="bmSummary" class="bm-summary"></div><div id="bmLinks" class="bm-sources"></div><p id="bmStatus" class="bm-status" role="status"></p><details class="bm-details"><summary>來源與搜尋範圍</summary><p>雙北公開搜尋首批，非全站清單。同站相同編號合併；不同網站可能刊登同一物件，第一版保留來源，不會擅自合併。新增日期是本系統首次看見的日期。</p><div id="bmSources"></div></details><div class="bm-filters"><label>查看<select id="bmView"><option value="all">符合與待確認</option><option value="matched">已知條件符合</option><option value="pending">待確認</option><option value="saved">已收藏</option><option value="hidden">已略過</option></select></label><label>來源<select id="bmSource"><option value="">全部已取得來源</option><option value="yungching">永慶</option><option value="sinyi">信義</option><option value="591">591</option></select></label></div><p id="bmCount" class="bm-count"></p><div id="bmResults" class="bm-grid"></div></div>';document.body.append(dialog);dialog.showModal();$('bmClose').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();$('bmBuyer').onchange=()=>{customerId=$('bmBuyer').value;renderDemands();};$('bmDemand').onchange=()=>{demandIndex=Number($('bmDemand').value);render();};$('bmView').onchange=$('bmSource').onchange=render;$('bmRefresh').onclick=load;$('bmEdit').onclick=()=>{dialog.close();openEdit(customerId);};$('bmResults').onclick=e=>{const b=e.target.closest('button[data-action]');if(b)storeAction(b.closest('[data-id]').dataset.id,b.dataset.action);};renderDemands();if(!list.length){textStatus('請先新增買方並填寫需求，再開始配對。');$('bmResults').innerHTML='<button id="bmAddBuyer">新增買方</button>';$('bmAddBuyer').onclick=()=>{dialog.close();openAdd();};$('bmRefresh').disabled=true;}else load();}
window.BuyerMatching={open};
})();
