(function(){
'use strict';
let menu,opener;
function close(restore=false){if(!menu)return;menu.remove();menu=null;opener?.setAttribute('aria-expanded','false');if(restore&&opener?.isConnected)opener.focus();}
function toggle(button,actions){if(opener===button&&menu){close();return;}close();opener=button;menu=document.createElement('div');menu.className='dash-action-menu';menu.setAttribute('popover','auto');menu.setAttribute('aria-label','行程與待辦操作');for(const original of actions){const action=original.cloneNode(true);action.removeAttribute('style');action.className='dash-menu-action';action.type='button';const label=original.title||original.getAttribute('aria-label');action.append(document.createTextNode(' '+label));action.addEventListener('click',()=>close(),true);menu.append(action);}document.body.append(menu);menu.showPopover();button.setAttribute('aria-expanded','true');const rect=button.getBoundingClientRect(),box=menu.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(innerWidth-box.width-8,rect.right-box.width))+'px';menu.style.top=Math.max(8,rect.bottom+box.height+6<innerHeight?rect.bottom+4:rect.top-box.height-4)+'px';const currentMenu=menu;menu.addEventListener('toggle',e=>{if(e.newState==='closed'&&menu===currentMenu)close();});menu.firstElementChild?.focus({preventScroll:true});}
function enhance(root){root.querySelectorAll('.dash-clickedit:not([data-compact-actions])').forEach(row=>{const buttons=[...row.querySelectorAll('button.btn-ic')],done=buttons.find(b=>b.title==='完成'),actions=buttons.filter(b=>['編輯','刪除','轉待辦','轉行程'].includes(b.title));if(!done||!actions.length)return;row.dataset.compactActions='true';const tray=document.createElement('div');tray.className='dash-compact-actions';done.setAttribute('aria-label','完成');done.parentElement.dataset.oldActions='true';tray.append(done);actions.forEach(b=>{b.parentElement.dataset.oldActions='true';b.remove();});const more=document.createElement('button');more.type='button';more.className='btn-ic';more.textContent='⋯';more.title='更多';more.setAttribute('aria-label','更多操作');more.setAttribute('aria-expanded','false');more.onclick=e=>{e.stopPropagation();toggle(more,actions);};tray.append(more);tray.onclick=e=>e.stopPropagation();row.append(tray);row.querySelectorAll('[data-old-actions]').forEach(e=>{if(!e.children.length)e.remove();});});}
for(const id of ['dashSchedule','dashTodo']){const root=document.getElementById(id);if(!root)continue;enhance(root);new MutationObserver(()=>{if(opener&&!opener.isConnected)close();enhance(root);}).observe(root,{childList:true,subtree:true});}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu){e.preventDefault();close(true);}});document.addEventListener('click',e=>{if(menu&&!menu.contains(e.target)&&e.target!==opener)close();});window.addEventListener('resize',()=>close());for(const type of ['wheel','touchmove'])document.addEventListener(type,e=>{if(menu&&!menu.contains(e.target))close();},{capture:true,passive:true});
})();
