const fs=require('fs'),path=require('path'),crypto=require('crypto');
function csv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(Boolean))rows.push(row);row=[];field='';}else field+=c;}if(field||row.length){row.push(field);rows.push(row);}return rows;}
const num=v=>v==null||v===''?null:Number.isFinite(Number(v))?Number(v):null;
function date(v){if(!/^\d{7}$/.test(v))return '';return (+v.slice(0,3)+1911)+'-'+v.slice(3,5)+'-'+v.slice(5,7);}
function parse(text,city){const rows=csv(text.replace(/^\uFEFF/,'')),headers=rows.shift();if(!headers?.includes('編號')||!headers.includes('總價元'))throw Error('官方資料欄位不符');return rows.flatMap(values=>{const r=Object.fromEntries(headers.map((h,i)=>[h,values[i]]));if(!r['交易標的']?.includes('建物')||!r['編號'])return [];const price=num(r['總價元']),area=num(r['建物移轉總面積平方公尺']);if(!(price>0)||!date(r['交易年月日']))return [];const address=r['土地位置建物門牌'],parkingPrice=num(r['車位總價元']),parkingArea=num(r['車位移轉總面積平方公尺']);return [{id:'moi:'+r['編號']+':'+(r['移轉編號']||''),source:'moi',kind:'transaction',city,district:r['鄉鎮市區'],address:address.startsWith(city)||address.startsWith(city.replace('台','臺'))?address:city+address,title:'實價登錄｜'+address,price:price/10000,area:area?Math.round(area/3.305785*100)/100:null,floorText:r['移轉層次'],type:r['建物型態'],tradeDate:date(r['交易年月日']),parkingPrice:parkingPrice==null?null:parkingPrice/10000,parkingArea:parkingArea==null?null:Math.round(parkingArea/3.305785*100)/100,notes:r['備註'],url:'https://lvr.land.moi.gov.tw/jsp/index.jsp'}];});}
const CITIES=[['a','台北市'],['b','台中市'],['c','基隆市'],['d','台南市'],['e','高雄市'],['f','新北市'],['g','宜蘭縣'],['h','桃園市'],['i','嘉義市'],['j','新竹縣'],['k','苗栗縣'],['m','南投縣'],['n','彰化縣'],['o','新竹市'],['p','雲林縣'],['q','嘉義縣'],['t','屏東縣'],['u','花蓮縣'],['v','台東縣'],['w','金門縣'],['x','澎湖縣'],['z','連江縣']];
async function collect(options={}){
 const dest=path.resolve('01-crm/data/inventory-transactions.json'),old=options.previous||(fs.existsSync(dest)?JSON.parse(fs.readFileSync(dest,'utf8').replace(/^\uFEFF/,'')):{listings:[]}),items=new Map(old.listings.map(p=>[p.id,p])),sources=[],now=new Date().toISOString();
 for(const[code,city]of CITIES){try{
  const response=await (options.fetch||fetch)('https://plvr.land.moi.gov.tw/Download?type=csv&fileName='+code+'_lvr_land_a.csv',{signal:AbortSignal.timeout(25000)});if(!response.ok)throw Error('官方下載失敗 '+response.status);
  const bytes=await response.arrayBuffer();let text=new TextDecoder('utf-8',{fatal:false}).decode(bytes);if(text.includes('\ufffd'))text=new TextDecoder('big5').decode(bytes);const rows=parse(text,city);
  for(const row of rows){const fingerprint=crypto.createHash('sha256').update(JSON.stringify(row)).digest('hex'),prior=items.get(row.id);items.set(row.id,{...row,fingerprint,seenAt:prior?.fingerprint===fingerprint?prior.seenAt:now,publishedObservedAt:prior?.publishedObservedAt||now});}
  sources.push({city,status:'ok',count:rows.length});
 }catch(error){sources.push({city,status:'error',reason:error.message,count:0});}}
 const ok=sources.filter(s=>s.status==='ok').length,feed={schema:1,generatedAt:now,attribution:'資料來源：內政部不動產成交案件實際資訊資料供應系統；全台當期開放資料累積，非全部歷史成交。以官方查詢動態資料為準。',sources:[{id:'moi',status:ok===CITIES.length?'ok':ok?'partial':'error',coverage:'全台當期開放資料累積；非全部歷史',cities:sources}],listings:[...items.values()]};
 if(options.write!==false)fs.writeFileSync(dest,JSON.stringify(feed));console.log(JSON.stringify({count:feed.listings.length,sources}));return feed;
}
module.exports={parse,csv,date,collect,CITIES};if(require.main===module)collect().catch(e=>{console.error(e.message);process.exitCode=1});
