importScripts('areas.js','match-engine.js');
const CRM='https://dsiqke8d1w5q2zz5.github.io/jijdspwl3115djsjlp/01-crm/';
let busy=false;
function cleanDemands(ds){return (Array.isArray(ds)?ds:[]).map(d=>({areaCities:(d.areaCities||[]).filter(c=>['台北市','新北市'].includes(c)),areaDists:(d.areaDists||[]).filter(x=>CRM_AREAS.some(a=>a.district===x))}));}
function tasksFor(ds){const tasks=new Map();for(const d of cleanDemands(ds)){const areas=CRM_AREAS.filter(a=>(!d.areaCities.length||d.areaCities.includes(a.city))&&(!d.areaDists.length||d.areaDists.includes(a.district)));for(const a of areas){const urls={yungching:'https://buy.yungching.com.tw/region/'+encodeURIComponent(a.city+'-'+a.district)+'_c',sinyi:'https://www.sinyi.com.tw/buy/list/'+(a.city==='台北市'?'Taipei':'NewTaipei')+'-city/'+a.zip+'-zip',rakuya:'https://www.rakuya.com.tw/sell/result?zipcode='+a.zip,leju:'https://www.leju.com.tw/object_list?city_code='+(a.city==='台北市'?'A':'F')+'&post_codes='+a.zip,'591':'https://sale.591.com.tw/?shType=list&regionid='+(a.city==='台北市'?'1':'3')};for(const [source,url]of Object.entries(urls))tasks.set(url,{source,url,city:a.city});}}return [...tasks.values()];}
async function pageRows(task){let tab;try{tab=await chrome.tabs.create({url:task.url,active:false});for(let i=0;i<35;i++){const state=await chrome.tabs.get(tab.id);if(state.status==='complete')break;await new Promise(r=>setTimeout(r,1000));}await chrome.scripting.executeScript({target:{tabId:tab.id},files:['acorn.js','read591.js','read.js']});for(let i=0;i<8;i++){const result=await chrome.scripting.executeScript({target:{tabId:tab.id},func:(source,city)=>({rows:globalThis.crmReadListings(source,city),blocked:/驗證您是否|verify you are human|checking your browser|access denied|just a moment/i.test(document.title+' '+document.body.innerText.slice(0,1200))}),args:[task.source,task.city]});const data=result[0]?.result;if(data?.blocked)throw Error('原站要求驗證或拒絕讀取，請自行開啟原站確認');if(data?.rows?.length)return data.rows;await new Promise(r=>setTimeout(r,1500));}throw Error('沒有讀到物件；可能無結果、需登入或頁面已變更');}finally{if(tab?.id)await chrome.tabs.remove(tab.id).catch(()=>{});}}
async function search(ds){if(busy)throw Error('另一個搜尋正在進行，請稍後再試');const tasks=tasksFor(ds);if(!tasks.length)throw Error('請先選擇雙北搜尋區域');if(tasks.length>40)throw Error('請將本次搜尋縮小至 8 個行政區以內，再搜尋；不會偷偷省略其餘區域');busy=true;const started=Date.now(),now=new Date().toISOString(),rows=new Map(),sources=new Map();try{for(const [taskIndex,task] of tasks.entries()){if(Date.now()-started>210000){for(const remaining of tasks.slice(taskIndex)){const prior=sources.get(remaining.source)||{id:remaining.source,pages:0,count:0,failedPages:0,coverage:'尚未完成'};prior.status=prior.pages?'partial':'error';prior.failedPages++;prior.reason='本次搜尋達時間上限，請縮小行政區後重試';sources.set(remaining.source,prior);}break;}let s=sources.get(task.source)||{id:task.source,status:'ok',pages:0,failedPages:0,count:0,checkedAt:now,coverage:task.source==='591'?'選定縣市第一頁':'選定行政區第一頁',reason:''};try{for(const row of await pageRows(task)){rows.set(row.id,{...row,firstSeenAt:now,seenAt:now});s.count++;}s.pages++;}catch(e){s.failedPages++;s.reason=e.message;}s.status=s.failedPages?(s.pages?'partial':'error'):'ok';sources.set(task.source,s);await chrome.storage.local.set({progress:{done:sources.size,pages:[...sources.values()].reduce((n,x)=>n+x.pages+x.failedPages,0),total:tasks.length,at:now}});}return {schema:1,generatedAt:now,coverage:'瀏覽器即時搜尋首批，非全站清單',sources:[...sources.values()],listings:[...rows.values()]};}finally{busy=false;await chrome.storage.local.remove('progress');}}
async function schedule(){if(!(await chrome.alarms.get('buyer-daily'))){const now=new Date(),at=new Date();at.setHours(8,25,0,0);if(at<=now)at.setDate(at.getDate()+1);await chrome.alarms.create('buyer-daily',{when:at.getTime(),periodInMinutes:1440});}}
chrome.runtime.onInstalled.addListener(schedule);chrome.runtime.onStartup.addListener(schedule);
chrome.alarms.onAlarm.addListener(async a=>{if(a.name!=='buyer-daily')return;const {selection=[]}=await chrome.storage.local.get('selection');if(!selection.length)return;try{const feed=await search(selection.flatMap(s=>s.demands));if(!feed.sources.some(s=>s.status==='ok'||s.status==='partial'))throw Error('各來源均未取得物件，保留上次結果');await chrome.storage.local.set({last:feed,lastError:null,lastMatches:selection.map(s=>({id:s.id,counts:s.demands.map(d=>feed.listings.filter(p=>BuyerMatchEngine.evaluate(d,p).status!=='excluded').length),at:feed.generatedAt}))});}catch(e){await chrome.storage.local.set({lastError:e.message});}});
chrome.runtime.onMessage.addListener((msg,sender,reply)=>{if(!sender.url?.startsWith(CRM))return;const go=async()=>{if(msg.type==='hello')return {version:1,busy};if(msg.type==='sync'){if(!Array.isArray(msg.payload)||msg.payload.length>100||msg.payload.some(x=>!Array.isArray(x.demands)||x.demands.length>10))throw Error('最多可設定 100 位買方，每位 10 組需求；原設定保持不變');const selection=msg.payload.map(x=>({id:String(x.id).slice(0,100),demands:x.demands.map(d=>Object.fromEntries(['areaCities','areaDists','areaDisplay','roomTypes','budgetMin','budgetMax','budget','want','noWant','matchCriteria'].filter(k=>d[k]!==undefined).map(k=>[k,d[k]])))}));await chrome.storage.local.set({selection});return {saved:selection.length};}if(msg.type==='last')return chrome.storage.local.get(['last','lastError','progress']);if(msg.type==='search'){const feed=await search(msg.payload?.demands);await chrome.storage.local.set({lastManual:feed});return {feed};}throw Error('不支援的操作');};go().then(reply,e=>reply({error:e.message}));return true;});
