importScripts('areas.js','match-engine.js');
const CRM='https://dsiqke8d1w5q2zz5.github.io/jijdspwl3115djsjlp/01-crm/';
const FIELDS=['areaCities','areaDists','areaDisplay','roomTypes','budgetMin','budgetMax','budget','want','noWant','matchCriteria'];
let working=false,starting=false;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function cleanDemands(ds){if(!Array.isArray(ds)||!ds.length)throw Error('請先填寫買方需求');return ds.map(d=>Object.fromEntries(FIELDS.filter(k=>d[k]!==undefined).map(k=>[k,d[k]])));}
function tasksFor(ds){const tasks=new Map();for(const d of ds){const areas=CRM_AREAS.filter(a=>(!d.areaCities?.length||d.areaCities.includes(a.city))&&(!d.areaDists?.length||d.areaDists.includes(a.district)));for(const a of areas){const urls={yungching:'https://buy.yungching.com.tw/region/'+encodeURIComponent(a.city+'-'+a.district)+'_c',sinyi:'https://www.sinyi.com.tw/buy/list/'+(a.city==='台北市'?'Taipei':'NewTaipei')+'-city/'+a.zip+'-zip',rakuya:'https://www.rakuya.com.tw/sell/result?zipcode='+a.zip,leju:'https://www.leju.com.tw/object_list?city_code='+(a.city==='台北市'?'A':'F')+'&post_codes='+a.zip,'591':'https://sale.591.com.tw/?shType=list&regionid='+(a.city==='台北市'?'1':'3')};for(const [source,url]of Object.entries(urls)){const key=source+':'+a.zip;tasks.set(key,{key,source,url,city:a.city,district:a.district,first:true,visited:[],lastIds:[]});}}}return [...tasks.values()];}
async function pageRows(task){let tab;try{tab=await chrome.tabs.create({url:task.url,active:false});await chrome.storage.local.set({ownedTab:tab.id});for(let i=0;i<35;i++){if((await chrome.tabs.get(tab.id)).status==='complete')break;await delay(1000);}if(task.source==='591'&&task.first){let chosen=false;for(let i=0;i<12;i++){const r=await chrome.scripting.executeScript({target:{tabId:tab.id},func:district=>{const button=[...document.querySelectorAll('button.section')].find(e=>e.textContent.trim()===district);if(!button)return false;const checkbox=button.querySelector('input');if(!checkbox?.checked){button.click();return false;}return new URL(location.href).searchParams.has('section');},args:[task.district]});if(r[0]?.result){chosen=true;break;}await delay(1500);}if(!chosen)throw Error('591 行政區篩選未確認，沒有改抓整個縣市');await delay(1500);}
 await chrome.scripting.executeScript({target:{tabId:tab.id},files:['acorn.js','read591.js','read.js','pagination.js']});for(let i=0;i<12;i++){const result=await chrome.scripting.executeScript({target:{tabId:tab.id},func:(source,city)=>globalThis.crmReadPage(source,city),args:[task.source,task.city]});const data=result[0]?.result;if(data?.blocked)throw Error('原站拒絕讀取或要求驗證');if(data&&(data.rows?.length||data.complete)&&(data.page||data.complete))return data;await delay(1500);}throw Error('物件或分頁尚未確認，未視為完成');}finally{if(tab?.id)await chrome.tabs.remove(tab.id).catch(()=>{});await chrome.storage.local.remove('ownedTab');}}
async function resumeAlarm(){await chrome.alarms.create('buyer-continue',{delayInMinutes:0.5});}
async function startSearch(ds,kind='manual',selection=[],buyerId=''){if(starting)throw Error('正在建立搜尋');starting=true;try{const prior=(await chrome.storage.local.get('job')).job;if(prior?.status==='running')throw Error('已有逐頁搜尋進行中，請等待完成或先取消');const demands=cleanDemands(ds),todo=tasksFor(demands);if(!todo.length)throw Error('請選擇雙北行政區');const now=new Date().toISOString(),job={id:crypto.randomUUID(),kind,selection,buyerId,demands,status:'running',startedAt:now,todo,totalScopes:todo.length,doneScopes:0,pages:0,scanned:0,listings:{},sources:{},seen:{}};await chrome.storage.local.set({job});await resumeAlarm();return {jobId:job.id};}finally{starting=false;}}
function summary(job){return job?{id:job.id,buyerId:job.buyerId,status:job.status,pages:job.pages,scanned:job.scanned,count:Object.keys(job.listings).length,doneScopes:job.doneScopes,totalScopes:job.totalScopes,error:job.error,feed:job.status==='running'?undefined:job.feed}:null;}
async function runChunk(){if(working)return;working=true;try{let {job,history={},ownedTab}=await chrome.storage.local.get(['job','history','ownedTab']);if(ownedTab){await chrome.tabs.remove(ownedTab).catch(()=>{});await chrome.storage.local.remove('ownedTab');}if(!job||job.status!=='running')return;await resumeAlarm();const until=Date.now()+60000;
 while(job.todo.length&&Date.now()<until){const task=job.todo.shift(),s=job.sources[task.source]||{id:task.source,status:'running',pages:0,count:0,completedScopes:0,failedPages:0,coverage:'依行政區逐頁搜尋，尚未完成'};try{const data=await pageRows(task);const ids=data.rows.map(r=>r.id).sort();if(task.visited.includes(task.url)||(ids.length&&ids.join('|')===task.lastIds.join('|')))throw Error('翻頁回傳重複內容，停止此區避免假完成');s.pages++;job.pages++;job.scanned+=data.rows.length;const now=new Date().toISOString();for(const row of data.rows){const old=history[row.id];job.seen[row.id]={firstSeenAt:old?.firstSeenAt||job.startedAt,price:row.price,seenAt:now};if(job.demands.some(d=>BuyerMatchEngine.evaluate(d,row).status!=='excluded')){job.listings[row.id]={...row,firstSeenAt:old?.firstSeenAt||job.startedAt,seenAt:now,discovery:old?'seen':'new',previousPrice:old?.price!==row.price?old?.price:undefined};}}
 if(data.next){const next=new URL(data.next);if(next.origin!==new URL(task.url).origin||!/^https:/.test(next.protocol))throw Error('下一頁網址不屬於原站');job.todo.push({...task,url:next.href,first:false,visited:[...task.visited,task.url],lastIds:ids});}else if(data.complete){job.doneScopes++;s.completedScopes++;}else throw Error('找不到可確認的下一頁或末頁');
 }catch(e){s.failedPages++;s.reason=e.message;job.doneScopes++;}s.count=Object.values(job.listings).filter(p=>p.source===task.source).length;s.status=s.failedPages?'partial':'running';job.sources[task.source]=s;const latest=(await chrome.storage.local.get('job')).job;if(latest?.id!==job.id||latest.status==='cancelled')return;await chrome.storage.local.set({job});await delay(1500);}
 if(job.todo.length){await resumeAlarm();return;}const now=new Date().toISOString();for(const s of Object.values(job.sources)){s.status=s.failedPages?(s.pages?'partial':'error'):'ok';s.checkedAt=now;s.coverage=s.failedPages?'部分區域未完成':`已讀至各搜尋區域的原站末頁（${s.pages} 頁）`;}
 job.status=Object.values(job.sources).some(s=>s.failedPages)?'partial':'completed';job.feed={schema:1,generatedAt:now,coverage:'已逐頁讀取；完成範圍依各來源狀態，受原站可見結果上限限制',sources:Object.values(job.sources),listings:Object.values(job.listings)};for(const [id,v]of Object.entries(job.seen))history[id]=v;job.seen={};job.todo=[];const patch={job,history};if(job.feed.sources.some(s=>s.status==='ok'||s.status==='partial')){if(job.kind==='auto'){patch.last=job.feed;patch.lastError=job.status==='partial'?'部分來源未完成，請查看來源狀態':null;}else patch.lastManual=job.feed;}else patch.lastError='各來源均未取得資料，保留上次結果';await chrome.storage.local.set(patch);await chrome.alarms.clear('buyer-continue');
 }catch(e){const {job}=await chrome.storage.local.get('job');if(job){job.status='partial';job.error='搜尋中斷：'+e.message;await chrome.storage.local.set({job,lastError:job.error});}}finally{working=false;}}
async function schedule(){if(!(await chrome.alarms.get('buyer-daily'))){const now=new Date(),at=new Date();at.setHours(8,25,0,0);if(at<=now)at.setDate(at.getDate()+1);await chrome.alarms.create('buyer-daily',{when:at.getTime(),periodInMinutes:1440});}if((await chrome.storage.local.get('job')).job?.status==='running')await resumeAlarm();}
chrome.runtime.onInstalled.addListener(schedule);chrome.runtime.onStartup.addListener(schedule);
chrome.alarms.onAlarm.addListener(async a=>{if(a.name==='buyer-continue')return runChunk();if(a.name!=='buyer-daily')return;const {selection=[]}=await chrome.storage.local.get('selection');if(!selection.length)return;try{await startSearch(selection.flatMap(s=>s.demands),'auto',selection);await runChunk();}catch(e){await chrome.storage.local.set({lastError:e.message});}});
chrome.runtime.onMessage.addListener((msg,sender,reply)=>{if(!sender.url?.startsWith(CRM))return;const go=async()=>{if(msg.type==='hello')return {version:2};if(msg.type==='sync'){if(!Array.isArray(msg.payload)||msg.payload.length>100||msg.payload.some(x=>!Array.isArray(x.demands)||x.demands.length>10))throw Error('最多 100 位買方，每位 10 組需求；原設定保持不變');const selection=msg.payload.map(x=>({id:String(x.id),demands:cleanDemands(x.demands)}));await chrome.storage.local.set({selection});return {saved:selection.length};}if(msg.type==='last')return chrome.storage.local.get(['last','lastError']);if(msg.type==='progress')return {job:summary((await chrome.storage.local.get('job')).job)};if(msg.type==='cancel'){const {job}=await chrome.storage.local.get('job');if(job?.status==='running'){job.status='cancelled';await chrome.storage.local.set({job});await chrome.alarms.clear('buyer-continue');}return {cancelled:true};}if(msg.type==='search')return startSearch(msg.payload?.demands,'manual',[],String(msg.payload?.buyerId||''));throw Error('不支援的操作');};go().then(result=>{reply(result);if(msg.type==='search')runChunk();},e=>reply({error:e.message}));return true;});
