// Pagination is based on each site's visible controls; absence is not proof of completion.
globalThis.crmReadPage=function(source,city){
 const rows=crmReadListings(source,city),n=x=>Number(String(x||'').replace(/[^0-9]/g,'')),url=new URL(location.href);let page=0,total=0,next=null;
 if(source==='yungching'){page=n(document.querySelector('.paginationPageListItem.actived')?.textContent);total=Math.max(0,...[...document.querySelectorAll('.paginationPageListItem')].map(e=>n(e.textContent)));if(page&&total>page){url.pathname=url.pathname.replace('/region/','/list/');url.searchParams.set('pg',page+1);next=url.href;}}
 if(source==='rakuya'){const p=document.querySelector('#app_pagination');page=n(p?.querySelector('input')?.value);total=n(p?.textContent.match(/共\s*([\d,]+)\s*頁/)?.[1]);if(page&&total>page){url.searchParams.set('page',page+1);next=url.href;}}
 if(source==='leju'){page=n(document.querySelector('.page-item.active')?.textContent)||n(url.searchParams.get('page'))||1;total=n(document.querySelector('[aria-label="最後一頁"]')?.textContent)||Math.max(0,...[...document.querySelectorAll('a.page-item')].map(e=>n(e.textContent)));const last=document.querySelector('button[aria-label="下一頁"]');if(last&&!last.disabled&&total>page){url.searchParams.set('page',page+1);next=url.href;}}
 if(source==='sinyi'){const links=[...document.querySelectorAll('nav[aria-label="SEO Pagination"] a')];total=Math.max(0,...links.map(e=>n(e.textContent)));page=Number(url.pathname.match(/\/(\d+)\/?$/)?.[1]||1);if(total>page){const exact=links.find(e=>n(e.textContent)===page+1);if(exact)next=exact.href;else{url.pathname=url.pathname.replace(/\/\d+\/?$/,'').replace(/\/$/,'')+'/'+(page+1);next=url.href;}}}
 if(source==='591'){const p=document.querySelector('.paginator-container');page=n(p?.querySelector('.active')?.textContent);total=Math.max(0,...[...p?.querySelectorAll('.paging a')||[]].map(e=>n(e.textContent)));const a=[...p?.querySelectorAll('.navigator a')||[]].find(e=>e.textContent.includes('下一頁'));if(a&&!a.parentElement.classList.contains('disabled')&&a.getAttribute('href')){const target=new URL(a.href);target.pathname='/';target.searchParams.delete('page');target.searchParams.set('firstRow',String(page*30));next=target.href;}}
 const empty=!rows.length&&/沒有符合.*(?:物件|房屋)|查無符合|共\s*0\s*(?:筆|戶)|找到\s*0\s*間/.test(document.body.innerText);
 return {rows,page,total,next,complete:empty||!!(page&&total&&page>=total&&!next),blocked:/驗證您是否|verify you are human|checking your browser|access denied|just a moment/i.test(document.title+' '+document.body.innerText.slice(0,1600))};
};
