// Pagination is based on each site's visible controls; absence is not proof of completion.
globalThis.crmReadPage=function(source,city){
 if(/驗證您是否|verify you are human|checking your browser|access denied|just a moment/i.test(document.title+' '+document.body.innerText.slice(0,1600)))return {rows:[],blocked:true,complete:false};
 const confirmedEmpty=(source==='591'&&location.hostname==='business.591.com.tw'&&/已為你找到\s*0\s*筆物件/.test(document.body.innerText))||(source==='sinyi'&&/共有\s*0\s*筆/.test(document.body.innerText))||(source==='yungching'&&/抱歉，暫無符合物件/.test(document.body.innerText))||(source==='591'&&/抱歉，[\s\S]{0,100}內暫無[\s\S]{0,100}相關內容/.test(document.body.innerText));
 if(confirmedEmpty)return {rows:[],page:0,total:0,next:null,complete:true,blocked:false};
 const rows=crmReadListings(source,city),n=x=>Number(String(x||'').replace(/[^0-9]/g,'')),url=new URL(location.href);let page=0,total=0,next=null;
 if(source==='yungching'){page=n(document.querySelector('.paginationPageListItem.actived')?.textContent);total=Math.max(0,...[...document.querySelectorAll('.paginationPageListItem')].map(e=>n(e.textContent)));if(page&&total>page){url.pathname=url.pathname.replace('/region/','/list/');url.searchParams.set('pg',page+1);next=url.href;}}
 if(source==='rakuya'){const p=document.querySelector('#app_pagination');page=n(p?.querySelector('input')?.value);total=n(p?.textContent.match(/共\s*([\d,]+)\s*頁/)?.[1]);if(page&&total>page){url.searchParams.set('page',page+1);next=url.href;}}
 if(source==='leju'){page=n(document.querySelector('.page-item.active')?.textContent)||n(url.searchParams.get('page'))||1;total=n(document.querySelector('[aria-label="最後一頁"]')?.textContent)||Math.max(0,...[...document.querySelectorAll('a.page-item')].map(e=>n(e.textContent)));const last=document.querySelector('button[aria-label="下一頁"]');if(last&&!last.disabled&&total>page){url.searchParams.set('page',page+1);next=url.href;}}
 if(source==='sinyi'){const links=[...document.querySelectorAll('nav[aria-label="SEO Pagination"] a')];total=Math.max(0,...links.map(e=>n(e.textContent)));page=Number(url.pathname.match(/\/(\d+)\/?$/)?.[1]||1);if(total>page){url.pathname=url.pathname.replace(/\/\d+\/?$/,'').replace(/\/$/,'')+'/'+(page+1);next=url.href;}}
 if(source==='591'){const p=document.querySelector('.paginator-container');page=n(p?.querySelector('.active')?.textContent);total=Math.max(0,...[...p?.querySelectorAll('.paging a')||[]].map(e=>n(e.textContent)));const a=[...p?.querySelectorAll('.navigator a')||[]].find(e=>e.textContent.includes('下一頁'));if(a&&!a.parentElement.classList.contains('disabled')&&a.getAttribute('href')){const target=new URL(url.href);if(url.hostname==='business.591.com.tw'){const link=new URL(a.getAttribute('href'),url);if(link.origin===url.origin&&link.pathname==='/list'&&link.searchParams.get('type')==='2')next=link.href;}else{target.pathname='/';target.searchParams.delete('page');target.searchParams.set('firstRow',String(page*30));next=target.href;}}}

 const empty=confirmedEmpty||!rows.length&&/沒有符合.*(?:物件|房屋)|查無符合|共\s*0\s*(?:筆|戶)|找到\s*0\s*間/.test(document.body.innerText);
 return {rows:confirmedEmpty?[]:rows,page,total,next:confirmedEmpty?null:next,complete:empty||!!(page&&total&&page>=total&&!next),blocked:/驗證您是否|verify you are human|checking your browser|access denied|just a moment/i.test(document.title+' '+document.body.innerText.slice(0,1600))};
};
