// Reads rendered listing cards / embedded public listing data only. No requests or page script execution.
globalThis.crmReadListings=function(source,city){
 const txt=(e,s)=>e.querySelector(s)?.textContent.trim()||'',num=s=>s==null||s===''?null:Number.isFinite(Number(String(s).replaceAll(',','')))?Number(String(s).replaceAll(',','')):null,first=s=>num(String(s||'').replaceAll(',','').match(/[\d.]+/)?.[0]),loc=a=>{const m=a.replaceAll('臺','台').match(/^(台北市|新北市)([^市縣]{1,4}[區鄉鎮市])/);return {city:m?.[1]||city,district:m?.[2]||''};};
 const age=s=>/個月/.test(s)?first(s)/12:/年/.test(s)?first(s):null;
 const normalize=t=>t==='電梯大廈'?'電梯大樓':t==='大樓'?'電梯大樓':t==='透天厝'?'透天':t;
 let rows=[];
 if(source==='rakuya')rows=[...document.querySelectorAll('a[href*="ehid="]')].filter(e=>e.querySelector('.card__head h2')).map(e=>{const info=txt(e,'.info__detail-info'),floor=txt(e,'.info__floor'),district=txt(e,'.info__geo--area'),geo=txt(e,'.info__geo'),tags=txt(e,'.group__tags');return {id:'rakuya:'+new URL(e.href).searchParams.get('ehid'),source,url:e.href,title:txt(e,'.card__head h2'),city,district,address:city+geo.replace(/\s+/g,' '),community:txt(e,'.info__geo--community'),price:first(txt(e,'.info__price--total')),area:first(txt(e,'.info__space')),mainArea:first(txt(e,'.info__space--main')),rooms:first(info.match(/([\d.]+)房/)?.[1]),age:age(info.match(/[\d.]+(?:年|個月)/)?.[0]||''),type:normalize(e.querySelector('.info__detail-info li')?.textContent.trim()||''),floor:num(floor.split('/')[0]),totalFloors:num(floor.split('/')[1]?.replace('樓','')),parking:/車位/.test(tags)?true:null,parkingType:/平面車位/.test(tags)?'平面':undefined,image:e.querySelector('img')?.src||'',description:tags};});
 if(source==='leju')rows=[...document.querySelectorAll('a[href^="/sales/"]')].map(a=>{const e=a.parentElement,title=a.textContent.trim().replace(/^查看物件：/,''),texts=[...e.querySelectorAll('div,span')].filter(x=>!x.children.length).map(x=>x.textContent.trim()),address=texts.find(t=>/^[^\s]{1,4}區/.test(t))||'',floor=texts.find(t=>/^[\d.-]+\/[\d]+樓$/.test(t))||'',price=texts.find(t=>/^[\d,.]+(?:億(?:[\d,.]+萬)?|萬)$/.test(t))||'',type=texts.find(t=>/^(?:店面|廠辦|公寓|大樓|華廈|套房|透天|別墅|土地)/.test(t)&&t.length<9)||'';let total=null;const pm=price.replaceAll(',','').match(/^(?:(\d+(?:\.\d+)?)億)?(?:(\d+(?:\.\d+)?)萬)?$/);if(pm)total=(Number(pm[1])||0)*10000+(Number(pm[2])||0);return {id:'leju:'+a.getAttribute('href').split('/').pop(),source,url:a.href,title,address:city+address,...loc(city+address),price:total,area:first(texts.find(t=>/^[\d.]+坪$/.test(t))),mainArea:null,rooms:first(texts.find(t=>/\d+房\d+廳/.test(t))?.match(/(\d+)房/)?.[1]),age:age(texts.find(t=>/^[\d.]+(?:年|個月)$/.test(t))||''),floor:num(floor.split('/')[0]),totalFloors:num(floor.split('/')[1]?.replace('樓','')),type:normalize(type),parking:e.querySelector('img[alt="車位"]')?true:null,community:txt(e,'a[href*="/community/"]'),image:e.querySelector('img[alt="物件照片"]')?.src||'',description:[...e.querySelectorAll('button')].map(b=>b.textContent.trim()).join(' ')};});
 if(source==='yungching')rows=[...document.querySelectorAll('.search-result-list-item > yc-ng-buy-house-card')].filter(e=>e.checkVisibility()).map(e=>{const a=e.querySelector('a[href*="house/"]'),address=txt(e,'.address'),fl=txt(e,'.floor'),tags=txt(e,'.note')+' '+txt(e,'.tag-list');return {id:'yungching:'+a?.href.match(/house\/(\d+)/)?.[1],source,url:a?.href,title:txt(e,'.caseName'),address,...loc(address),price:num(txt(e,'.price')),area:first(txt(e,'.regArea')),mainArea:first(txt(e,'.mainArea')),community:txt(e,'.community'),parkingType:/平面/.test(txt(e,'.car'))?'平面':undefined,rooms:first(txt(e,'.room').match(/([\d.]+)房/)?.[1]),age:first(txt(e,'.case-info').match(/([\d.]+)年/)?.[1]),type:normalize(txt(e,'.caseType')),floor:num(fl.split('/')[0]),totalFloors:num(fl.split('/')[1]?.replace('樓','')),parking:/含車位|坡道平面|坡道機械|升降平面|升降機械/.test(e.textContent)?true:null,image:e.querySelector('img')?.src||'',description:tags};});
 if(source==='sinyi'){const j=JSON.parse(document.querySelector('#__NEXT_DATA__')?.textContent||'{}');rows=(j.props?.initialReduxState?.buyReducer?.list||[]).filter(o=>!o.isOff).map(o=>({id:'sinyi:'+o.houseNo,source,url:'https://www.sinyi.com.tw/buy/house/'+o.houseNo,title:o.name,community:o.commName||'',address:o.address,...loc(o.address),price:num(o.totalPrice),area:num(o.areaBuilding),rooms:first(String(o.layout||'').match(/([\d.]+)房/)?.[1]),age:first(o.age),type:normalize(txt(document,'a[href*="'+o.houseNo+'"] [class*="type-badge"]')),floor:num(o.floor),totalFloors:num(o.totalfloor),parking:typeof o.isParking==='boolean'?o.isParking:null,image:o.image?.[0]||'',description:o.layout||''}));}
 if(source==='591')rows=globalThis.crmRead591(document);
 return [...new Map(rows.filter(p=>p.title&&p.district&&p.price>0&&p.url&&!p.id.endsWith('undefined')).map(p=>[p.id,p])).values()];
};
