(()=>{const acorn=globalThis.acorn;
const number=v=>v===null||v===undefined||v===''?null:Number.isFinite(Number(String(v).replace(/,/g,'')))?Number(String(v).replace(/,/g,'')):null;
const firstNumber=v=>{const m=String(v??'').match(/[\d.]+/);return m?number(m[0]):null;};
const location=address=>{const m=String(address||'').replaceAll('臺','台').match(/^(台北市|新北市)([^市縣]{1,4}[區鄉鎮市])/);return {city:m?.[1]||'',district:m?.[2]||''};};
// Decode Nuxt's literal-only data envelope. No eval/vm or arbitrary calls.
function literal(n,env={}){if(!n)throw Error('資料缺漏');switch(n.type){case'Literal':return n.value;case'Identifier':if(Object.hasOwn(env,n.name))return env[n.name];throw Error('未知資料變數');case'UnaryExpression':if(n.operator==='void'&&n.argument.type==='Literal'&&n.argument.value===0)return null;if(n.operator==='-')return -literal(n.argument,env);if(n.operator==='!')return !literal(n.argument,env);throw Error('不支援的資料格式');case'NewExpression':if(n.callee.type==='Identifier'&&n.callee.name==='Set'&&n.arguments.length===1&&n.arguments[0].type==='ArrayExpression')return literal(n.arguments[0],env);throw Error('不支援的資料結構');case'ArrayExpression':return n.elements.map(x=>literal(x,env));case'ObjectExpression':return Object.fromEntries(n.properties.map(p=>{if(p.type!=='Property'||p.computed||p.method)throw Error('不支援的資料欄位');return [p.key.name??p.key.value,literal(p.value,env)];}));default:throw Error('不支援的資料節點 '+n.type);}}
function nuxt(html){const script=[...html.querySelectorAll('script')].map(x=>x.textContent).find(s=>s?.startsWith('window.__NUXT__='));if(!script)throw Error('找不到公開物件資料');const ast=acorn.parse(script,{ecmaVersion:2020}),assign=ast.body[0]?.expression,call=assign?.right;if(assign?.type!=='AssignmentExpression'||call?.type!=='CallExpression'||call.callee.type!=='FunctionExpression'||call.callee.body.body.length!==1||call.callee.body.body[0].type!=='ReturnStatement')throw Error('資料格式已變更');const env={};call.callee.params.forEach((p,i)=>{if(p.type!=='Identifier')throw Error('資料格式已變更');env[p.name]=literal(call.arguments[i]);});return literal(call.callee.body.body[0].argument,env);}
function walk(o,predicate,out=[]){if(!o||typeof o!=='object')return out;if(predicate(o))out.push(o);else for(const v of Object.values(o))walk(v,predicate,out);return out;}
function parse591(html){return walk(nuxt(html),o=>o.houseid&&o.title&&o.region_name&&o.price!==undefined).filter(o=>o.kind&&o.address&&!o.is_newhouse).map(o=>({id:'591:'+o.houseid,source:'591',url:'https://sale.591.com.tw/home/house/detail/2/'+o.houseid+'.html',title:o.title,address:(o.region_name||'')+(o.section_name||'')+(o.address||''),city:o.region_name,district:o.section_name,price:number(o.price),area:number(o.area),mainArea:number(o.mainarea)||null,floor:number(String(o.floor||'').split('/')[0].replace(/F$/,'')),totalFloors:number(String(o.floor||'').split('/')[1]?.replace(/F$/,'')),parkingType:o.cartmodel||'',rooms:firstNumber(o.room),age:o.showhouseage&&/年/.test(o.showhouseage)?firstNumber(o.showhouseage):null,type:o.shape_name||o.kind_name||'',parking:o.has_carport===1?true:o.has_carport===0?false:null,image:o.photo_url||'',community:o.community_name||'',description:(o.tag||[]).map(t=>typeof t==='string'?t:t.name||'').join(' ')}));}

globalThis.crmRead591=parse591;})();