// Reads rendered listing cards / embedded public listing data only. No requests or page script execution.
globalThis.crmReadListings=function(source,city){
 const txt=(e,s)=>e.querySelector(s)?.textContent.trim()||'',num=s=>s==null||s===''?null:Number.isFinite(Number(String(s).replaceAll(',','')))?Number(String(s).replaceAll(',','')):null,first=s=>num(String(s||'').replaceAll(',','').match(/[\d.]+/)?.[0]),loc=a=>{const m=a.replaceAll('臺','台').match(/^(台北市|新北市|桃園市|台中市|台南市|高雄市|基隆市|新竹市|新竹縣|苗栗縣|彰化縣|南投縣|雲林縣|嘉義市|嘉義縣|屏東縣|宜蘭縣|花蓮縣|台東縣|澎湖縣|金門縣|連江縣)(.{1,4}?區|.{1,4}?[鄉鎮市])/);return {city:m?.[1]||a.match(/^(新竹市|嘉義市)/)?.[1]||city,district:m?.[2]||''};};
 const age=s=>/個月/.test(s)?first(s)/12:/年/.test(s)?first(s):null;
 const normalize=t=>t==='電梯大廈'?'電梯大樓':t==='大樓'?'電梯大樓':t==='透天厝'?'透天':t;
 let rows=[];
 if(source==='rakuya')rows=[...document.querySelectorAll('a[href*="ehid="]')].filter(e=>e.querySelector('.card__head h2')).map(e=>{const info=txt(e,'.info__detail-info'),floor=txt(e,'.info__floor'),district=txt(e,'.info__geo--area'),geo=txt(e,'.info__geo'),tags=txt(e,'.group__tags');return {id:'rakuya:'+new URL(e.href).searchParams.get('ehid'),source,url:e.href,title:txt(e,'.card__head h2'),city,district,address:city+geo.replace(/\s+/g,' '),community:txt(e,'.info__geo--community'),price:first(txt(e,'.info__price--total')),area:first(txt(e,'.info__space')),mainArea:first(txt(e,'.info__space--main')),rooms:first(info.match(/([\d.]+)房/)?.[1]),age:age(info.match(/[\d.]+(?:年|個月)/)?.[0]||''),type:normalize(e.querySelector('.info__detail-info li')?.textContent.trim()||''),floor:num(floor.split('/')[0]),totalFloors:num(floor.split('/')[1]?.replace('樓','')),parking:/車位/.test(tags)?true:null,parkingType:/平面車位/.test(tags)?'平面':undefined,image:e.querySelector('img')?.src||'',description:tags};});
 if(source==='leju')rows=[...document.querySelectorAll('a[href^="/sales/"]')].map(a=>{const e=a.parentElement,title=a.textContent.trim().replace(/^查看物件：/,''),texts=[...e.querySelectorAll('div,span')].filter(x=>!x.children.length).map(x=>x.textContent.trim()),address=texts.find(t=>/^[^\s]{1,4}區/.test(t))||'',floor=texts.find(t=>/^[\d.-]+\/[\d]+樓$/.test(t))||'',price=texts.find(t=>/^[\d,.]+(?:億(?:[\d,.]+萬)?|萬)$/.test(t))||'',type=texts.find(t=>/^(?:店面|廠辦|公寓|大樓|華廈|套房|透天|別墅|土地)/.test(t)&&t.length<9)||'';let total=null;const pm=price.replaceAll(',','').match(/^(?:(\d+(?:\.\d+)?)億)?(?:(\d+(?:\.\d+)?)萬)?$/);if(pm)total=(Number(pm[1])||0)*10000+(Number(pm[2])||0);return {id:'leju:'+a.getAttribute('href').split('/').pop(),source,url:a.href,title,address:city+address,...loc(city+address),price:total,area:first(texts.find(t=>/^[\d.]+坪$/.test(t))),mainArea:null,rooms:first(texts.find(t=>/\d+房\d+廳/.test(t))?.match(/(\d+)房/)?.[1]),age:age(texts.find(t=>/^[\d.]+(?:年|個月)$/.test(t))||''),floor:num(floor.split('/')[0]),totalFloors:num(floor.split('/')[1]?.replace('樓','')),type:normalize(type),parking:e.querySelector('img[alt="車位"]')?true:null,community:txt(e,'a[href*="/community/"]'),image:e.querySelector('img[alt="物件照片"]')?.src||'',description:[...e.querySelectorAll('button')].map(b=>b.textContent.trim()).join(' ')};});
 if(source==='yungching')rows=[...document.querySelectorAll('.search-result-list-item > yc-ng-buy-house-card')].filter(e=>e.checkVisibility()).map(e=>{const a=e.querySelector('a[href*="house/"]'),address=txt(e,'.address'),fl=txt(e,'.floor'),tags=txt(e,'.note')+' '+txt(e,'.tag-list');return {id:'yungching:'+a?.href.match(/house\/(\d+)/)?.[1],source,url:a?.href,title:txt(e,'.caseName'),address,...loc(address),price:num(txt(e,'.price')),area:first(txt(e,'.regArea')),mainArea:first(txt(e,'.mainArea')),community:txt(e,'.community'),parkingType:/平面/.test(txt(e,'.car'))?'平面':undefined,rooms:first(txt(e,'.room').match(/([\d.]+)房/)?.[1]),ageText:txt(e,'.case-info').match(/預售(?:屋)?|新成屋|[\d.]+年/)?.[0]||'',age:first(txt(e,'.case-info').match(/([\d.]+)年/)?.[1]),type:normalize(txt(e,'.caseType')),floorText:fl,floor:num(fl.split('/')[0]),totalFloors:num(fl.split('/')[1]?.replace('樓','')),parking:/含車位|坡道平面|坡道機械|升降平面|升降機械/.test(e.textContent)?true:null,image:e.querySelector('img')?.src||'',description:tags};});
 if(source==='sinyi'){const j=JSON.parse(document.querySelector('#__NEXT_DATA__')?.textContent||'{}');rows=(j.props?.initialReduxState?.buyReducer?.list||[]).filter(o=>!o.isOff).map(o=>({id:'sinyi:'+o.houseNo,source,url:'https://www.sinyi.com.tw/buy/house/'+o.houseNo,title:o.name,community:o.commName||'',address:o.address,...loc(o.address),price:num(o.totalPrice),area:num(o.areaBuilding),rooms:first(String(o.layout||'').match(/([\d.]+)房/)?.[1]),ageText:String(o.age??''),age:first(o.age),type:normalize(txt(document,'a[href*="'+o.houseNo+'"] [class*="type-badge"]')),floorText:String(o.floor??''),floor:num(o.floor),totalFloors:num(o.totalfloor),parking:typeof o.isParking==='boolean'?o.isParking:null,image:o.image?.[0]||'',description:o.layout||''}));}
 if(source==='591')rows=globalThis.crmRead591(document,city);
 return [...new Map(rows.filter(p=>p.title&&(p.district||['新竹市','嘉義市'].includes(p.city))&&p.price>0&&p.url&&!p.id.endsWith('undefined')).map(p=>[p.id,p])).values()];
};

// Detail fields are distinct from source search categories.
globalThis.crmReadYCDetail=doc=>{const field=name=>{const h=[...doc.querySelectorAll('.item h4')].find(e=>e.textContent.trim()===name);return h?.closest('.item')?.querySelector('.item-detail')?.textContent.trim()||'';};const usage=field('謄本用途'),buildingType=field('型態')||doc.querySelector('.case-type')?.textContent.trim()||'';return {...(usage?{usage,usageEvidence:'永慶謄本用途'}:{}),...(buildingType?{buildingType,type:buildingType}:{}),...(/^(住宅大樓|電梯大樓|電梯大廈)$/.test(buildingType)?{elevator:true}:{}),...(usage||buildingType?{availability:'available'}:{})};};
globalThis.crmReadSinyiDetail=(doc,id)=>{let data;try{data=JSON.parse(doc.querySelector('#__NEXT_DATA__')?.textContent||'{}').props?.initialReduxState?.buyReducer;}catch{return {};}const detail=data?.detailData,content=data?.contentData;if(String(detail?.houseNo)!==String(id))return {};const out={},usage=String(detail.detail?.purpose||'').trim();if(usage)Object.assign(out,{usage,usageEvidence:'信義謄本用途'});if(String(content?.houseNo)===String(id)){
 const numeric=(value)=>value!==null&&value!==undefined&&String(value).trim()!==''&&Number.isFinite(Number(value))?Number(value):null;
 for(const [key,source]of Object.entries({area:'areaBuilding',landArea:'areaLand',price:'totalPrice',totalFloors:'floors'})){const v=numeric(content[source]);if(v!==null)out[key]=v;}
 const layout=String(content.layout||'');for(const [key,unit]of [['rooms','房'],['halls','廳'],['bathrooms','衛']]){const match=layout.match(new RegExp('(\\d+)'+unit));if(match)out[key]=Number(match[1]);}
 if(content.floor!==null&&content.floor!==undefined)out.floorText=String(content.floor);
 if(content.age){out.ageText=String(content.age);const match=out.ageText.match(/^(\d+(?:\.\d+)?)年$/);if(match)out.age=Number(match[1]);}
 out.sinyiDetails={};
 for(const key of ['houseNo','name','cityName','zipName','commId','commName','address','totalPrice','priceFirst','uniPrice','rawUniPrice','isParking','areaBuilding','areaLand','pingUsed','layout','totalLayout','age','floor','floors','areaInfo','sfside','sfdarkroom','hasmanager','monthlyFee','roomplus','hallplus','bathroomplus','openroomplus','houseFront','buildingFront','windowFront','parking','latitude','longitude','firstDisplay','images','layoutImage','layoutImage3D','vrUrl','videoUrl'])if(content[key]!==undefined)out.sinyiDetails[key]=content[key];
 out.sinyiDetails.building=detail.detail||{};out.sinyiDetails.features=detail.description||[];
 out.sinyiDetails.neighborhood=(detail.lifeInfo||[]).map(group=>({type:group.type,places:(group.info||[]).map(({title,distance,time})=>({title,distance,time}))}));
 const raw=content.areaInfo?.find(x=>x.title==='主建物')?.area;if(raw!==null&&raw!==undefined&&String(raw).trim()!==''&&Number.isFinite(Number(raw))&&Number(raw)>0)out.mainArea=Number(raw);const parking=String(content.parking||'').trim();if(parking&&/平面|機械/.test(parking)){out.parking=true;out.parkingType=parking;}else if(content.isParking===false)out.parking=false;}if(Object.keys(out).length)out.availability='available';return out;};
globalThis.crmVerifyListings=async rows=>{const out=[];for(const row of rows){let value={};try{if(row.source==='591'){const id=row.id.split(':').pop(),response=await fetch('https://bff-house.591.com.tw/v1/web/sale/detail?id='+encodeURIComponent(id),{signal:AbortSignal.timeout(6000)});if(response.ok)value=globalThis.crmRead591API(await response.json(),id)||{};}if(!value.availability){const response=await fetch(row.url,{signal:AbortSignal.timeout(6000)});if([404,410].includes(response.status))value={availability:'unavailable',availabilityReason:'原物件頁已失效（HTTP '+response.status+'）'};else if(response.ok){const doc=new DOMParser().parseFromString(await response.text(),'text/html');value=row.source==='yungching'?globalThis.crmReadYCDetail(doc):row.source==='sinyi'?globalThis.crmReadSinyiDetail(doc,row.id.slice(6)):globalThis.crmRead591Detail(doc);}}}catch{}const at=new Date().toISOString(),success=Object.keys(value).length>0;out.push({id:row.id,...value,detailAttemptedAt:at,detailStatus:success?'ok':'failed',detailError:success?'':'原站讀取失敗或未取得可核對欄位',...(success?{detailCheckedAt:at}:{})});}return out;};
